### ISSUE TITLE
Cancel scheduled message with MessageId

### ISSUE THREAD

**Issue by vincentyau** [Azure/azure-service-bus-dotnet#100]
This is a question not an issue. Is there a way to cancel scheduled message base on MessageId? 
In recently version, the CancelScheduledMessageAsync is added to support cancel message by SequenceId. 
I compose all the MessageIds for deduping purpose.  So I know all the messages by MessageId, but not the SequenceId.  Is there a work around for this, like MessageId to SequenceId lookup?  Thanks.

**Comment by jtaubensee** [comment]
Unfortunately there is not a way to cancel a message by the id. The reason being, is that you can send multiple messages with the same id, and if you didnt have deduplication turned on, Service Bus would accept those messages. Sequence number is the only field that is guaranteed to be unique per message. Scheduling messages does require you to keep track of sequence numbers in case you want to cancel a message.

**Comment by vincentyau** [comment]
Thanks for your quick response.
