### ISSUE TITLE
Issue with implicit load of assemblies

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus-dotnet#101]
I have created one .net core application (ASM1).
Application assembly ASM1 references project assembly ASM2.
ASM2 references by nugget Azure Service Bus client.

When trying to send the message, application fails with following error:
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Net.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
```

It fails at following line in `async Task<AmqpConnection> CreateConnectionAsync(TimeSpan timeout)`:
```csharp
AmqpSettings amqpSettings = AmqpConnectionHelper.CreateAmqpSettings(
                amqpVersion: ServiceBusConnection.AmqpVersion,
                useSslStreamSecurity: true,
                hasTokenProvider: true);
```

SB client has dependency to this assembly, but .NET core framework does not load it at all. It is not redirection problem. Assembly is really not loaded. It does not appear in the list of loaded modules.

If we really have assembly load issue, I guess it will not be an issue of SB Client. It is more related to .NET Core team.

**Comment by ddobric** [comment]
Workaround for this is to add explicit reference to missing assembly (in this case 'System.Net.Security, Version=4.0.0.0) from the top assembly (in this case ASM1).

**Comment by jtaubensee** [comment]
@ddobric - Is this still an issue for you? I haven't seen this on my side yet.
