### ISSUE TITLE
Support HTTPS connectivity mode

### ISSUE THREAD

**Issue by jnevins-gcm** [Azure/azure-service-bus-dotnet#102]
## Actual Behavior
1. TCP connections are blocked
2.  Clients fail to connect

## Expected Behavior
1. Client(s) fall back to HTTP/HTTPS

## Versions  
- OS platform and version: Windows 7
- .NET Version: netstandard1.3
- NuGet package version or commit ID: master

Is this already supported? If so, how can I make it work?

**Comment by jtaubensee** [comment]
@jnevins-gcm - This is not currently supported, and it will likely be a little while before we get to it. But thank you for adding the issue so we can track it.

**Comment by jnevins-gcm** [comment]
Do you have a timeline on nuget package availability and first non-preview release?

**Comment by SeanFeldman** [comment]
@jnevins-gcm there's an issue specifically for nuget package you might want to track, issue #49

**Comment by jtaubensee** [comment]
@jnevins-gcm - The support will actually be provided through the dependency library, which is azure/azure-amqp#57

Ditto @SeanFeldman

**Comment by SeanFeldman** [comment]
@nemakam this is covered by #288 ?

**Comment by nemakam** [comment]
Expect this functionality to ship with our next release of 1.1.0.
