### ISSUE TITLE
Thrown Fault & Timeout exceptions cluttering debug output

### ISSUE THREAD

**Issue by adam3039** [Azure/azure-service-bus-dotnet#103]
I am able to resolve this by enabling "Just My Code" in the debugger options of Visual Studio, but is this really the best approach? Seems like a bit of a work around. I'm getting exceptions thrown every 20-30 seconds, usually about 50-70 lines of Timeout & Fault exceptions from the Microsoft.Servicebus.dll at a time. As you can imagine, this really clutters the debug output.

    Exception thrown: 'System.ServiceModel.FaultException'1' in Microsoft.ServiceBus.dll

    Exception thrown: 'System.ServiceModel.FaultException1' in Microsoft.ServiceBus.dll

    Exception thrown: 'System.ServiceModel.FaultException1' in Microsoft.ServiceBus.dll

    Exception thrown: 'System.ServiceModel.FaultException1' in Microsoft.ServiceBus.dll

    Exception thrown: 'System.ServiceModel.FaultException1' in Microsoft.ServiceBus.dll

    Exception thrown: 'System.TimeoutException' in Microsoft.ServiceBus.dll

**Comment by jtaubensee** [comment]
@adam3039 - The library you are referencing is not open source. This repo is for the new .NET Standard based library with the namespace 'Microsoft.Azure.ServiceBus'. Can you use this [link](https://www.nuget.org/packages/WindowsAzure.ServiceBus/ContactOwners) to send a message regarding that package?

**Comment by SeanFeldman** [comment]
@jtaubensee should this issue be moved to https://github.com/Azure/azure-service-bus instead to be addressed in the existing client?
