### ISSUE TITLE
Extensibility API

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#106]
Allow extension API to override/enrich certain behaviors 
Good candidates could be:
- Message ID generator (currently "baked" into the library) - #24 Allow registration of message id factory
- Mutation of incoming and outgoing message
- etc

This will open up an opportunity to plug-in customization or provide those as independent packages for consumption (@jtaubensee brought up an idea of a `KeyVault` package to secure messages, see example below).

Here's a proposed API:

`IClientEntity` to expose a property `Extensions` of a type `IExtension`

```c#
public interface IExtension
{
  IExtension MessageIdGenerator(Func<Message>, string> idGenerator);
  IExtension IncomingMessageMutator(Func<Message, Task<Message>> mutator);
  IExtension OutgoingMessageMutator(Func<Message, Task<Message>> mutator);
  // etc
}
```

This will allow configuration of customization that are only needed in the following manner:

```c#
queueClient.Extensions.MessageIdGenerator(message => $"{message.Id}_{DateTime.Now.ToString("s")}");
queueClient.Extensions.OutgoingMessageMutator(message =>HeaderMutator(message));
```

It will also allow creation of extension methods that could be packaged and distributed:

```c#

// KeVault package 

namespace Microsoft.Azure.ServiceBus.Extensions.KeyVault
{
  static class KeVaultExtensionExtensions
  {
    static void UseKeyVault(this IExtension extention, params...)
    {
       extention.IncomingMessageMutator(funcIn);
       extention.OutgoingMessageMutator(funcOut);
    }
  }
}
//...
```

Usage (of the package and in-project extensions):

```c#
queueClient.Extensions.UseKeyVault(params);
queueClient.Extensions.MessageIdGenerator(message => $"{message.Id}_{DateTime.Now.ToString("s")}");
queueClient.Extensions.OutgoingMessageMutator(message =>HeaderMutator(message));
```

**Main points**

1. Allow very specific extension points with clear API.
1. Extension points should not be "getting in the way" on the root level (ie only whoever is interested would access the API by going through `Extensions`).
1. Allow registration of multiple extensions for any extension APIs (e.g. multiple outgoing message mutators).

**Drawbacks**

Extensions are currently provided during the execution phase, which could lead to accidental dynamic changes by user. To solve this, it would require to split into two phases: (1) configuration phase and (2) execution phase, when extension points are locked. To implement 2-phased approach it would require to review the general API so that 

```c# 
var queueClient = new QueueClient(connectionString, queueName, recieveMode);
queueClient.Extensions.MessageIdGenerator(func);
```

Would become
```c#
// phase 1 - extensions are opened
var configuration = new QueueClientConfiguration();
configuration.MessageIdGenerator(func);
configuration.UseKeyVault(params);

// phase 2 - extensions will be locked by QueueClient and be read-only
var queueClient = new QueueClient(connectionString, queueName, recieveMode, configuration);
```

**Comment by jtaubensee** [comment]
@SeanFeldman - Sorry for the delay with my response. We are really excited about the idea of extensions, and are thinking of the following potential ideas:

* KeyVault
* Claim check (#141)
* Check sum
* Compression

These extension points are very powerful, as they would give you access to mutate the message on send and receive. This also adds to potential debugging confusion / performance testing, etc.

With that said, we want the extension **points** to only be available on the `MessageSender` & `MessageReceiver`. Based on #87, we decided that the Queue/Topic/Subscription were desiged for simple use cases, and Sender/Receivers are for the more advanced scenarios.

However, this does not mean that you wouldn't be able to use extensions with the clients. Instead, you would need to implement an abstract class to do so.

```csharp
public abstract class ServiceBusPlugin
{
	public virtual Task<Message> BeforeMessageSend(Message message)
	{
		return Task.FromResult(message);
	}

	public virtual Task AfterMessageSend()
	{
		return Task.FromResult<object>(null);
	}

	public virtual Task<Message> AfterMessageReceive(Message message)
	{
		return Task.FromResult(message);
	}

	public virtual Task BeforeMessageReceive()
	{
		return Task.FromResult<object>(null);
	}
}
```

So one of the methods in my KeyVault plugin, could look like this:
```csharp
public override async Task<Message> BeforeMessageSend(Message message)
{
	if (message.UserProperties.ContainsKey(Constants.InitializationVectorPropertyName) || message.UserProperties.ContainsKey(Constants.KeyNamePropertyName))
	{
		return message;
	}

	var iV = await EncryptionHelper.GenerateInitializationVector();
	var secret = await secretManager.GetHashedSecret(secretName);

	message.UserProperties.Add(Constants.InitializationVectorPropertyName, Convert.ToBase64String(iV));
	message.UserProperties.Add(Constants.KeyNamePropertyName, secretName);

	message.Body = await EncryptionHelper.Encrypt(message.Body.GetString(), secret, iV);
	return message;
}
```

And in order to use the plugin with the clients, you would do the following:
```csharp
var keyVaultPluginOptions = new KeyVaultPluginOptions()
{
	AzureClientId = "",
	AzureClientSecret = "",
	KeyVaultEndpoint = ""
};
var keyVaultPlugin = new KeyVaultPlugin("ServiceBusExtension", keyVaultPluginOptions);

var qclient = new QueueClient("", "queue1");
qclient.UsePlugin(keyVaultPlugin);
```

Since the `QueueClient` is mostly a wrapper around a `MessageSender` and `MessageReceiver`, we are able to set the `BeforeMessageSend` on the `QueueClient`'s inner `MessageSender`.

Thoughts?

**Comment by SeanFeldman** [comment]
👍

**Comment by SeanFeldman** [comment]
A few items I'd like to bring up for discussion

1. Registration of the plugins should be restricted to the configuration time, not run-time. Should not be possible to plug an ad-hoc plugin in the middle of execution.
1. What will be the order of execution, per each step (out of 4 listed [here](https://github.com/Azure/azure-service-bus-dotnet/issues/106#issuecomment-297805676)), assuming multiple plugins are registered.
1. Would the plugins provided by the ASB team have a separate repo? They should be on a separate release cycle than the client itself.

**Comment by jtaubensee** [comment]
Closing based on #153
