### ISSUE TITLE
Interop support for other clients

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus-dotnet#114]
Have upgraded to 0.0.2-preview and running in some issues.

1. QueueClient does not have a method GetBody<>() as described in samples.
2. After receiving of the message property 'Body' is always NULL.
3. There is no more ReceiveAsync() method

**Comment by jtaubensee** [comment]
Hi @ddobric,

Please keep in mind that this is not a direct port of the older WindowsAzure.ServiceBus package. Since we are rewriting the library, we have taken the time to reorganize/redesign the api's and interfaces. For an example of this check out #87.

> QueueClient does not have a method GetBody<>() as described in samples

Which samples are you referring to?

> After receiving of the message property 'Body' is always NULL

Can you share some code?

> There is no more ReceiveAsync() method

Same as response in #13.

**Comment by ddobric** [comment]
**Receiver is the original sample code from repo:**

`
  private static void ReceiveMessages()
        {
            try
            {
                // Register a OnMessage callback
                queueClient.RegisterMessageHandler(
                    async (message, token) =>
                    {
                        // Process the message
                        Console.WriteLine($"Received message: SequenceNumber:{message.SystemProperties.SequenceNumber} Body:{Encoding.UTF8.GetString(**message.Body**)}");

                        // Complete the message so that it is not received again.
                        // This can be done only if the queueClient is opened in ReceiveMode.PeekLock mode.
                        await queueClient.CompleteAsync(message.SystemProperties.LockToken);
                    },
                    new RegisterHandlerOptions() {MaxConcurrentCalls = 1, AutoComplete = false});
            }
            catch (Exception exception)
            {
                Console.WriteLine($"{DateTime.Now} > Exception: {exception.Message}");
            }
        }
`

**Sender is based on SB .NET (Desktop)  SDK:**

`  
private static void sendMessage()
        {
            var sender = QueueClient.CreateFromConnectionString(..);

            MyType msg = new MyType()
            {
              . . .              
            };

            sender.SendAsync(createMessage(msg)).Wait();
        }

        private static BrokeredMessage createMessage(object sendingObject)
        {
            string strMsg = JsonConvert.SerializeObject(sendingObject);
            BrokeredMessage msg = new BrokeredMessage(UTF8Encoding.UTF8.GetBytes(strMsg));
            msg.Properties.Add("XYZ", "THIS WORKS");
            return msg;
        }`

After receiving message,Body is NULL!!!

**Comment by ddobric** [comment]
The problem seems to be in incomplete implementation of AmqpMessageConverter.
I have extended following method:
` public static SBMessage AmqpMessageToSBMessage(AmqpMessage amqpMessage)`

with following code:

` c#
else if (amqpMessage.BodyType == SectionFlag.Data && amqpMessage.DataBody != null)
{
                var data = amqpMessage.DataBody.FirstOrDefault();
                if (data != null)
                {
                    // Chek cast ???
                    var seg = (ArraySegment<byte>)data.Value;
                    sbMessage = new SBMessage(seg.ToArray());
                }
                else
                {
                    // ??
                    sbMessage = null;                   
                }
}
`

see [https://raw.githubusercontent.com/ddobric/azure-service-bus-dotnet/master/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs](changed file)

**Comment by jtaubensee** [comment]
@ddobric - You are correct about the interop scenario. Thanks for bringing this up. I have submitted #118 in place of #117. I also updated the samples and removed the `GetBody` method in the readmes: 53b8c1c84a0df8dbcd850b7223d15de9c11f27d1

Is there anything else that we need to track in this issue?

**Comment by ddobric** [comment]
Yes, you can :)
Pls. publish a new nuget package. Right now, using my one.

**Comment by jtaubensee** [comment]
Changing the milestone of this issue, and leaving it open as a reminder to test further interop scenarios for 1.0

**Comment by jtaubensee** [comment]
Added a ToDo item in  src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs

**Comment by SeanFeldman** [comment]
Optionally you can have a bookmark (link) pointing to the specific commit, file, and location in the file.

For the https://github.com/Azure/azure-service-bus-dotnet/issues/114#issuecomment-296243973, it would be. I use that trick to ease the navigation on the issues.

https://github.com/Azure/azure-service-bus-dotnet/blob/f5f78333522f81e4f7d3a497bad233d4265b3626/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs#L175

**Comment by nemakam** [comment]
Closing this with merge of #207
