### ISSUE TITLE
The name of class 'RegisterHandlerOptions' should be changed

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus-dotnet#120]
According to .NET naming convention  I think **'RegisterHandlerOptions'** should be renamed to
**''MessageHandlerOptions'** , because it is implied by **'RegisterMessageHandler()**' verb and it configure how registered **MessageHandler** should behave and not how method **RegisterHandler()** should behave.

**Comment by vinaysurya** [comment]
Hi Damir,

Thanks for bringing this up. We also noticed this and have already changed this while working on the OnSession Feature. I will link this issue to that codeflow.

Thanks,
Vinay

**Comment by jtaubensee** [comment]
closing based on #125
