### ISSUE TITLE
Ability to specify RetryPolicy for sender without of need to specify ReceiveMode

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus-dotnet#121]
When creating a queueClient instance for sending of messages, it would be useful to provide RetryPolicy, without of need to specify ReceiveMode.

NOW:
```csharp
eventSender = new QueueClient(m_StatusEventsQueueConnStr, "statusqueue", ReceiveMode.PeekLock, new RetryExponential(TimeSpan.FromSeconds(0), TimeSpan.FromSeconds(15), 5));
```
It would be good to have additional override:
```csharp
eventSender = new  QueueClient(m_StatusEventsQueueConnStr, "statusqueue", new RetryExponential(TimeSpan.FromSeconds(0), TimeSpan.FromSeconds(15), 5));
```

**Comment by jtaubensee** [comment]
@ddobric - This seems like a reasonable ask. Thanks.

**Comment by jtaubensee** [comment]
After some more thought my concern with this, is that we can end up with too many different overloads. And after looking at it further, you can do the following:

```csharp
var qClient = new QueueClient("connectionString", "queue1", retryPolicy: new RetryExponential(TimeSpan.FromSeconds(0), TimeSpan.FromSeconds(15), 5));
```

Since it is an optional parameter, you can specify it.

**Comment by nemakam** [comment]
@ddobric, That's a valid ask, but it might end up being a conflicting requirement for other folks who would always rely on `RetryPolicy.Default` and switch between using different `ReceiveMode`. 
And I personally don't want to have two overloads which differs only in the position of the params. Its more confusing than the approach @jtaubensee just suggested.
