### ISSUE TITLE
Create entity clients with ConnectionStringBuilder

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-service-bus-dotnet#122]
I still can remember time, when community was exited after we introduced ConnectionStrings and simplification with CreateFromConnectionString().

Why don't we have it now? just matter of time?

Refactoring this by migrating to new SDK is a kind of painful, because we need to deal with different connection strings (path cannot be part of connection string).

**Comment by jtaubensee** [comment]
The public constructor for a `QueueClient` accepts a connection string and entity path. So instead of a static "factory" style method, you can do the following:
```csharp
var qClient = new QueueClient("SuperSecretConnectionString", "queueName");
```

**Comment by ddobric** [comment]
Hi @jtaubensee , you are right.

the issue with contained path in connection string is not one more line of code. It is more about configuration strategy, which already exist around SB for ten years now. Strategy basically says: "Connection string for SB entity and store it somewhere".
Now we need two such artefacts: Connection String + path.

It is not big deal to enable this in the client. General expectation is always that new version of some SDK must always be an improvement and not a restriction.

**Comment by jtaubensee** [comment]
@ddobric - Yep, I think it makes most sense to have the ConnectionStringBuilder overload to avoid confusion.

Regarding the expectation of this being a "new version" of the old client: Think of this as more .NET Core, versus the .NET Framework. For example, the `WindowsAzure.ServiceBus` NuGet package was first uploaded 6 years ago, so this is a chance for us to do some "spring cleaning," and avoid the common pitfalls that customers have had in the past.

**Comment by nemakam** [comment]
Merged #136

**Comment by papatoob** [comment]
@jtaubensee  - Soon this hopefully won't matter anymore, but with 0.0.3-preview the following does not seem to work (at least with my tests):

> A valid work around for this would be to do the following:
>
>     var myConnectionString = "myConnectionString";
>     var csb = new ServiceBusConnectionStringBuilder(myConnectionString);
>     var qClient = new QueueClient(myConnectionString, csb.EntityPath);

Instead, this raises a `System.ArgumentException: NamespaceConnectionString should not contain EntityPath.` in `Microsoft.Azure.ServiceBus.Primitives.ServiceBusNamespaceConnection..ctor(String namespaceConnectionString, TimeSpan operationTimeout, RetryPolicy retryPolicy)`

So at this point I don't see a way to create a client from a "complete" ConnectionString containing the entity path.

**Comment by nemakam** [comment]
@papatoob , with this fix you should now be able to do this:
```csharp
var myConnectionString = "myConnectionString";
var csb = new ServiceBusConnectionStringBuilder(myConnectionString);
var qClient = new QueueClient(myConnectionString);
```

**Comment by papatoob** [comment]
Thanks. I will have to wait for the next NuGet package release though, since I'm not on VS 2017 yet.
