### ISSUE TITLE
Client name confusion

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#128]
The old client (WindowsAzure.ServiceBus) and the new client (this repo) are both SB clients 😃
The old client is not going away so fast, which will add to confusion.

Perhaps use some code names to distinguish between the two?

**Comment by jtaubensee** [comment]
Aren't `WindowsAzure.ServiceBus` and `Microsoft.Azure.ServiceBus` the respective code names?

**Comment by SeanFeldman** [comment]
If you expect people to type that up every time, then yes. Otherwise, nope.

**Comment by jtaubensee** [comment]
@SeanFeldman - Any suggestions then? I personally will be using the above names to reference the corresponding libraries, unless we come up with something better.

**Comment by SeanFeldman** [comment]
👍 I'll follow the same guidance. Not on the phone though. There it will be
"old" vs "new" 😉
