### ISSUE TITLE
Implement Abandon/Deadletter/Defer/RenewMessageLock

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#13]
_From @vinaysurya on October 12, 2016 2:2_

Following API Constructs will need to be implemented for this task:
a) AbandonAsync(Guid LockToken) and AbandonAsync(Guid lockToken, IDictionary<string, object> propertiesToModify)
b) DeadletterAsync(Guid lockToken), DeadletterAsync(Guid lockToken, IDictionary<string, object> propertiesToModify) and DeadLetterAsync(Guid lockToken, string deadLetterReason, string deadLetterErrorDescription)
c) DeferAsync(Guid LockToken), DeferAsync(Guid lockToken, IDictionary<string, object> propertiesToModify) and Receive(BySequenceNumber)
d) RenewMessageLockAsync(Guid LockToken)

_Copied from original issue: Azure/azure-messaging-dotnet#5_

**Comment by ddobric** [comment]
Hi all,

what is the state of RenewMessageLock?

**Comment by jtaubensee** [comment]
@ddobric - Are you wanting to use `RenewMessageLock` from the clients (i.e. Queue / Subscription client)?

If so, we don't have plans to implement this functionality, as this use case is handled by `AutoRenewTimeout` in the message handler.

In case you want to manually renew the message lock and use other advanced functionality, you would need to do so from the `MessageReceiver` which isn't quite public yet. Follow #57 for the status on that.

**Comment by ddobric** [comment]
Thanks. Right now, it is most important to support AutoRenew. MessageReceiver is welcome. :)
