### ISSUE TITLE
Add/implement IDisposable on ClientEntity

### ISSUE THREAD

**Issue by justdmitry** [Azure/azure-service-bus-dotnet#130]
`ClientEntity` (and it successors) have public `CloseAsync` method, which indicates that "good practice" is to close each client/entity after use.

For many years, this is known as Dispose pattern, and special `IDisposable` interface and `using` language construct are created for this scenario.

Please, add `IDisposable` interface to `ClientEntity` class.

**Comment by jtaubensee** [comment]
@justdmitry - So this is an interesting question. While in most cases it is proper to implement the IDisposible class, we don't necessarily want to encourage the `using` syntax. For example:

```csharp
using (var qClient = new QueueClient())
{
    qClient.SendAsync(new Message(Encoding.UTF8.GetBytes("Hello")));
}
```
In most cases, the `QueueClient` is long-lived, and a Windows service would create a single client and use it throughout the application.

What we ultimately want to avoid, is customers using the above example (using statement) repeatedly throughout their application. Under the covers this is creating a connection, sending a single message, and then closing the connection, which is a heavy series of operations.

**Comment by justdmitry** [comment]
Understand. 

That's looks like [HttpClient per call / singleton](http://stackoverflow.com/questions/22560971/what-is-the-overhead-of-creating-a-new-httpclient-per-call-in-a-webapi-client) issue...

Do you recommend (for web app) register it as a singleton for whole app lifetime? Does QueueClient/TopicClient are (or _planned to be_ in RTM) thread-safe?

**Comment by jtaubensee** [comment]
@justdmitry - Yep, its basically the same as HttpClient; that is a good comparison.

The clients should be thread safe. 

You've actually brought up a good point (which we were hoping to address later, but has some relevance here). See #134.
