### ISSUE TITLE
QueueClient Prefetch Can never be set

### ISSUE THREAD

**Issue by adminnz** [Azure/azure-service-bus-dotnet#135]
There is no way for a user to configure the prefetch count.
The only public QueueClient constructor requires a connectionString, and that connectionString cannot have anything apart from Endpoint, SharedAccessKeyName, SharedAccessKey, EntityPath in it (due to how the ServiceBusConnectionStringBuilder is implemented).

If the QueueClient's other constructor was exposed it would allow users to pass in a ServiceBusNamespaceConnection (which does allow you to set the Prefetch Count).

Or is the intention that if the user needs to prefetch and/or batch, they should implement everything this library is already doing?

**Comment by jtaubensee** [comment]
Closing based on #140.
