### ISSUE TITLE
Claim check support

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#141]
Feature request - support for [claim check pattern](http://www.enterpriseintegrationpatterns.com/patterns/messaging/StoreInLibrary.html).

**Comment by jtaubensee** [comment]
@SeanFeldman - This would likely be implemented as a plugin/extension, so this is on-hold for the meantime.

**Comment by SeanFeldman** [comment]
I've implemented claim check pattern here: https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin

It's already [on nuget](https://www.nuget.org/packages/ServiceBus.AttachmentPlugin) and can be test driven.

**Comment by nemakam** [comment]
Looks clean and good. Thanks for the implementation @SeanFeldman.

**Comment by SeanFeldman** [comment]
Thank you @nemakam for the review.
Any chance we could get NuGet package for the "OOTB" plugins going? I'm sure @jtaubensee would be happy to see it out 😃

**Comment by nemakam** [comment]
Don't have an ETA as of now, but I assure you its high on our radar. 😄

**Comment by SeanFeldman** [comment]
Great, appreciate sharing the status.
Last question - should I send a PR for the plugins [readme.md](https://github.com/Azure/azure-service-bus-dotnet-plugins/blob/dev/README.md) to add a section on community provided plugins? Hope ServiceBus.AttachmentPlugin will set an aspiring example and many more plugins will be added by the community.

**Comment by nemakam** [comment]
We have this in our mind already. We do want to add third party plugin links to our readme. But I'm sure there are policy requirements that we need to take care of before we endorse a third party plugin. So you could raise a PR if you want, but it will be blocked till we get this straightened out.

**Comment by SeanFeldman** [comment]
👍 sounds fair. Will raise PR to get the rest eventually moving.

**Comment by nemakam** [comment]
Closing this issue based on #13
