### ISSUE TITLE
Increase Extensibility by unsealing and making public

### ISSUE THREAD

**Issue by adminnz** [Azure/azure-service-bus-dotnet#145]
In the code's current state it is not very practical to extend anything because nearly all classes that actually do something are marked as private and/or sealed.
e.g. AmqpMessageReceiver, AmqpMessageSender, TopicClient, QueueClient, MessageReceivePump, etc

As per [MSDN Sealing](https://msdn.microsoft.com/en-us/library/ms229023(v=vs.110).aspx) 
> Sealing a class because you cannot think of an extensibility scenario is not a good reason.

Also the only point in the referenced link that kind of applies is to do with virtual members, but even then I don't see a valid reason why nearly the whole library is private/sealed.

For an actual extensibility scenario:
I know that for messages I'm sending to Azure Service Bus, if I could receive them in batches I could potentially make drastically less database calls as it is highly likely that a messages received in a small window of time (batch) are referring to the same entity in the database.
(note: the sending cannot be batched as multiple sources can be sending for the same entity)
But to implement this using the current code would require me to re-implement (not change, just implement so I have access) all of the AMQP namespace. Rewrite the MessageReceivePump and QueueClient even though only 1 or 2 methods that are actually being changed.

**Comment by jtaubensee** [comment]
@adminnz - Can you clarify your use case a little more? You want to batch receive? If so, you will be able to do that soon. 

#57 will allow you to use the MessageSender/Receiver objects which will have the more advanced scenarios you are looking for.

**Comment by adminnz** [comment]
Yes batch receive, so that I can do something like.
`var messages = await messageReceiver.ReceiveBatchAsync(batchSize: 500, waitTime: TimeSpan.FromSeconds(10));`

Where batchSize is the max number of messages to receive and waitTime is the maximum amount of time to wait for the 500 messages and if that time is reached then the call would return with whatever messages were pulled down.
Also handling Message locktoken renewal within all this.

**Comment by jtaubensee** [comment]
Sure. What you are saying is correct. With the Receiver you can call, `await messageReceiver.ReceiveAsync(numMessagesToReceive, waitTime)`. I have a PR open that will make this public. https://github.com/Azure/azure-service-bus-dotnet/pull/146

What kind of throughput are you expecting? With the sender/receiver, you are responsible for renewing the lock tokens on your own, but with the QueueClient, we handle this for you.
