### ISSUE TITLE
RegisterMessageHandler takes exactly 1 minute to complete

### ISSUE THREAD

**Issue by jack4it** [Azure/azure-service-bus-dotnet#154]
## Actual Behavior
1. The call of RegisterMessageHandler takes exactly 1 minute to complete

## Expected Behavior
1. Should this not be faster?
2. Why 1 minute though?

## Versions  
- OS platform and version: win 10, server 2012/2016
- .NET Version: 1.1.x
- NuGet package version or commit ID: 0.0.2, 0.0.3

**Comment by vinaysurya** [comment]
It does not have to be. I think today we wait for a whole minute waiting for a message to show up while we register the handler for the first time. We could just try waiting for a lesser time or for no time and still go ahead and register the handler anyway. I'll make that change and submit a PR.

**Comment by MPOSEIDON** [comment]
I am having the same issue. Why it is taking 1 minute to register message handler?

**Comment by SeanFeldman** [comment]
@MPOSEIDON see PR #183

**Comment by nemakam** [comment]
#183 is checked in. Next release should solve this issue
