### ISSUE TITLE
Road Map / The path to 1.0

### ISSUE THREAD

**Issue by GavinOsborn** [Azure/azure-service-bus-dotnet#159]
Is there a Road Map for getting to 1.0?
Something that details both:
 - Your goals when you hope to be done
 - What features are still out-standing.

At the moment it's hard to tell how far away you are from getting to a first major release.
It would also be great to understand what we can expect from a 1.0 release in terms of comparable feature parity with the existing SDKs.

Many Thanks

**Comment by aviita** [comment]
This blog post in msdn is even promising a roadmap, but it seems to have been removed from the Readme.md.

Blog post:
[https://blogs.msdn.microsoft.com/servicebus/2016/12/20/service-bus-net-standard-and-open-source/](https://blogs.msdn.microsoft.com/servicebus/2016/12/20/service-bus-net-standard-and-open-source/)

Roadmap link:
[https://github.com/Azure/azure-service-bus-dotnet#road-map](https://github.com/Azure/azure-service-bus-dotnet#road-map)

Some Readme.md history:
[https://github.com/Azure/azure-service-bus-dotnet/pull/86/files](https://github.com/Azure/azure-service-bus-dotnet/pull/86/files)

The whole Readme.md with some roadmap info from 4 Feb:
[https://github.com/Azure/azure-service-bus-dotnet/blob/125f684fe68b29538f1e19ce8ebc87e523149d99/README.md](https://github.com/Azure/azure-service-bus-dotnet/blob/125f684fe68b29538f1e19ce8ebc87e523149d99/README.md)

I did not look at what was the latest status before it was removed. Just the readme.md history and last mention I could find on roadmap in the commit message title.

**Comment by jtaubensee** [comment]
@GavinOsborn & @aviita - The road map that you are mentioning, was in place to help provide a **runtime** feature comparison between this client and the `WindowsAzure.ServiceBus` nuget package. Since we have reached **runtime** parity for all major use cases, we removed that reference from the readme.

We also found that we weren't using the tools at our disposal. Instead we have started using milestones: https://github.com/Azure/azure-service-bus-dotnet/milestones. In there you can see each item that we are currently tracking.

In case you are concerned with what is in the 1.0.0 milestone, take a look here: https://github.com/Azure/azure-service-bus-dotnet/milestone/6

We are nearly there, and the issues in that milestone are straightforward. What keeps this from being a GA library, is the community feedback, stress testing, and collateral. In all honesty, it partly comes down to us feeling comfortable about our customers using this library in production scenarios, and we still need some more stress testing and feed back for that to be the case. With that said, we are targeting early summer (which could even mean next month).

Have you guys had any issues with the library? Any general feedback?

**Comment by jtaubensee** [comment]
One more thing to add:
> It would also be great to understand what we can expect from a 1.0 release in terms of comparable feature parity with the existing SDKs.

This library will be missing management functionality, so there will be no `CreateQueue` type of capabilities. Here is a note in our readme about that: https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library

**Comment by GavinOsborn** [comment]
@jtaubensee thanks for your answer that helps a lot.

In light of your answer, perhaps to phrase the question differently:
Would you currently recommend this library for production workloads?

## Feedback
> Have you guys had any issues with the library? Any general feedback?

It's hard for me to provide much feedback at present as I'm only just exploring this new library and haven't used it in anger.

My $0.02 impression so far

### Depth
It feels a bit lite at the moment. I draw this opinion from classes like `Message` which doesn't have any of the utility methods for assigning a payload. I can only do so via a `byte[]`. WindowsAzure.ServiceBus allowed me to compose my Message with a [Stream, byte[] or object](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage?view=azureservicebus-4.0.0). This also applies to deserialization options like `GetBody<T>()` that are missing.

I'm certainly not saying we need the `DataContractSerializer` but perhaps some alternative serialization/deserialization helpers would be nice.

### BrokeredMessage => Message
I'd be curious to know the motivation for renaming `BrokeredMessage` => `Message`.
What I liked about `BrokeredMessage` was that it was quite unique and so didn't blur/conflict with other concepts within my own codebase or with other libraries that I was consuming.

I was also a big fan of the `MessageSender`/`MessageReceiver` abstraction in `WindowsAzure.ServiceBus`. They were missing when I played with it but I see you've made them available now in your 0.0.5 release, nice!

Beyond that I don't have much yet without exploring further :-)

**Comment by SeanFeldman** [comment]
Good feedback @GavinOsborn. Some links you might want to get more context about certain developments.

>  I can only do so via a byte[]

#98 Change Message.Body type to byte[]

> `BrokeredMessage` => `Message`

#108 (Brokered)Message refactoring

On this one I have to admit that looking at it now, `BrokeredMessage` does feel more "familiar" after all the time working with it. But it's just me.

**Comment by GavinOsborn** [comment]
@SeanFeldman the commentary in #98 about `Stream` support makes perfect sense - sounds like a wise decision. However support for some default object serialization doesn't seem like such a bad thing.

The truth is there are still plenty of devs out there that are uncomfortable dealing with either `Stream` or `byte[]`. Microsoft have always gone the extra mile in looking after them.

Regarding the decision to rename I still haven't found any mention of the original rationale for the change. As such I still lean quite firmly in the `BrokeredMessage` camp. I feel `Message`, while perfectly valid in the context of this project, is too generic when bringing into consuming code bases where Message can have many meanings.

This quote from #108 is a great illustration of my own thoughts:

> @SeanFeldman - I don't think we are going back to BrokeredMessage, I just used the alias to make it clear what the AMQP converter was doing. I can just as easily use an alias like "SBMessage" in that class too.

**Comment by jtaubensee** [comment]
> However support for some default object serialization doesn't seem like such a bad thing

Our team is actually planning to have a plugin that would handle these types of interop scenarios, and this is something that we currently have open issues on (#114). So, it might be an extra step or two for true interop, but we will try to make this as easy as possible.

> BrokeredMessage rename to Message

Part of the reason for changing the name of `BrokeredMessage` to `Message` is to simplify things within our service. Many customers we talk with don't grasp what 'broker' means in this sense. This is regularly shown when people ask what a "brokered connection" is, so we have opted to get rid of this name, and wanted to keep it from showing up in the new library.

Please keep in mind, that this new library isnt meant to a 1:1 continuation of concepts from the previous library; if that were the case, we could have easily added .NET Standard support to the older library.
