### ISSUE TITLE
On prem Servicebus

### ISSUE THREAD

**Issue by ambidexterous** [Azure/azure-service-bus-dotnet#167]
## Actual Behavior
1. I downloaded the code and tried try to run the tests but am getting this:
Message: System.TypeInitializationException : The type initializer for 'Microsoft.Azure.ServiceBus.UnitTests.TestUtility' threw an exception.
---- System.ArgumentException : Illegal connection string parameter name 'StsEndpoint'
Parameter name: connectionString

I'm using on premise service bus version.
This is the connection string I use:

Endpoint=sb://hostname.corp.domain.com/ServiceBusEapQANamespace;StsEndpoint=https://hostname.corp.domain.com:9355/ServiceBusEapQANamespace;RuntimePort=9354;ManagementPort=9355;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=bKnerepD9LBGHIVAM4nXJTw5kAAP5updfQYhH2gFG/o=

This same connection string works fine with other tools e.g. Service Bus Explorer 

If I remove couple of the "unsupported" parameters and simplify my conn string to this: Endpoint=sb://hostname.corp.domain.com/ServiceBusEapQANamespace;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=bKnexepD9LBPQIVaM4nXJTw5kAAP5udpxdYhH2gFG/o=

I get this error: Message: Microsoft.Azure.ServiceBus.MessagingEntityNotFoundException : None of the server sasl-mechanisms ([PLAIN,EXTERNAL]) are supported by the client (MSSBCBS).

## Expected Behavior
1. Tests pass

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by jtaubensee** [comment]
@ambidexterous - While in theory this new client might work with the on-prem version of Service Bus, support for that is not currently in scope. And due to the support timeline for on-prem, we aren't actually recommending that customers begin developing new projects for on-prem. In case you are curious about our road map, @clemensv had a good blog post to sum things up: https://azure.microsoft.com/en-us/blog/collaboration-and-federation-azure-service-bus-messaging-on-premises-futures/

**Comment by ambidexterous** [comment]
Thank you for answering. 

I see. In our case we are not starting a new project we actually have a plan to migrate off of the on Prem service bus later this year, however interim we're working to get all the apps updated to .NET core including this piece.

If I was to try to get it work with on prem I have to use some special style of connection string (without the extra attributes) and expose my service bus instance on a specific port etc.?

**Comment by jtaubensee** [comment]
@ambidexterous - Unfortunately this new client only supports SAS authentication, which is not available for on-prem service bus.
