### ISSUE TITLE
APIApprover: Missing public members

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#169]
The file [here](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/test/Microsoft.Azure.ServiceBus.UnitTests/API/ApiApprovals.ApproveAzureServiceBus.approved.txt), seems to only have public interfaces and classes listed and not the members inside of those. @seanfeldman seems to think there is a setting that needs to be flipped.

**Comment by SeanFeldman** [comment]
This is an [issue with ApiApprover](https://github.com/JakeGinnivan/ApiApprover/issues/32). #170 will solve it for now.
