### ISSUE TITLE
Wrap TimeoutException in ServiceBusTimeoutException with IsTransient as true

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#173]
[Documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-exceptions) on `TimeoutException` says:

> Retry might help in some cases; add retry logic to code.

This is a challenge today because `TimeoutException` is [not derived from the `ServiceBusException`](https://github.com/Azure/azure-service-bus-dotnet/blob/784fc14cf348c472b5a25eb5aa8e2afc8b43a56d/src/Microsoft.Azure.ServiceBus/Amqp/AmqpExceptionHelper.cs#L97) which exposes `IsTransient`. The translation is using 

Should the client throw a custom (specific to this library) timeout exception derived from `MessagingException`? 

To provide more context, with the WinsowsAzure.ServiceBus client there are a few issues when handling exceptions with `OnMessageOptions.ExceptionReceived` and trying to determine if a timeout exception is transient or not (issue https://github.com/Azure/azure-service-bus/issues/28 and https://github.com/Azure/azure-service-bus/issues/27).

**Comment by binzywu** [comment]
Generally speak, all exceptions from a cloud service could be considered as transient unless the cloud service is completely down and no one wants to bring it up. :)

@SeanFeldman what operations you have seen that throws ` TimeoutException` ?

**Comment by SeanFeldman** [comment]
OnMessage API would throw in when a lock is failing renewal (at least I've seen this with the old/current/WindowsAzure.ServiceBus client. 
In this code base, `System.TimeoutException` is thrown when it's a [timeout error](https://github.com/Azure/azure-service-bus-dotnet/blob/784fc14cf348c472b5a25eb5aa8e2afc8b43a56d/src/Microsoft.Azure.ServiceBus/Amqp/AmqpExceptionHelper.cs#L97)

**Comment by nemakam** [comment]
@SeanFeldman Given that is a distributed system in the backend, there can be timeout at any stage when transferring messages across machines. But for a SB user, any kind of `TimeoutException` is a retry-able exception.
Are you suggesting that there are `TimeoutException`s which doesn't work with retry?

**Comment by SeanFeldman** [comment]
@nemakam not quite. What I'm saying is that exception handling becomes more complicated than it should be when `System.TimeoutException` is used since it doesn't have the `.IsTransient` attribute. It forces implementation that differentiates between transient and non-transient exception, where for non-transient exception `TimeoutException` is an outlier 😃 

It could be simplified if `TimeoutException` would be derived from the `ServiceBusException` and then the need to look into specific non-transient exception would be eliminated.

**Comment by nemakam** [comment]
Oh If I read you right, you are suggesting **every** `TimeoutException` be thrown as `ServiceBusTimeoutException` with `IsTransient` as true?

**Comment by SeanFeldman** [comment]
Precisely.

**Comment by nemakam** [comment]
Sure. This seems to be a relatively simple change, but might require some testing. I've added the  help-wanted tag for this issue.
Feel free to pick it up
