### ISSUE TITLE
Keep alive setting for AMQP connection

### ISSUE THREAD

**Issue by bmmathe** [Azure/azure-service-bus-dotnet#181]
Is there anyway to keep the AMQP client alive in QueueClient or SubscriptionClient?
We have an endpoint on a web service that isn't hit too frequently during the day which causes the SubscriptionClient to timeout in between calls.  When this happens the SubscriptionClient has to re-establish the connection to Azure Service Bus which is taking a relatively long time.  We can't send the message in a thread outside of the request because we only want to commit a transaction if the message makes it to the SB.

**Comment by binzywu** [comment]
how often to you make a call? Would HTTP work better for your scenario?

**Comment by bmmathe** [comment]
We only post to specific tops when a transaction takes place so it could be several minutes.  The HTTP client is just as slow (~1 second).  Referencing the Azure Service Bus Documentation: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements it seems like the full framework library maintains the open connection via a connection factory.  It doesn't seem like the dotnet core library has this same concept as the connection seems to timeout and has to re-establish.  We ran some tests and as long as we are sending messages every few seconds the timings are less than 20ms after the first message is sent.  In our scenario though, only sending a message every few minutes, every message takes at least 1 second to send which sets our baseline performance for our endpoints that need to send messages to the bus at 1 second.

**Comment by binzywu** [comment]
sorry to get back later. It might be good if you could share some repro code to us. The sender only gets idle after 10 minutes to activity. So if the messages are sent every few minutes, the connection should be alive unless network issues.

**Comment by WilliamHBonney** [comment]
@binzywu Sorry to post on someone elses thread, but i am investigating an issue where i set MaxAutoRenewDuration to 20 minutes, with a 2 minute lock duration, AutoComplete = false.  If my receiver has a sleep for 9:00 and i then call CompleteAsync(lock token) it works. If my receiver has a sleep for 11:00 and i call CompleteAsync(lock token) i get a lockLost exception ... someone else has the lock blah blah blah - but they don't! i had a block on it for the full 11 minutes (the clientid is the same after 11 minutes but something has changed).
