### ISSUE TITLE
MessageReceiver.ReceiveAsync(serverWaitTime) doesn't accept value less than a second

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#189]
Connect to #183 (see [comment](https://github.com/Azure/azure-service-bus-dotnet/pull/183#discussion_r122316536))

The fix for #154 and #177 reduced `serverWaitTime` from 1 minute to 1 seconds.
Attempts to reduce it to less than a second or setting to `TimeSpan.Zero` resulted in tests failure.
Can `MessageReceiver.ReceiveAsync(serverWaitTime)` accept values less than 1 second?

**Comment by nemakam** [comment]
@SeanFeldman Typo in the heading? 
"value less than a second"

**Comment by vinaysurya** [comment]
Pull Request #199 should resolve this issue
