### ISSUE TITLE
Running tests on PRs w/o jeopardizing security

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#190]
Currently PRs from external contributors are not running tests on build server (AppVeyor).

This creates a few problem of
- Contributors not being aware if they break anything by their changes
- ASB team members required to run those tests locally/manually

It would be ideal to find out a way to to execute tests on PRs as well.

/cc @nemakam

**Comment by SeanFeldman** [comment]
One of the discussed options is when a build is executed, it create a resource group `sb-dotnet-av-$buildVersion-rg` which is removed when the build is done. This means PRs would be creating their own RGs and removing those when the build is done. 

Problem with this approach is that it makes secrets `azure-service-bus-dotnet/ClientSecret` and `azure-service-bus-dotnet/CodeCovSecret` vulnerable 😞

**Comment by SimonCropp** [comment]
only build PRs that have had a review form someone in the team

 * configure appveyor to not build any public PR branches. 
 * Build small bot
 * bot detects a PR "approval" either by interrogating the approval state of a PR https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request or by using a custom label.
 * note the bot run periodical or respond to webhooks like https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent https://developer.github.com/v3/activity/events/types/#pullrequestevent
 * ping appveyor to start a build for that specific branch https://www.appveyor.com/docs/api/projects-builds/#start-build-of-specific-branch-commit

**Comment by nemakam** [comment]
I tried a different approach. Let me know if you find any issues with it.

* Blocked appveyor from being configured from `appveyor.xml`. Instead, moved everything to UI based approach where I have given the `build.ps1` inline as the build script.
* The script reads the environment variables into local variables, and then before invoking MsBuild, go and update environment variables with garbage value.
* Use the locally read variables to take care of test bed setup

**Comment by nemakam** [comment]
Looks like this works for now.
