### ISSUE TITLE
Suggestion: provide a GH group to ping for reviews to remove dependency on individuals

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#194]
When a community PR is raised, there's no public group to be pinged to indicate PR is ready for a review. Would be great if such a group would be created and documented in [`readme.md`](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/README.md)

**Comment by binzywu** [comment]
@SeanFeldman Could you please try to use this github team? @Azure/azure-service-bus-write 

Or do you mean a different way?

**Comment by SeanFeldman** [comment]
Thank you @binzywu.

Would it be worth mentioning @Azure/azure-service-bus-write in readme.md? It's not showing up in auto-complete and not very intuitive (azure-service-bus-write for reviewers 😃).

**Comment by SeanFeldman** [comment]
Also, `@Azure/azure-service-bus-write` seems to be hidden? When you use it, it's represented as a GH team. When I do that, it's not.

**Comment by nemakam** [comment]
Resolved using #215
