### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by Hantse** [Azure/azure-service-bus-dotnet#195]
Hello,

I try to use Topic with this version of library, with full framework i can use topic send/receive, on this version, i can send, but when i try do add RegisterMessageHandler, i receive this exception :
`The messaging entity 'myservicebus:topic:topicsample~15|microsoft%20azure%20sponsorship' could not be found. TrackingId:xxxxxxxxxx, SystemTracker:myservicebus:topic:topicsample~15|microsoft%20azure%20sponsorship, Timestamp:6/21/2017 1:15:19 PM TrackingId:xxxxxxxx, SystemTracker:gateway6, Timestamp:6/21/2017 1:15:18 PM`

The topic, is not implemented ?

Thank's

**Comment by nemakam** [comment]
@Hantse, Sending to and receiving from topic is implemented and have several tests for this.
Are you using `SubscriptionClient` to receive or `MessageReceiver`?
Could you provide a sample code that could repro this?

**Comment by Hantse** [comment]
Hello,

The receive code :
`class Program
    {
        private const string ServiceBusConnectionString = "mykey";
        private const string TopicName = "topicsample";
        private const string SubscriptionName = "Microsoft Azure Sponsorship";
        private static MessageReceiver msc;
        private static SubscriptionClient sc;

        public static void Main(string[] args)
        {
            try
            {
                sc = new SubscriptionClient(ServiceBusConnectionString, TopicName, SubscriptionName);
                msc = new MessageReceiver(ServiceBusConnectionString, TopicName);

                MainAsync().GetAwaiter().GetResult();
            }
            catch (Exception exception)
            {
                Console.WriteLine($"{DateTime.Now} > Exception: {exception.Message}");
            }
        }

        private static async Task MainAsync()
        {
            Console.WriteLine("Press ctrl-c to stop receiving messages.");
            ReceiveMessages();
            Console.ReadKey();
        }

        // Receives messages from the queue in a loop
        private static void ReceiveMessages()
        {
            try
            {
                msc.RegisterMessageHandler(async (a, b) =>
                {
                    await Task.Run(() => Console.WriteLine("Message Receive"));
                });

                sc.RegisterMessageHandler(async (a, b) =>
                {
                    await Task.Run(() => Console.WriteLine("Message Receive"));
                });

            }
            catch (Exception exception)
            {
                Console.WriteLine($"{DateTime.Now} > Exception: {exception.Message}");
            }
        }
    }`

Same exception with SubscriptionClient or MessageReceiver.

**Comment by vinaysurya** [comment]
It is likely not running because MessageReceiver is being created with a topicName. MessageReceiver should always be created with a subscription Name.

Replacing:
msc = new MessageReceiver(ServiceBusConnectionString, TopicName);
with
msc = new MessageReceiver(ServiceBusConnectionString, EntityNameHelper.FormatSubscriptionPath(TopicName, SubscriptionName));

should fix the problem for you.

**Comment by Hantse** [comment]
Hi,

Thank's, but same exception :
The messaging entity 'afeliosample:topic:topicsample~15|microsoft%20azure%20sponsorship' could not be found.

**Comment by SeanFeldman** [comment]
> private const string SubscriptionName = "Microsoft Azure Sponsorship";
Looks off. When you create your subscription client, that should be subscription **name** as in ASB subscription, not Azure subscription.

**Comment by binzywu** [comment]
@SeanFeldman got the point. 

Actually I just checked in service, the topic "AFELIOSAMPLE:TOPIC:TOPICSAMPLE " does not have any subscriptions under it. As suggested by @nemakam, you could use service bus explorer to check.

Furthermore, I don't think space (' ' or %20 as url encoded value) is ever supported as subscription name.

**Comment by Hantse** [comment]
Ok, i try and that's work.

Thank's for your help.

**Comment by SeanFeldman** [comment]
Can propose to label this as `question` to filter from issues that are not questions? Thank you.
