### ISSUE TITLE
ServiceBusNamespaceConnection hardcodes amqps as URI scheme for endpoint

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#197]
When `ServiceBusNamespaceConnection` is constructed with a connection string, it leverages `ServiceBusConnectionStringBuilder` to parse all parts. Except URI scheme. That one is [hard-coded](https://github.com/Azure/azure-service-bus-dotnet/blob/3d9c42b47fbba3132d63c04b3cdab79d419240bd/src/Microsoft.Azure.ServiceBus/ServiceBusConnectionStringBuilder.cs#L97) to `amqps`. Since endpoint information will be surfaced when exceptions are happening, endpoint information should match what users provide as their connection string.

See [discussion here](https://github.com/Azure/azure-service-bus-dotnet/pull/193#issuecomment-310797652) for details.

~~Test to change: https://github.com/Azure/azure-service-bus-dotnet/pull/193/files#diff-79c587cd7db2ab49c0272c47fab9a244R17~~
`ServiceBusConnectionStringBuilder` needs to be tested.

**Comment by nemakam** [comment]
Thanks @SeanFeldman  for opening this...

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Azure/azure-service-bus-dotnet/commit/d9ac7decf341c09d1bf5dda280ea515ccd82c6a1 😉
