### ISSUE TITLE
QueueClient does not expose Renew and Receive

### ISSUE THREAD

**Issue by smiggleworth** [Azure/azure-service-bus-dotnet#208]
## Actual Behavior
1. QueueClient does not expose Renew and Receive methods

## Expected Behavior
1. QueueClient would expose Renew and Receive methods

## Versions  
All

**Comment by SeanFeldman** [comment]
`QueueClient` now exposed [`RegisterMessageHandler`](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/QueueClient.cs) only. Agree, for simpler use cases it's a bit too much if you just need to get a single message. For that, there's [`MessageReceiver`](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs#L281)/[`MessageSender`]( https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Core/MessageSender.cs#L177) that can do exactly what you need.

**Comment by smiggleworth** [comment]
Is there a plan to expose these methods?  Would you be open to a pull request?

**Comment by SeanFeldman** [comment]
Don't see why team would not be willing to discuss this option, right @Azure/azure-service-bus-write?

Sender and receiver are internal and simpler  receives/ sends could be delegated.

**Comment by binzywu** [comment]
@SeanFeldman sender and receiver are public classes.

**Comment by SeanFeldman** [comment]
@binzywu I meant "senders and receivers used by queue client"

**Comment by binzywu** [comment]
@smiggleworth There is no plan to expose these on clients (QueueClient and SubscriptionClient) currently. As renew is done in the background and receiving is done by on message handler as Sean pointed out earlier. Client is built to support basic scenarios. If you want to have more control, then using MessageSender and MessageReceiver directly will be better option.

**Comment by SeanFeldman** [comment]
@binzywu given the label, should it be closed? Thanks 🙂
