### ISSUE TITLE
Exception: A message handler has already been registered.

### ISSUE THREAD

**Issue by flockoftanks** [Azure/azure-service-bus-dotnet#209]
## Actual Behavior

The client successfully registers and waits for messages to become available in the queue, but once it starts receiving messages, it seems to be attempting to re-register the handler and I get infinite exceptions until it receives the next message, then continues to display the same exception message indefinitely.  
```
try
{
    // Receive the next message from the queue
    queueClient.RegisterMessageHandler(
        async (message, TokenProvider) =>
        {
            Console.WriteLine($"Received message: SequenceNumber:{ message.SystemProperties.SequenceNumber } Body: { Encoding.UTF8.GetString(message.Body) }");

            // Complete the message so that it is not received again.
            // This can only be done only if the queueClient is opened in ReceiveMode.PeekLock mode.
            await queueClient.CompleteAsync(message.SystemProperties.LockToken);
        },
        new MessageHandlerOptions() { MaxConcurrentCalls = 1, AutoComplete = false});
}
catch (Exception exception)
{
    Console.WriteLine($"{DateTime.Now} > Exception: {exception.Message}");
}
```
> dotnet run
> Press ctrl-c to exit receive loop.
> Received message: SequenceNumber:47569271064100874 Body: Message 0
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> 7/5/17 3:32:51 PM > Exception: A message handler has already been registered.
> ..... to infinity

## Expected Behavior
1. I only expect my console to display the messages that are received, not throw exceptions trying to re-register the message handler.

## Versions  
- OS platform and version: Ubuntu 17.04
- .NET Version: netcoreapp2.0
- NuGet package version or commit ID: 0.0.6-preview

**Comment by SeanFeldman** [comment]
@flockoftanks could you provide a gist to how this block is hosted (where that try-catch is found)?

**Comment by flockoftanks** [comment]
Oh man, I apologize.  Somehow a while loop ended up in there.  Think I pasted some bad code.  It kept re registering it and I completely missed it when I looked.  Sorry to waste everyone's time!  But thanks for getting back to me.
