### ISSUE TITLE
Release was not made from the master branch

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#222]
So far releases were made from `master` except the last release `0.0.7-preview`.
Shouldn't `master` branch represent what's been released?

![image](https://user-images.githubusercontent.com/1309622/28201365-f15c93ae-682d-11e7-8d5d-a3e34be25f10.png)

**Comment by vinaysurya** [comment]
Thanks for bringing this to our attention @SeanFeldman, Yes, we should have ideally made it from the master. But at this point since nothing has changed from master and dev, I've initiated a merge from dev to master. I'll also check if we need to make any other changes to release notes etc

**Comment by SeanFeldman** [comment]
No worries. At some point in time we should automate this process and look into gitflow to simplify the process. Raised #224 to track it.

**Comment by vinaysurya** [comment]
Dev is now merged into master. It did not look like there were any other updates necessary to release notes etc. Should be good to close the issue @SeanFeldman ?

**Comment by SeanFeldman** [comment]
Thank you @vinaysurya
