### ISSUE TITLE
Getting Error with MessageHandlerOptions - Issue with 0.0.7-preview?

### ISSUE THREAD

**Issue by drewid** [Azure/azure-service-bus-dotnet#229]
The sample project builds, but when trying to replicate the sample code to "Receive" messages from a queue I am getting the following error:

```
"Code: CS7036	
There is no argument given that corresponds to the required formal parameter 'exceptionReceivedHandler' of 'MessageHandlerOptions.MessageHandlerOptions(Func<ExceptionReceivedEventArgs, Task>)'	
```

I am using Windows 10, Visual Studio 2017 Preview and the code in use is pretty much identical.

**The only significant differences are:**

1) Sample project is using .Net Core 1.0 and I am using .Net Core 1.1 (sample works when I choose 1.1)
2) Sample project is using 0.0.5-preview and I am using the latest 0.0.7-preview
3) I am doing a web api project and not a console project - should not matter.

Any ideas on how to help troubleshoot this?  If something basic like getting messages doesn't work then I am obviously dead in the water.

Thanks!

**Comment by drewid** [comment]
After doing the obvious and changing the NuGet package being used to 0.0.5-preview, I can confirm there is an issue between 0.0.5-preview and 0.0.7-preview.  

The sample project works with 0.0.5-preview but **NOT** with 0.0.7-preview.  Not sure exactly what changed but help with figuring that out would be greatly appreciated.

**Comment by SeanFeldman** [comment]
@drewid you're correct that there was a change in the `RegisterMessageHandler` API and the sample should have been updated (I'll raise a PR). Saying that, compiler error says exactly what needs to be done 😉 

```
CS7036	There is no argument given that corresponds to the required formal parameter 'exceptionReceivedHandler' of 'MessageHandlerOptions.MessageHandlerOptions(Func<ExceptionReceivedEventArgs, Task>)'	ReceiveSample	C:\github\SeanFeldman\azure-service-bus\samples\DotNet\Microsoft.Azure.ServiceBus\ReceiveSample\Program.cs
```
I.e. You need to provide a func/callback into the `MessageHandlerOptions`.

**Comment by SeanFeldman** [comment]
@Azure/azure-service-bus-write: messages sent with `0.0.5-preview` are incompatible with `0.0.7-preview`. The sample should probably note that there's not wire compatibility on messages sent with different preview versions.

**Comment by SeanFeldman** [comment]
@drewid see PR under the right repo: https://github.com/Azure/azure-service-bus/pull/51

**Comment by drewid** [comment]
@SeanFeldman - having a brain cramp still trying to figure out what is being asked for in 0.0.7.

**Comment by SeanFeldman** [comment]
You need to provide a func/callback for the `MessageHandlerOptions` constructor. See PR for details.
