### ISSUE TITLE
Suggestion: add events for diagnostics

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-service-bus-dotnet#231]
I have a pretty straight forward console app that registers a session handler, and persists every message to a database. This is running in a Docker container on an Ubuntu VM in Azure.

My problem is that after a few days of inactivity (i.e. no messages on the queue) the console app seems to loose connection or something, because it stops handling messages. Now, I don't know where the problem might be - in this library? Problem with docker? Problem with the Azure network? So what would be really helpful is some way of diagnosing the QueueClient. Like an `OnMessagePumpTriggered` event or something, so that I can log every time it tries to fetch messages, and see if it suddenly stops or something. I'm not sure how this client is built, but if you have some kind of persistent connection in there, maybe an event that gets fired when that connection is lost or something?

**Comment by vinaysurya** [comment]
John,
 When you register for SessionHandler using say the Register method below, the 'exceptionReceivedHandler' can be used to register for any exceptions seen in the session pump. Are you already subscribed to this and if so do you not see any exceptions from this handler?
RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, Func<ExceptionReceivedEventArgs, Task> exceptionReceivedHandler)

**Comment by johnknoop** [comment]
Cool. Didn't know about that one (needed the latest version of the package).

I actually get an exception _every time_: "The session lock has expired on the MessageSession. Accept a new MessageSession." 

Even if I publish a session with a completely new, unused session id. Any idea what that might be? Feels like a false negative, since the message gets consumed and removed from the queue.

**Comment by vinaysurya** [comment]
But at this time, do you know if your session handler callback (1st argument) from below, actually get the session and process it? Or it did not get any sessions at all during this time?

RegisterSessionHandler(Func<IMessageSession, Message, CancellationToken, Task> handler, Func<ExceptionReceivedEventArgs, Task> exceptionReceivedHandler)

**Comment by johnknoop** [comment]
No, everything gets processed. I have two processes running in different console windows. One sending and one receiving. And everything works as expected, so it's strange that I get the exception callback.

**Comment by johnknoop** [comment]
Found the reason: apparently, the default value for AutoComplete is true, and since I do my own `session.CompleteAsync(message)`, the message is already completed when the "autocompletion" wants to do it's thing. Turning that setting to false resolved the issue.

Ok, great, now I'm going to deploy this code onto my Azure vm and see if anything suspicious gets written to the log in a few days.
