### ISSUE TITLE
How to delete and get the statistics of the queue implementation of the service bus

### ISSUE THREAD

**Issue by barkhashah** [Azure/azure-service-bus-dotnet#243]
Hi Azure-service-bus-dotnet team,

I have few questions regarding the new implemenation for the azureservicebusdotnet. In the previous old client ( Microsoft.ServiceBus ), we used to have NameSpaceManager which has these APIs ( QueueExistsAsync, DeleteQueueAsync, GetQueueAsync ) and some classes like QueueDescription, TopicDescritpion for Topic that are missing in the newer implementation ( Microsoft.Azure.ServiceBus ).
Can someone please tell me how can we manage the service bus resources in the lastest release? How can i delete the queue or query the queue?

Would appreciate your response.

thanks
barkha shah

**Comment by vinaysurya** [comment]
@barkhashah, all operations you are mentioning all fall into management operations.. At this point in time we do not plan to support management operations in this library and it is only meant for runtime operations.  All management operations will be using the Microsoft.Azure.Management.ServiceBus library.

https://github.com/Azure/azure-service-bus-dotnet/blob/a171b6cf8c5f99e534099de87260663fee3e195b/README.md#can-i-manage-service-bus-entities-with-this-library

**Comment by barkhashah** [comment]
The sample application for management library is still using older preview version of servicebus lilbrary (0.0.1 )and it was very confusing because It took me some time to figure out that TopicCreateOrUpdateParameters is gone and instead we use SBTopic. Kindly update your samples also as and when new preview versions of libraries are released.

**Comment by vinaysurya** [comment]
Like I mentioned on the other thread, w.r.t samples, we are updating the samples to use the latest version. Expect an update on this next week. Until then please use this Pull request to see the updated sample.
Azure-Samples/service-bus-dotnet-management#6

**Comment by vinaysurya** [comment]
@barkhashah, the samples repo for Azure-Samples/service-bus-dotnet-management is now updated.
