### ISSUE TITLE
Cannot add rule to topic subscription 

### ISSUE THREAD

**Issue by dmitry606** [Azure/azure-service-bus-dotnet#246]
AddRuleAsync call always throws - "The service was unable to process the request; please retry the operation.". At the same time, it is possible to add rules to the same subscription using Service Bus Explorer.

     static void Main(string[] args)
    {
        var subscriptionClient = new SubscriptionClient(
            nsConnString,
            topicName,
            subsName,
            ReceiveMode.ReceiveAndDelete);

        subscriptionClient.AddRuleAsync(new RuleDescription
        {
            Filter = new CorrelationFilter { Label = Guid.NewGuid().ToString() },
            Name = Guid.NewGuid().ToString()
        }).Wait();

        Console.WriteLine("Success");
        Console.ReadKey();

    }

## Versions  
- OS platform and version: Win10
- .NET Version: 2.0.0-preview2
- NuGet package version or commit ID: 0.0.7-preview (and earlier)

**Comment by SeanFeldman** [comment]
Quoting from [readme.md](https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library):

> The standard way to manage Azure resources is by using Azure Resource Manager. In order to use functionality that previously existed in the .NET Framework Service Bus client library, you will need to use the Microsoft.Azure.Management.ServiceBus library.

Considering that management operations would not be performed by this library, is it right to have this API in this client library?

**Comment by nemakam** [comment]
@dmitry606 , error which adding rule is a known bug and is fixed in master branch. Refer #227 .
We would be releasing the next nuget package with these fixes very soon.

**Comment by SeanFeldman** [comment]
@nemakam could you please address my [question](https://github.com/Azure/azure-service-bus-dotnet/issues/246#issuecomment-320037841) as well? Thank you.

**Comment by nemakam** [comment]
Rules are considered runtime operations and are used more heavily. Customers create and delete rules in the same transaction consisting of sends and receives. That is why we have rule operations in this library. Let me know if it answers your question. I'll mark this issue closed.

**Comment by SeanFeldman** [comment]
Thank you @nemakam. My confusion was coming from the fact that rules are also entities.
👍 to close.
