### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by dmitry606** [Azure/azure-service-bus-dotnet#247]
The library is unusable on .NET Core 2.0. I already posted one issue https://github.com/Azure/azure-service-bus-dotnet/issues/246, but even without that, I now get every second message lost. When do you plan to add support for .NET Core 2.0?

**Comment by SeanFeldman** [comment]
The library support .NET Standard 1.3, so shouldn't be an issue running under .NET Core 2.0.
@dmitry606 out of curiosity, aside from #246 could you provide a repro for message lost error? Thank you.

**Comment by dmitry606** [comment]
It was me, I just had 2 receivers on the same subscription.. :)
