### ISSUE TITLE
GitHub link for the latest Microsoft.Azure.Management.ServiceBus

### ISSUE THREAD

**Issue by barkhashah** [Azure/azure-service-bus-dotnet#252]
Hi 
I am looking for the source code for the Microsoft.Azure.Management.ServiceBus ( 1.0.0) june 30th in the GitHub but not able to find it. The documentation is still pointing to the old source code which is the preview version. ( https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ResourceManagement/ServiceBus) .

Can anyone please help me out? The new release does not seem to have TopicCreateOrUpdateParameters and all the samples provided in this page is pointing to the old release.
thanks
barkha shah

**Comment by vinaysurya** [comment]
Barkha,

We are in the process of pushing an update to the https://github.com/Azure-Samples/service-bus-dotnet-management samples page, that will let you use the new SBTopic etc to create and manage topics/subscriptions/rules.. 

If you see this pull requests, it addresses your question already. We are working to publish the update soon. Until then please have a look at here to see how it can be managed.
https://github.com/Azure-Samples/service-bus-dotnet-management/pull/6

**Comment by barkhashah** [comment]
Thanks vinaysurya . Will keep an eye on it . Alternatively please let me know on this link too :)

**Comment by barkhashah** [comment]
@vinaysurya Actually I need the source code for the management library 1.0.0 itself more than the sample code. https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ResourceManagement/ServiceBus is pointing to the old Code !!!
This should be there somewhere , right?

**Comment by vinaysurya** [comment]
@barkhashah, looks like this is the link for the latest ServiceBus Management library.. If you see the version on the csproj there it indicates the version as 1.0.0 which is the current version.

https://github.com/Azure/azure-sdk-for-net/tree/3b013cd9b9aac9407f3d9bea221922d037c1596a/src/SDKs/ServiceBus/Management.ServiceBus
