### ISSUE TITLE
SubscriptionDescription vs SBSubscription - missing parameters

### ISSUE THREAD

**Issue by barkhashah** [Azure/azure-service-bus-dotnet#255]
EnableDeadLetteringOnFilterEvaluationExceptions, ForwardTo, ForwardDeadLetteredMessagesTo and UserMetadata are no longer part of SBSubscription. They used to be in SubscriptionDescription in the old library.

Are they not relevant anymore or they are being used else where?

**Comment by SeanFeldman** [comment]
Being part of management operations, `SubscriptionDescription` I'd needed when entities are managed. See management library for alternative 😉

**Comment by vinaysurya** [comment]
@barkhashah, Forwardto and ForwardDeadLetteredMessagesTo were not supported with ARM until recently. We recently added supported for this feature through ARM. The way this works is once the swagger template is exposed for these new features, the next revision of management library  will automatically include them in the Subsequent release. Expect the ForwardTo and ForwardDeadLetteredMessagesTo to be available in the next release of the management library (probably a month from now). 

Regarding the EnableDeadLetteringOnFilterEvaluationExceptions, that might just have been missed. I'll check if this can be added back to the swagger. Thanks!

**Comment by vinaysurya** [comment]
@barkhashah, looks like EnableDeadLetteringOnFilterEvaluationExceptions got left out. We have created a bug to expose this as well and will check other properties too. But they should all become available with the next refresh of the mgmt library.

**Comment by SeanFeldman** [comment]
> We have created a bug

Link?

**Comment by binzywu** [comment]
@SeanFeldman unfortunately it is internal. I need to find a way to link the internal vsts with github issues.

**Comment by niemyjski** [comment]
Thanks for the update. For now, we'll just exclude these from our fork (https://github.com/FoundatioFx/Foundatio.AzureServiceBus/pull/1) cc @barkhashah

**Comment by alexeyzimarev** [comment]
`SBSubscription` still has `ForwardTo` property missing in the latest version as per today.

**Comment by nemakam** [comment]
You could follow the updates at https://github.com/Azure/azure-service-bus/issues/88

**Comment by alexeyzimarev** [comment]
@nemakam what is this issue has to do with the issue you have referenced? These are two different things. This one: https://github.com/Azure/azure-sdk-for-net/issues/3599 is much more relevant.

**Comment by alexeyzimarev** [comment]
> Expect the ForwardTo and ForwardDeadLetteredMessagesTo to be available in the next release of the management library (probably a month from now).

It is November and the new SDK library still does not have it.
