### ISSUE TITLE
Plans for the "old" WindowsAzure.ServiceBus library

### ISSUE THREAD

**Issue by Aleksanderis** [Azure/azure-service-bus-dotnet#257]
I didn't find any exact topic mentioning it, but what are the plans for the "old" WindowsAzure.ServiceBus library (https://www.nuget.org/packages/WindowsAzure.ServiceBus)? I see it's still being quite actively maintained (last update was on July 22, 2017).
However what I read about the new library in this repository - I got an impression that old library was quite "old-fashioned" and didn't match current Azure philosophy (like ServiceBus management or too-heavy BrokeredMessages), so that it wasn't worth just to migrate it to .NET Core as it was.

So, will it be supported and maintained, or new library plans to replace it fully after final release?
I'm asking, because we are planning to migrate our .NET Framework app to .NET Core. We cannot do it straight away because some other dependencies, but we are considering to migrate at least ServiceBus usage to reduce dependencies with "classic" services/libraries.

**Comment by vinaysurya** [comment]
WindowsAzure.ServiceBus will be supported and maintained and there are no current plans to completely replace it.

**Comment by Aleksanderis** [comment]
Ok, thanks for the response! Just one more clarification.;)
It will be supported and maintained, but not ported to .NET Core/.NET standard? I.e. the only option for .NET Core is to use the "new" library?

**Comment by vinaysurya** [comment]
Correct!
