### ISSUE TITLE
Issue with AMQP when running on Xamarin.iOS

### ISSUE THREAD

**Issue by mintyfusion** [Azure/azure-service-bus-dotnet#260]
Please refer to the issue here: https://github.com/Azure/azure-amqp/issues/71 which happens when receiving message from Service Bus on Xamarin.iOS

The issue has been fixed by AMQP team and I was wondering if you know when the new package with updated AMQP can be released?

**Comment by vinaysurya** [comment]
@mintyfusion, the current version of ServiceBus is already released with the version of Amqp 2.1.0 that carries the fix you mention. Can you please try with the latest version of this library if your scenario works?

**Comment by mintyfusion** [comment]
Yes, it works. The message is correctly received in Xamarin.iOS. Thank you very much.
