### ISSUE TITLE
Get and Set SessionState should take bytes not stream

### ISSUE THREAD

**Issue by binzywu** [Azure/azure-service-bus-dotnet#261]
## Actual Behavior
1. Current API takes Stream

## Expected Behavior
1. Takes bytes instead of stream

This is a breaking change but a necessary for moving to 1.0 GA.

## Versions  
- OS platform and version: N/A
- .NET Version: N/A
- NuGet package version or commit ID: N/A

**Comment by SeanFeldman** [comment]
> This is a breaking change but a necessary for moving to 1.0 GA.

The version is still not GA-ed, so np with the change @binzywu
