### ISSUE TITLE
Support AMQP transport in config-driven WCF applications

### ISSUE THREAD

**Issue by TWolverson** [Azure/azure-service-bus-dotnet#268]
## Actual Behavior
1. There does not seem to be any way to create a WCF client or service using AMQP transport. There is no equivalent AmqpBinding for the NetMessagingBinding, for example. If this is possible, it is not documented anywhere that I can find.
2. 

## Expected Behavior
1. Allow creation of WCF services and clients running AMQP transport, using the usual WCF configuration mechanism
2. 

## Versions  
- OS platform and version: Any
- .NET Version: Any
- NuGet package version or commit ID: N/A

**Comment by binzywu** [comment]
@TWolverson Do you mean our old Full .Net client? The new .net standard client doesn't support WCF.

**Comment by TWolverson** [comment]
@binzywu I suppose so? Is this not the repo corresponding to the Nuget package Microsoft.ServiceBus? There are a couple of different sources that suggest that library has never been fully open-sourced. If this isn't it, which one is?

**Comment by binzywu** [comment]
This is not the repo for our full .net library. This repo is a brand new library that only supports AMQP not netmessaging. The full .net one is never open sourced. And I don't think we ever will. To open issue against that, you can go to this repo https://github.com/Azure/azure-service-bus. Where we take all issues related to old client and services. That repo also contains all the samples.

**Comment by TWolverson** [comment]
@binzywu  OK I'll do that, thanks.
