### ISSUE TITLE
How does one configure this library to use a proxy for HTTP traffic?

### ISSUE THREAD

**Issue by cjpomer** [Azure/azure-service-bus-dotnet#269]
In the full framework this was previously handled in web.config or app.config with a default proxy.  Additionally, there is code that can change the default proxy for the process running.  In netcore that functionality is deprecated or unfinished.

But surely there must be a way to consume this API from behind a proxy?

Sorry if this is the wrong forum (I'm a bit new to github).  And I see that other issues are tagged as questions, which this certainly is, but I can't see how/where to do that.

**Comment by binzywu** [comment]
@cjpomer We have not added the websocket support yet which we will add in near future. But we will. However, to give definitive answer about whether proxy is supported across all platforms, we don't know yet.

**Comment by cjpomer** [comment]
Thanks @binzywu.

I want to e.g. receive messages from a queue or topic on a machine running behind a web proxy.

Can you help me understand how websocket will help?

**Comment by binzywu** [comment]
Our underneath [AMQP library](https://github.com/Azure/azure-amqp) supports WebSocket as transportation which uses the WebSocket implementation in .Net which support proxy. WebSocket uses service bus https endpoint.

**Comment by nemakam** [comment]
@cjpomer Websocket support is merged into our branch. This would be shipped as 1.1.0. Make sure you use TransportType=AmqpWebSockets for your connections which run through a proxy.
