### ISSUE TITLE
UWP Scenarios not working with version 1.0.0 library

### ISSUE THREAD

**Issue by vinaysurya** [Azure/azure-service-bus-dotnet#277]
When attempting Universal Windows Platform Send/Receive application using Microsoft.Azure.ServiceBus library which in turn references Microsoft.Azure.Amqp library version 2.1.0, we get the following error during the first send/receive

System.InvalidOperationException: A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)

The issue has already been fixed in the Azure.Amqp library and a corresponding nuget package is released. Please refer to the following issue for more details on the issue and fix:
https://github.com/Azure/azure-amqp/issues/75

This issue will track the updating of this library version to the newer version of Azure.Amqp library.

**Comment by eliasj** [comment]
Hi, Thank you for the fix. Just what we needed. 

Now I wonder if you know when this fix will be released on NuGet?

**Comment by nemakam** [comment]
@eliasj Unfortunately, we don't have a fixed release date for 1.1.0 yet. We have some more work to do before the release. My best guess for next nuget would be in another 2-3 weeks.

**Comment by antlhuede** [comment]
@nemakam is there a release date for this update coming anytime soon?
Last best guess was for a date several weeks ago. My workaround using this package in UWP is not at all reliable and I don't know if I should spend the time finishing a proper implementation for production or waiting for this package to be released.

Could it be coming with the October 17th Fall Creators Update?

**Comment by nemakam** [comment]
@antlhuede 
Release 2.0 is now out. Please give it a try.

**Comment by runewake2** [comment]
@nemakam The 2.0 release introduces a dependency on .NET Standard 2.0. This requires a minimum version of the Fall Creators Update which makes using this fix very difficult.

**Comment by nemakam** [comment]
@runewake2 
Can you take a look at [2.0 release notes](https://github.com/Azure/azure-service-bus-dotnet/releases/tag/2.0.0) and if you are not particular about any new feature that we released, you could also consider using our 1.0 client with the latest amqp nuget reference in your solution.
