### ISSUE TITLE
Add Source Link support

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#280]
### Why?

To make developers life easier. Allow stepping into ASB client source code when needed w/o wasting time.

### How?

[SourceLink](https://github.com/ctaggart/SourceLink)

### Will it support multiple targets?

Yes

### What will it look like?

I've applied this to [`ServiceBus.AttachmentPlugin`](https://www.nuget.org/packages/servicebus.attachmentplugin) version 1.0.2 and up. You can try that in action or see this sample project using it:

![sourcelinking](https://user-images.githubusercontent.com/1309622/29448151-7f1a3422-83b2-11e7-8295-057ed338616d.gif)

**Comment by SeanFeldman** [comment]
I can send a PR if there are no objections 🙂 
<img src="https://media.giphy.com/media/J33SbyIEQ4SoU/giphy.gif" />

**Comment by vinaysurya** [comment]
Thanks for the idea @SeanFeldman ! Sounds great! Think this will be very handy for people running into issues and want to do a first hand analysis of what is going and may result in a PR following it too :-)

**Comment by vinaysurya** [comment]
![image](https://user-images.githubusercontent.com/20955970/29467106-164b53ee-83f4-11e7-929b-3b2ccb440288.png)

**Comment by SeanFeldman** [comment]
> may result in a PR following it too

@vinaysurya you read my mind 😉 

I'll send a PR shortly. Will it go into `1.1.0`?

**Comment by vinaysurya** [comment]
I've tagged for 1.1.0, will check with @binzywu and @nemakam and confirm

**Comment by SeanFeldman** [comment]
Great. Once a PR is there, this could be slowly applied to rest of the .NET libraries/packages. At least this is my hope.

**Comment by nemakam** [comment]
Its pretty handy. Definitely worth a try. (y)

**Comment by SeanFeldman** [comment]
🎉 on behalf of all those that ever wanted to step into the source code of the client (old and new alike) - THANK YOU.
