### ISSUE TITLE
Calling QueueClient.SendAsync(..) hangs

### ISSUE THREAD

**Issue by thisispaulsmith** [Azure/azure-service-bus-dotnet#281]
Calling `await queueClient.SendAsync(message);` hangs.

I've tried this in several projects but the same behavour is experienced running the sample code documented here [https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient](url)

This hangs everytime.

I would expect this to publish a message to the service bus.

Visual Studio 2017
NetCoreApp 1.1

**Comment by nemakam** [comment]
@thisispaulsmith I just tried the sample again with different types of queues and the same environment config (2017 + 1.1NetCoreApp) and things work as expected.
Do you have more details on where in client library code does it hang? Also, could you try running it from another machine and check the result?

**Comment by nemakam** [comment]
My hunch is that you aren't able to establish a connection in the first place. Double check your firewall rules which may blocks these requests. Also, do you run behind a proxy?

**Comment by SeanFeldman** [comment]
Alternatively, provide a link to a repro.

**Comment by thisispaulsmith** [comment]
@nemakam It appears to be connectivity issue. I had dismissed that as a possible problem as the older Azure.ServiceBus library worked with the same connection string on the same machine/network.

I've just tried the sample code at home and it works as expected. Does this connected over a different protocol/port?

**Comment by thisispaulsmith** [comment]
The connection is made over port 5671. Can this be configured?

**Comment by SeanFeldman** [comment]
See #102. Currently panned for 1.1.0.

**Comment by thisispaulsmith** [comment]
@SeanFeldman Thanks

**Comment by esmeraldahs** [comment]
Hello, i am having the same issue. 
The point is that sending the message to the queue works, because i can see the message (using azure trigger functions), it's my WPF that freezes and while debugging i noticed that it stops at the line : await queueClient.SendAsync(messageBody) 
 This is the code where i am trying to send to the Azure Service Bus Queue

`public async Task SendMessagesAsync(string message)
        {
            try
            {
                var messageBody = new Message(Encoding.UTF8.GetBytes(message));
                try
                {
                    //the await itself waits for the process to be completed, if any problem, throws exception
                    await queueClient.SendAsync(messageBody);
                    logger.Write($"Payload was sent successfully to server. ==> {message}", LogEventLevel.Information);
                }
                catch (Exception ex)
                {
                    logger.Write($"The process of sending data to the queue failed because this exception was thrown:{ex}", LogEventLevel.Error);
                    Application.Current.Dispatcher.Invoke(delegate
                    {
                        errorQueueStatus.Show();
                    });
                }
            }
            catch (Exception exception)
            {
                logger.Write($"The process of sending data to the queue failed because this exception was thrown: {exception}", LogEventLevel.Error);
                Application.Current.Dispatcher.Invoke(delegate
                {
                    errorQueueStatus.Show();
                });
            }
        }`

**Comment by Oliii** [comment]
Hello,
I was having the same issue using a TopicClient, and adding a configureAwait(false) to the sendAsync call resolved it:
`await queueClient.SendAsync(message).ConfigureAwait(false);`
