### ISSUE TITLE
Randomly getting MessageLockLostException when calling Complete/CompleteAsync

### ISSUE THREAD

**Issue by mss37** [Azure/azure-service-bus-dotnet#284]
## Actual Behavior
Queue is empty, queue config: 
- DefaultMessageTimeToLive = TimeSpan.FromHours(1),
- LockDuration = TimeSpan.FromMinutes(5),
- DuplicateDetectionHistoryTimeWindow = TimeSpan.FromMinutes(10),
- MaxDeliveryCount = 10,

1. IQueueClient queueClient = new QueueClient.............
2. IMessageReceiver rec = new MessageReceiver.....................
3. await queueClient.SendAsync(new Message(someData) { MessageId = Guid.NewGuid().ToString() });
4. var res = await rec.ReceiveAsync();
5. await rec.CompleteAsync(res.SystemProperties.LockToken);
6. Most of the time randomly I get MessageLockLostException, with the text: "The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.", **and the message stays in the queue**.

## Expected Behavior
1. The method call succeeds.
2. The message is removed from the queue.

## Versions  
- OS platform and version: 10
- .NET Version: Standard1.6+net47
- NuGet package version or commit ID:1.0.0

**Comment by SeanFeldman** [comment]
Are you running with debugger when you get the exception?
What's the lock duration on the queue?

**Comment by mss37** [comment]
Yes, I am using the debugger.
LockDuration = TimeSpan.FromMinutes(5),

**Comment by SeanFeldman** [comment]
Hmm, can't see anything obvious from the pseudo code. Could you share a simple repro to demonstrate that behavior?
Also, no chance that the same queue is consumed by anyone/thing else?

**Comment by mss37** [comment]
https://github.com/mss37/AzureServiceBusDotnetIssue284Example
It seems that I missed the part of creating a new client for each step, without this the issue doesn't show up.

**Comment by mss37** [comment]
This is clearly still an issue, but I have one question, is there any harm in using a client or receiver for a prolonged period of time? does the client have any internal status?

**Comment by SeanFeldman** [comment]
> This is clearly still an issue

In your repro, you're recreating QueueClient and MessageReceiver. Any specific reason?

I'll let MSFT team address this, but the client/message receiver used to receive message should be used to complete it as well.

**Comment by nemakam** [comment]
@SeanFeldman is right. 
You need to `complete` the message on the same `QueueClient`/`MessageReceiver` that you received it from. The details are stored at a connection (technically, AMQP-link) basis. With AMQP currently, you will not be able to complete the message on a different `QueueClient`.
Also, another thing I notice is that you do not call `await QueueClient.CloseAsync()` before creating a new client. Each of these clients create background threads for different functions. You need to remember to close the clients before discarding the object.

**Comment by nemakam** [comment]
> This is clearly still an issue, but I have one question, is there any harm in using a client or receiver for a prolonged period of time? does the client have any internal status (I supposed it shouldn't, it should be a very thin client to minimize issues)?

The clients are designed to run for a prolonged time. You should not have no problem with that. The only slight exception is `Session`. You need to periodically renew the session lock. That client cannot be reused once the session lock is lost.

**Comment by nemakam** [comment]
Closing this issue. Let me know if your concerns are not addressed yet.

**Comment by SeanFeldman** [comment]
There is something related. I'll raise a separate issue.

**Comment by mss37** [comment]
Happy with adding the issue about adding the remark, I was about asking for that, actually, it worth mentioning this in the exception text (as a potential reason)
The lock supplied is invalid. Either the lock expired, the message has already been removed from the queue, **or was received using a different receiver instance**.

**Comment by cmeiklejohn** [comment]
I'm running into this with a very simple example:

```
SubscriptionClient.RegisterMessageHandler(
                (message, token) =>
                {
                    // Process the message
                    Log.Info($"Received message: SequenceNumber:{message.SystemProperties.SequenceNumber} Body:{Encoding.UTF8.GetString(message.Body)}");

                    // Can't call CompleteAsync here without MessageLockLostException thrown!

                    return Task.CompletedTask;
                },
                (exceptionEvent) =>
                {
                    // Process the exception
                    Log.Info("Exception = " + exceptionEvent.Exception);
                    return Task.CompletedTask;
                });
```

**Comment by SeanFeldman** [comment]
@cmeiklejohn don't see `MessageHandlerOptions` defined in your handler registration. The default is to auto-complete messages. So if you try to complete it in your handler, you'll get the exception.

**Comment by cmeiklejohn** [comment]
Here's my modified example that's still triggering the error.

```
 SubscriptionClient = new SubscriptionClient(ServiceBusConnectionString,
                   TopicName,
                   SubscriptionName,
                   ReceiveMode.PeekLock);

            SubscriptionClient.RegisterMessageHandler(
                async (message, token) =>
                {
                    // Process the message
                    Log.Info($"Received message: SequenceNumber:{message.SystemProperties.SequenceNumber} Body:{Encoding.UTF8.GetString(message.Body)}");
                   // Complete the lock
                    await SubscriptionClient.CompleteAsync(message.SystemProperties.LockToken);
                },
                (exceptionEvent) =>
                {
                    // Process the exception
                    Log.Info("Exception = " + exceptionEvent.Exception);
                    return Task.CompletedTask;
                });
        }
```

**Comment by SeanFeldman** [comment]
@cmeiklejohn did you try to update your code based on my https://github.com/Azure/azure-service-bus-dotnet/issues/284#issuecomment-390018538 ?

When you register a handler w/o explicit options, you're using the defaults.

**Comment by cmeiklejohn** [comment]
Maybe I misunderstood.  I'm specifying the locktype in the subscription client now rather than assuming the default.  Does that not carry on to the handler?

```
SubscriptionClient = new SubscriptionClient(ServiceBusConnectionString,
                   TopicName,
                   SubscriptionName,
                   ReceiveMode.PeekLock);
```

**Comment by SeanFeldman** [comment]
You're specifying *RecieveMode*. You're not specifying Message handler
behavior.
Please add that option to message handler registration and verify it's
working as expected.

**Comment by cmeiklejohn** [comment]
Yes, I see now.  That resolved my issue, thank you very much for your help!

**Comment by Alchemy86** [comment]
Im using the exact example from MS.
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues 

And I'm getting this issue every time... Why would this be, auto complete is set to false. and the code is as seen on the site.

**Comment by nemakam** [comment]
How often do you get this?

**Comment by Alchemy86** [comment]
I can write to it with the example fine but the error reading happens every
time the basic example is run. The first 4 reads of 10 are fine but after
that is all failures with that message

**Comment by maddentist** [comment]
I have the same issue while trying to read messages from a worker role (2 instances running). Both CompleteAsync and AbandonAsync throw the same Microsoft.Azure.ServiceBus.MessageLockLostException

`        public override void Run()
        {
            MessageHandlerOptions options = new MessageHandlerOptions(ExceptionReceivedHandler)
            {
                AutoComplete = WorkerRolesParameters.AutoComplete, // True
                MaxConcurrentCalls = WorkerRolesParameters.MaxConcurrentCalls, // EXCEPTION thrown whatever the value
            };

            topicClient.RegisterMessageHandler(ProcessMessageAsync, options);
            CompletedEvent.WaitOne();
        }

        private Task ProcessMessageAsync(Message message, CancellationToken cancellationToken)
        {
            if (message != null)
            {
                processor.MessageTriageAndActionForTopic(message);
            }
            return Task.CompletedTask;
        }

        private Task ExceptionReceivedHandler(ExceptionReceivedEventArgs arg)
        {
            Debug.WriteLine("Error handling incoming message in enistein workerrole : " + arg.Exception.Message);
            return Task.CompletedTask;
        }        

	internal async void MessageTriageAndActionForTopic(Message message)
        {
                // Traitement du message

                byte[] data = message.Body;

                FromDeviceHubMessagesTypes messageType = (FromDeviceHubMessagesTypes)data[0];
                byte[] payload = data.SubArray(1);
                Debug.WriteLine("PROC / TCPSENDER => Triaging " + messageType.ToString() + " // Instance : " + RoleID);

                if (messageType != FromDeviceHubMessagesTypes.InterCloudReturnPackage)
                {
                    Debug.WriteLine("PROC / TCPSENDER => wrong package received" + " // Instance : " + RoleID);
                    return;
                }

                ReturnToDeviceIntermediatePackage package = await BinarySerializerWrapper.DeserializeToObjectAsync<ReturnToDeviceIntermediatePackage>(payload);

                if (connectors.TryGetValue(new IPAddress(package.IpAdress).ToString(), out TcpThread thread))
                {
                    Debug.WriteLine("Trying to feed data to " + (new IPAddress(package.IpAdress).ToString()) + " on instance " + RoleID);
                    thread.FeedData(package.Payload, await TellIfDisconnectPacket(package.Payload));
                    await queueClient.CompleteAsync(message.SystemProperties.LockToken);
                }
                else
                {
                    Debug.WriteLine("Message abandonned by instance " + RoleID);
                    await queueClient.AbandonAsync(message.SystemProperties.LockToken);
                }
        }`

**Comment by SeanFeldman** [comment]
@maddentist `MessageTriageAndActionForTopic` should **not** be `async void`. Call to this method should be awaited. Why there's a `processor.` when the method is invoked?
