### ISSUE TITLE
Build server artifacts

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#285]
## Actual Behavior

![image](https://user-images.githubusercontent.com/1309622/29532091-b36f6b9e-8668-11e7-8ab7-3ffc670fa753.png)

## Expected Behavior

Capture nuget package for local testing / inspections.

**Comment by clemensv** [comment]
I can't make sense out of this bug. Reopen with clarification.

**Comment by SeanFeldman** [comment]
AppVeyor is capturing build artifacts. Currently it's not configured and captures code coverage report.

When a PR is built, AV could capture the nuget package generated by the project to be used for smoke testing.
