### ISSUE TITLE
CompleteAsync() remarks should mention receiver affinity when completing messages

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#286]
Similar to the full framework client, [`CompleteAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagereceiver.completeasync) operation's remark should include similar warning:

>  If using AMQP, this operation can only be performed on messages that were received by this receiver.

[Current implementation](https://github.com/Azure/azure-service-bus-dotnet/blob/b39ef8a63c84d0b1bfa7c36ff13e2dc021b97833/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs#L369-L416) doesn't have that remark.

**Comment by nemakam** [comment]
Also, as part of this change, the `MessageLockLostException`'s error message can be updated as suggested in https://github.com/Azure/azure-service-bus-dotnet/issues/284#issuecomment-323825573
