### ISSUE TITLE
Create Queues programmatically

### ISSUE THREAD

**Issue by axio-marco** [Azure/azure-service-bus-dotnet#290]
Is it possible to create a queue programmatically?
What behavior should I expect when the specified queue name does not refer to a created queue?

I could not find documentation about that topic.

**Comment by axio-marco** [comment]
I am sorry, I did not realize the docs refer to https://www.nuget.org/packages/Microsoft.Azure.Management.ServiceBus/

**Comment by SeanFeldman** [comment]
👍 
[Readme.md](https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library) is the right approach for this library.
