### ISSUE TITLE
Different serialization of messages

### ISSUE THREAD

**Issue by iremmats** [Azure/azure-service-bus-dotnet#292]
Using the preview version 0.0.1 of this library and the versions for .net framework we send alot of messages created from string var message = new BrokeredMessage(jsonString). This has worked fine for us. Messages on the bus are then "Message Body - Data Encoded using a data contract serializer". When we do the same with 1.0.0 all messages are instead "Message Body - Data encoded as a stream of bytes".

How can we change the encoding of the message body? Receivers of our messages cannot read these messages without changing their implementation.

## Versions  
- .NET Version: Net core 1.1
- NuGet package version or commit ID: 1.0.0

**Comment by SeanFeldman** [comment]
There's a wire compatibility issue #239 that has a workaround in [one of the comments](https://github.com/Azure/azure-service-bus-dotnet/issues/239#issuecomment-320820562)

**Comment by iremmats** [comment]
Thanks, we are waiting for the PR to be merged and released then. Meanwhile we will use the preview version. 
You can close this issue.

**Comment by SeanFeldman** [comment]
> Meanwhile we will use the preview version.

@iremmats not sure what PR you're referring to. Irregardless, there's an [official release](https://github.com/Azure/azure-service-bus-dotnet/latest) you should probably use instead of preview.
