### ISSUE TITLE
Provide RenewLockAsync functionality which accepts only LockToken

### ISSUE THREAD

**Issue by shahbarkha** [Azure/azure-service-bus-dotnet#295]
IMessageReceiver method:
 Task RenewLockAsync(Message message);
Takes "Message" as the argument as opposed to all other similar methods which takes" string lockToken" as follows:

Task CompleteAsync(IEnumerable<string> lockTokens);
Task DeferAsync(string lockToken);
 Task AbandonAsync(string lockToken);
 Task DeadLetterAsync(string lockToken);

Why RenewLockAsync is taking Message object and not lockToken string as the argument?

How do you expect the user to use the RenewLockAsync method when we don't expose the Message object to them?

On search I found this issue and understood the reason, however, what is the way to create Message Object given we have lock token?
https://github.com/Azure/azure-service-bus-dotnet/pull/245

**Comment by niemyjski** [comment]
Any updates on this

**Comment by SeanFeldman** [comment]
@niemyjski updates? It was opened 2h ago...

**Comment by niemyjski** [comment]
Lol was on my phone and came across it, didn't check the date

**Comment by SeanFeldman** [comment]
> How do you expect the user to use the RenewLockAsync method when we don't expose the Message object to them?

Who are we in this scenario? Are you creating a library where your library is abstracting ASB? In that case, do you need to expose lock token or message at all? Wouldn't that be handled by your abstraction whenever users of your library request current message processing extension? Thanks.

**Comment by shahbarkha** [comment]
@SeanFeldman

Who are we in this scenario?Are you creating a library where your library is abstracting ASB?

>> We are the Foundatio Library that provides generic abstraction on the queue and it allows users to renew the lock if needed. When the queue item is dequed we send the item to the user and also the necessary value obtained from the MessageBus/ Message which used to be lockTocken so that user can renew the lock by itself. The library is not handling the logic if the locktocken needs to be renewed. We give the discretion to the user. I will talk to @niemyjski to discuss this further. In the old library RenewLockAsync used to take the lockTocken and it just didn't make any sense to pass heavy weight Message object to the RenewLockAsync method while all other siblings methods takes lockTocken.

**Comment by SeanFeldman** [comment]
@Azure/azure-service-bus-write was message receiver in the old client tracking the received messages somehow to have access to those via lockTokens?

**Comment by SeanFeldman** [comment]
Looking at PR #245 it seems like regression made to satisfy `Message.LockedUntiUtc` update.

In the old client, `client.RenewLockToken(lockToken)` would return the new `LockedUntilUtc` DateTime value where in PR #245 the change was done to update `Message` due to the fact that `LockedUntilUtc` property is internal and cannot be modified from the outside. Hence passing message into the `RenewLockToken` method. 

Either the change in PR needs to be reverted, or there needs to be a way to modify the property w/o forcing the entire `Message` to be passed in. On the other hand, if someone is extending lock duration while manually receiving a message, wouldn't they already handle timing manually anyways? I.e. how important in this scenario to keep `LockedUntilUtc` up-to-date?

**Comment by niemyjski** [comment]
I agree, also the locked until should be a read only public property as it's adding value and not hurting anything. Are there any updates on if this will make it into the next release? This is kind of a blocker.

**Comment by nemakam** [comment]
This seems like a reasonable ask. 
After discussing it with the team, we have decided to have an overload of `Task<DateTime> RenewMessage(string lockToken)` which can be used to renew the message.
Needless to say, lock tokens in AMQP are link-specific. i.e., the `MessageReceiver` that received this message is the only client entity which can renew the lock.

We will try to work on this when possible. If you are blocked on it, you could consider raising a PR. It should be a very simple fix (given #245).

**Comment by SeanFeldman** [comment]
> After discussing it with the team, we have decided to have an overload of Task<DateTime> RenewMessage(string lockToken) which can be used to renew the message.

@nemakam to confirm, the overload would not update message `LockedUntilUtc` property and will throw if given a `LockTocken` of a message received with another receiver?

**Comment by nemakam** [comment]
Yes. That is correct. This information will have to be part of the remarks.

**Comment by shahbarkha** [comment]
@nemakam @SeanFeldman Can you guys please tell me when can we expect a new version of this library?

**Comment by SeanFeldman** [comment]
It's in `develop`, so logically as part of 2.0

**Comment by shahbarkha** [comment]
Thanks Sean but I was more interested to know the ETA? :)

**Comment by SeanFeldman** [comment]
I'm not aware of a specific date, but will quote this:

*"**I love deadlines. I love the whooshing noise they make as they go by." *
😉

Given this commit (
https://github.com/Azure/azure-service-bus-dotnet/commit/4012c45a713ad13ecd19bc8503512fa5169b1ad1),
the answer is: soon.

**Comment by nemakam** [comment]
@shahbarkha @SeanFeldman, We would aim at releasing version 2.0 this week.

**Comment by shahbarkha** [comment]
Woooohooooo

**Comment by nemakam** [comment]
@Shahbarkha @SeanFeldman 
We are currently experiencing delays and challenges with the build signing process to release the nuget. We will provide updates when we have some to share. Currently, doesn't look like we will be able to release this week.
Sorry for the inconvenience.

**Comment by shahbarkha** [comment]
@nemakam Hi Neeraj, Any update on 2.0 release of this library? :)

**Comment by nemakam** [comment]
@shahbarkha 
2.0 is now released! Apologies for the delay!

**Comment by shahbarkha** [comment]
That’s a great news. Worth the wait. 

Thank you
