### ISSUE TITLE
Should IClientEntity.IsClosedOrClosing implementations be thread safe?

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-service-bus-dotnet#297]
For example `ClientEntity` implements it with a vanilla property:
https://github.com/Azure/azure-service-bus-dotnet/blob/b39ef8a63c84d0b1bfa7c36ff13e2dc021b97833/src/Microsoft.Azure.ServiceBus/ClientEntity.cs#L37

However its name suggests asynchronous use, implying that something like `volatile` or `Interlocked` should be used on the underlting variable (like they do in `CancellationTokenSource`).

**Comment by nemakam** [comment]
Closed via #330
