### ISSUE TITLE
NamespaceManager - add a CancellationToken parameter to Async methods

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-service-bus-dotnet#298]
e.g. `CreateTopicAsync(TopicDescription)`.

**Comment by SeanFeldman** [comment]
You might want to move this to the the repo that is for the client you're referring to, `WindowsAzure.ServiceBus` -> https://github.com/Azure/azure-service-bus. This repo is for the new client `Microsoft.Azure.ServiceBus` that [doesn't have `NamespaceManager`](https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library).

**Comment by ohadschn** [comment]
Done, thanks for noticing: https://github.com/Azure/azure-service-bus/issues/80.
