### ISSUE TITLE
Remove solution folders for test & src from solution in VS

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#30]
This is what it currently looks like

![image](https://cloud.githubusercontent.com/assets/1309622/20992657/c64c6838-bca2-11e6-9dba-79ccd4401604.png)

Each time navigation to the source or test project requires unnecessary expansion of the `src` and `test` solution folders. While it's ok to keep things separated on the file system, is there a real need for this in a VS solution? 

Suggest to remove those solution folders in VS (keep it on the file system). That way loading solution will present the projects right away.

**Comment by jtaubensee** [comment]
Closing this issue. One other thing to note, is that there is the need for multiple projects inside the solution as the library closes. I am getting ready to submit a PR that will have a UWP test project, and I can see a future where there are Service Bus extensions that might reside in the same repo/solution.
