### ISSUE TITLE
var or not var

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#300]
at the risk of bike shedding. i dont mind var or not var, but it makes it hard to contribute when there is no consistency

**Comment by SeanFeldman** [comment]
> var or not var

Is not the question.

VAR! 😃

**Comment by nemakam** [comment]
We would happily accept your contribution irrespective of whether you use var or no var. We want to make it easier for everyone (var or not-var people) to contribute.
We currently don't have plans of working on changing this. But if you are interested, feel free to send out a PR with the changes with the setting `use var where evident`
