### ISSUE TITLE
MSB3644	The reference assemblies for framework ".NETCore,Version=v5.0" 

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#301]
I get a compile error because of ` <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>`
https://github.com/Azure/azure-service-bus-dotnet/commit/a21a7b6598525f6b690736541985d1b82f3c2767#diff-8a6ee8acd956baca004497033464d66eR35

**Comment by nemakam** [comment]
What is the exact error message that you get?
We have a perfectly running build and a [UWP sample](https://github.com/Azure/azure-service-bus/pull/73 ) which works pretty well with the current client

**Comment by nemakam** [comment]
And you get this error message while building the client code or while using `Microsoft.Azure.ServiceBus` nuget package in your application?

**Comment by SimonCropp** [comment]
when building 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETCore,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	Microsoft.Azure.ServiceBus	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1122	
```

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: Microsoft.Azure.ServiceBus, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1122,5): error MSB3644: The reference assemblies for framework ".NETCore,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
1>Done building project "Microsoft.Azure.ServiceBus.csproj" -- FAILED.
2>------ Rebuild All started: Project: Microsoft.Azure.ServiceBus.UnitTests, Configuration: Debug Any CPU ------
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

```

**Comment by nemakam** [comment]
> MSB3644	The reference assemblies for framework ".NETCore,Version=v5.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version

Looks like you don't have the latest dotnet core SDK installed. Could you update your SDK version and try again.

**Comment by SimonCropp** [comment]
can u give me a url to `.NETCore,Version=v5.0` ?

**Comment by SimonCropp** [comment]
and this is what i have installed now 
![image](https://user-images.githubusercontent.com/122666/30298053-5449fd38-978d-11e7-9ba3-b5b8754a5e29.png)

**Comment by nemakam** [comment]
@SimonCropp , not sure why you are facing this. Might be a dotnet error that you are facing? This seems to compile just fine in every other machine that we use (and lot of other contributers + public build servers etc).
One other thing that I notice is that we take dependency on [Microsoft.NETCore.UniversalWindowsPlatform v5.2.3](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/5.2.3) which internally takes dependency on [Microsoft.NETCore v5.0.2](https://www.nuget.org/packages/Microsoft.NETCore/).
This might be the framework version it is referring to. See if your nuget package restore works fine. Maybe just create a standalone project and try to take a dependency on `Microsoft.NETCore.UniversalWindowsPlatform` nuget.

**Comment by nemakam** [comment]
@SimonCropp do you plan to use this for uap app or regular dotnetcore app?

**Comment by SimonCropp** [comment]
given netstandard 1.3 supports UAP OOTB no extra csproj config should required https://github.com/Azure/azure-service-bus-dotnet/pull/310/commits/15865e7c2d45ac1e9ea4172dfbef312a89bca3c1

**Comment by sorenhoyer** [comment]
I get the same error.
