### ISSUE TITLE
Delete non-executed code.

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#312]
Regarding this comment https://github.com/Azure/azure-service-bus-dotnet/pull/308#issuecomment-328670851

> The second one removes couple of helper utility methods which may be useful later. They don't do any harm.

Dont leave it in "just in case we need it" https://www.mjhilton.net/2017/09/06/source-control-antipatterns/

**Comment by clemensv** [comment]
This issue isn't actionable. If there's concrete dead code, let's reference that in an isolated issue and get rid of it. I agree with the stance that we shouldn't carry dead code in the active code base. That's why we use a VCS.

**Comment by SimonCropp** [comment]
But i linked to dead code. Isnt that explicitly actionable

**Comment by clemensv** [comment]
Maybe that link is a bit subtle. I don't see it.

**Comment by nemakam** [comment]
@clemensv , the previous conversation was long. @SimonCropp is referring to 
https://github.com/Azure/azure-service-bus-dotnet/pull/308/commits/37df79167dd5660391e4299d51c64f62fa496440

**Comment by nemakam** [comment]
Fixed in #347
