### ISSUE TITLE
Move over to using the PublicApiGenerator nuget

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#315]
do u want a PR?

**Comment by SeanFeldman** [comment]
Currently, API changes tested against full framework only and not .NET Standard. With PublicApiGenerator it would become possible to run for both.

**Comment by nemakam** [comment]
Does it provide any advantage over the current situation? I don't think the API surface would change with different framework targets. 
I am still open to the PR, but not sure if its worth the effort.

**Comment by SimonCropp** [comment]
I was not suggesting for the purposes of diff frameworks. But from the desire to remove a large chink of code that you should not own in this codebase

**Comment by nemakam** [comment]
If that's the change, then I'm super inclined to get this change in.

**Comment by SeanFeldman** [comment]
There is one caveat to watch out. The default implementation [blacklisted anything coming from the `Microsoft.` namespace](https://github.com/Azure/azure-service-bus-dotnet/pull/170/files#diff-f9f4148478840eaec24f00670498a6dcR116). There might be a patch required to the PublicApiApprover first.

**Comment by clemensv** [comment]
@nemakam @SeanFeldman @SimonCropp I labeled this as a backlog item just now, but I'm not a fan of keeping issues of that sort open because test/build tooling choices change quickly. Unless there's an instant workable improvement that's equivalently functional with less code and there's actual work being scheduled/done to integrate, I lean towards tossing the issue out for now.

**Comment by nemakam** [comment]
@SimonCropp 
> There is one caveat to watch out. The default implementation blacklisted anything coming from the Microsoft. namespace. There might be a patch required to the PublicApiApprover first.

With this, does this issue need to be open? Is there a way to get rid of the clunky code in the repo?

**Comment by SeanFeldman** [comment]
@clemensv @nemakam I can look into it. Assign to me.

**Comment by SeanFeldman** [comment]
Update: we can remove this code once PublicApiGenerator supports [white-listing namespace](https://github.com/JakeGinnivan/ApiApprover/issues/32).
I'll work with PublicApiGenerator maintainers to get that change in and send a PR for ASB client.

**Comment by SeanFeldman** [comment]
Update: my [PR with white-listing](https://github.com/JakeGinnivan/ApiApprover/pull/36) has been merged. Once updated package shows up on Nuget, I'll be moving this forward.
