### ISSUE TITLE
Add the ability to retrieve/query sequence numbers of scheduled messages

### ISSUE THREAD

**Issue by boylec** [Azure/azure-service-bus-dotnet#316]
## Actual Behavior
1. Client used to schedule a message (returns a reference to the scheduled message)
2. Sequence number of returned object saved into a variable.
3. Process shuts down or crashes.
4. Need to cancel scheduled message arises.
5. Message occurs anyway because there was no way to retrieve the sequence number to cancel it.

## Expected Behavior
1. Client used to schedule a message (returns a reference to the scheduled message)
2. Sequence number of returned object saved into a variable.
3. Process shuts down or crashes.
4. Need to cancel scheduled message arises.
5. Client used to query sequence numbers of scheduled messages.
6. Sequence numbers used to cancel scheduled messages using IQueueClient.CancelScheduledMessagesAsync.

## Versions  
- OS platform and version: Windows 10
- .NET Version: 4.7
- NuGet package version or commit ID: The most recent

**Comment by clemensv** [comment]
See issue #343. I'm closing this one since fixing that issue will enable this feature. You can already do this in the NETFX client as I point out in that bug.
