### ISSUE TITLE
questionable string argument checking

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#318]
I have noticed in many areas some questionable string arg checking 

eg https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Primitives/SecurityToken.cs#L57

```
        public SecurityToken(string tokenString)
        {
            if (tokenString == null)
            {
                throw Fx.Exception.ArgumentNull(nameof(tokenString));
            }
```

so am i to assume an empty string for `tokenString` is valid?

if not would u like a PR?

**Comment by nemakam** [comment]
Sure. Go ahead and include this in your PR.
Btw, this is internal and none of the internal methods call this with empty string. But I agree to your point.

**Comment by SimonCropp** [comment]
@nemakam if u dont mind i will do this as a new PR after the other one is merged

also there are instances that are part of the public api. eg

```
        public override void UnregisterPlugin(string serviceBusPluginName)
        {
            ....
            if (serviceBusPluginName == null)
            {
                throw new ArgumentNullException(nameof(serviceBusPluginName), Resources.ArgumentNullOrWhiteSpace.FormatForUser(nameof(serviceBusPluginName)));
            }
```

**Comment by nemakam** [comment]
Sure.. No problem.. Thanks
