### ISSUE TITLE
MessageReceiver.RegisterPlugin fails to pass plugin name

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-service-bus-dotnet#326]
MessageReceiver.RegisterPlugin does this

```
throw new ArgumentException(nameof(serviceBusPlugin), Resources.PluginAlreadyRegistered.FormatForUser(nameof(serviceBusPlugin)));
```

where `PluginAlreadyRegistered` is `The {0} plugin has already been registered.` which will always result in `The serviceBusPlugin plugin has already been registered.`.

I will fix in a PR

**Comment by SeanFeldman** [comment]
`MessageReceiver` is affected as well. Addressed by #559
