### ISSUE TITLE
Abstracting common components for easier testing

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#33]
There are scenarios where it would help to be able to test code that relies on ASB client w/o exercising ASB client itself. A few scenarios are:
- Broker not available
- Emulating certain operations to throw exceptions they can raise, but not on demand

With previous client the only option is to wrap everything from ASB to allow mocks/stubs. It would help to have new client to take testability into consideration.

**Comment by nemakam** [comment]
You can track the changes in PR #82

**Comment by jtaubensee** [comment]
This was addressed by #95
