### ISSUE TITLE
Support a Shared Access Signature to create a Queue|Topic|SubscriptionClient

### ISSUE THREAD

**Issue by hbiarge** [Azure/azure-service-bus-dotnet#332]
## Actual Behavior
1. All the clients have constructors that accept a ServiceBusConnectionStringBuilder or a connectionString that creates a new ServiceBusConnectionStringBuilder.
2. ServiceBusConnectionStringBuilder seems that not support Shared Access Signatures
3. The result is that all TokenProvider instances are created based on the serviceBusConnection.SasKeyName and the serviceBusConnection.SasKey
4. It forces the client to know that sensitive information.

## Expected Behavior
1. ServiceBusConnectionStringBuilder should support Shared Access Signatures
2. The TokenProvider should be created with the existing factory method: TokenProvider.CreateSharedAccessSignatureTokenProvider(serviceBusConnection.SharedAccessSignature)

## Versions  
- OS platform and version: All
- .NET Version: All
- NuGet package version or commit ID: 1.0.0

**Comment by nemakam** [comment]
@hbiarge Looks the SAS token is currently not completely integrated. We can definitely work on this feature. However, it might not be part of the next release 2.0. Thanks for bringing this up.

**Comment by clemensv** [comment]
SAS token support should indeed be prioritized.
