### ISSUE TITLE
Make previously available classes/enums public again

### ISSUE THREAD

**Issue by alexeyzimarev** [Azure/azure-service-bus-dotnet#335]
I spent some time working on the MassTransit migration to use this library.

However, many elements are now made internal or private, whilst we count on them to be public.

Examples:

- `TokenProvider` - internal abstract static class but static methods are public
- `TokenScope` - internal enum

**Comment by nemakam** [comment]
@alexeyzimarev 
I would like to know your use-case for this request. 
We already have a request to allow using SAS tokens (#332). Does this take care of your scenario?

**Comment by alexeyzimarev** [comment]
@nemakam as I wrote, I am working to switch MassTransit from the old ServiceBus library to this library. The API I mentioned was public before. It means that in the new library the API surface has changed so much that we now need to seek workarounds for something that just worked before.

I give you an example about `TokenProvider`. This class has several static methods to create a shared access key token provider with different set of parameters. *None* of those methods are being used in the library itself. What is the reason this API has even been made? Definitely, it would be useful for the API users to have the ability to call these methods. By doing so, you will not force us to support all these ways to create the shared access key token provider by all parameters combinations that you accept, but just let our users to choose, which factory method to use from the `TokenProvider` class itself and let us keep the reference to the `TokenProvider` object.

**Comment by alexeyzimarev** [comment]
I mean, how do we suppose to use these methods:
https://github.com/Azure/azure-service-bus-dotnet/blob/10fb579c967200563c108b4e4282de5ead79730e/src/Microsoft.Azure.ServiceBus/Primitives/TokenProvider.cs#L42
https://github.com/Azure/azure-service-bus-dotnet/blob/10fb579c967200563c108b4e4282de5ead79730e/src/Microsoft.Azure.ServiceBus/Primitives/TokenProvider.cs#L53
https://github.com/Azure/azure-service-bus-dotnet/blob/10fb579c967200563c108b4e4282de5ead79730e/src/Microsoft.Azure.ServiceBus/Primitives/TokenProvider.cs#L81
https://github.com/Azure/azure-service-bus-dotnet/blob/10fb579c967200563c108b4e4282de5ead79730e/src/Microsoft.Azure.ServiceBus/Primitives/TokenProvider.cs#L93

**Comment by nemakam** [comment]
Yes. These need to get public. These will be made public as part of #332. 
Meanwhile If you are blocked on this, it would be best if you could raise a PR for this. I can help you out with the changes that are to be done.

**Comment by nemakam** [comment]
I'm going to mark this duplicate and track this as part of #332
