### ISSUE TITLE
Error Could not find any resources appropriate for the specified culture or the neutral culture - Xamarin Forms for Android

### ISSUE THREAD

**Issue by izefler** [Azure/azure-service-bus-dotnet#336]
The following error is occurring:

Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.Amqp.Amqp.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Amqp" at compile time, or that all the satellite assemblies required are loadable and fully signed.

09-27 22:57:04.342 E/mono    ( 3778): 
09-27 22:57:04.342 E/mono    ( 3778): Unhandled Exception:
09-27 22:57:04.342 E/mono    ( 3778): System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.Amqp.Amqp.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Amqp" at compile time, or that all the satellite assemblies required are loadable and fully signed.
09-27 22:57:04.342 E/mono    ( 3778):   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) [0x000bf] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2[TKey,TValue] localResourceSets, System.Boolean tryParents, System.Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) [0x000d9] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, System.Threading.StackCrawlMark& stackMark) [0x00099] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents) [0x00002] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Resources.ResourceManager.GetString (System.String name, System.Globalization.CultureInfo culture) [0x0005a] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at Microsoft.Azure.Amqp.Amqp.Resources.get_AmqpTimeout () [0x00005] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1[T].CompleteOnTimer () [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1[T].OnTimerCallback (System.Object state) [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1+<>c[T].<SetTimer>b__5_0 (System.Object s) [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono    ( 3778):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778): [ERROR] FATAL UNHANDLED EXCEPTION: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.Amqp.Amqp.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Amqp" at compile time, or that all the satellite assemblies required are loadable and fully signed.
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) [0x000bf] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2[TKey,TValue] localResourceSets, System.Boolean tryParents, System.Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) [0x000d9] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, System.Threading.StackCrawlMark& stackMark) [0x00099] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents) [0x00002] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Resources.ResourceManager.GetString (System.String name, System.Globalization.CultureInfo culture) [0x0005a] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.Amqp.Resources.get_AmqpTimeout () [0x00005] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1[T].CompleteOnTimer () [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1[T].OnTimerCallback (System.Object state) [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1+<>c[T].<SetTimer>b__5_0 (System.Object s) [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.342 E/mono-rt ( 3778):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778): [ERROR] FATAL UNHANDLED EXCEPTION: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Azure.Amqp.Amqp.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Amqp" at compile time, or that all the satellite assemblies required are loadable and fully signed.
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (System.String fileName) [0x000bf] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (System.Globalization.CultureInfo culture, System.Collections.Generic.Dictionary`2[TKey,TValue] localResourceSets, System.Boolean tryParents, System.Boolean createIfNotExists, System.Threading.StackCrawlMark& stackMark) [0x000d9] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo requestedCulture, System.Boolean createIfNotExists, System.Boolean tryParents, System.Threading.StackCrawlMark& stackMark) [0x00099] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Resources.ResourceManager.InternalGetResourceSet (System.Globalization.CultureInfo culture, System.Boolean createIfNotExists, System.Boolean tryParents) [0x00002] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Resources.ResourceManager.GetString (System.String name, System.Globalization.CultureInfo culture) [0x0005a] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.Amqp.Resources.get_AmqpTimeout () [0x00005] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1[T].CompleteOnTimer () [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1[T].OnTimerCallback (System.Object state) [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at Microsoft.Azure.Amqp.TimeoutAsyncResult`1+<>c[T].<SetTimer>b__5_0 (System.Object s) [0x00000] in <1fd538a4a6b8459ebd975b01426c612c>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Threading.Timer+Scheduler.TimerCB (System.Object o) [0x00007] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.343 E/mono-rt ( 3778):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-27 22:57:04.344 D/        ( 3778): HostConnection::get() New Host Connection established 0xad9a6d00, tid 3819

I want to use the Azure Service Bus in a xamarin.forms application, the following error occurs when calling the SendAsync method.

                topicClient = new TopicClient(ServiceBusConnectionString, "xamarin");
                await topicClient.SendAsync(new Message()
                {
                    Body = SerializerHelper.Serialize(message)
                });

## Expected Behavior

Creation of topic and message posting.

## Versions  
- OS platform and version: Windows 10
- .NET Version: .Net Standard 1.6
- NuGet package version or commit ID: 1.0.0

**Comment by juhamaja** [comment]
Xamarin.Droid with couple of DeviceClient methodHandlers assigned. When we lose internet connection (either on purpose or unintentionally) this will pop up. 

Aqmp 2.1.2
Devices.Client 1.5.2

**Comment by nemakam** [comment]
Might be related to https://github.com/Azure/azure-amqp/issues/82
Will update references to consume latest amqp package.

**Comment by nemakam** [comment]
The latest package (not released yet) should have your fix. Reopen if it doesn't work.

**Comment by SamuelDebruyn** [comment]
I get a FileNotFoundException with message "Invalid Image"
The filename it's referring to is `/storage/emulated/0/Android/data/my.app.id/files/.__override__/nl-BE/Microsoft.Azure.ServiceBus.resources.dll`
