### ISSUE TITLE
Add user properties when deadletter

### ISSUE THREAD

**Issue by sfalik** [Azure/azure-service-bus-dotnet#339]
In the old service bus API, you could specify a reason and error description when moving a message to the DLQ:
`public void DeadLetter (string deadLetterReason, string deadLetterErrorDescription);`

## Issue
I am trying to replicate that behaviour with this new service bus API:

        async Task ProcessMessagesAsync(Message message, CancellationToken token)
        {
            try
            {
                //Attempt to process message.....
                ProcessMessage(message);

                //Message processed successfully
                await _subscriptionClient.CompleteAsync(message.SystemProperties.LockToken);
            }
            catch (Exception ex)
            {
                //Error occurred during processing, note the error and move to DLQ
                message.UserProperties.Add("ErrorMessage", ex.ToString());
                await _subscriptionClient.DeadLetterAsync(message.SystemProperties.LockToken);
            }
        }

However, while the UserProperties.Add method succeeds, they are not actually persisted when the message is moved to the DLQ.

## Question
Is this a bug, or is this expected behaviour and there is a different way to achieve the same thing?

**Comment by sfalik** [comment]
Note:  I tried developing a ServiceBusPlugin that could modify the message before it is written to the Dead Letter Queue, but the 'BeforeMessageSend' function on the plugin is not called when moving to DLQ

**Comment by nemakam** [comment]
@sfalik 
There are a couple of issues with the implementation that you have proposed.

`message.UserProperties.Add("ErrorMessage", ex.ToString());` does add the property to the message. But this is added only in memory, and is never transmitted to ServiceBus. You need a `_subscriptionClient.SendAsync()` operation to send these messages back with the updated properties. Also, FYI, you cannot send the same message which has been received.

This can also be seen in `await _subscriptionClient.DeadLetterAsync(message.SystemProperties.LockToken);`. While calling `DeadLetterAsync()`, you only pass the `lockToken` string and not the entire message. So you updating the message in memory will not affect the message that is present in service bus.

`DeadLetterReason` is an internal property which cannot be set as a user property. You can definitely simulate it by adding your own property and use it as an alternative for deadLetterReason, but you cannot actually set the `deadLetterReason` though user properties. This also means, that above thing cannot be done through plugins. This particular offering should be in built inside the client and `deadLetterReason` should be exposed as an overload. 

> 'BeforeMessageSend' function on the plugin is not called when moving to DLQ

Moving a message from the main queue to DLQ is a service-side operation and not a client side. But `BeforeMessageSend` is a client side operation. Hence, this function is not expected to be invoked while dead-lettering a message.

**Comment by nemakam** [comment]
> Is this a bug, or is this expected behaviour and there is a different way to achieve the same thing?

This is not a bug. Its an expected behaviour. Is there a different way to achieve it? Unfortunately, this has to be added as additional information while forming the AMQP message which is sent to service to deadletter this message.

**Comment by nemakam** [comment]
As for a solution to this issue,
1. You can leave this issue open, and when we get time, we will implement this feature in future releases. OR
1. You could send a PR with the required changes. I can help you out with implementing these changes.
