### ISSUE TITLE
Filtered Subscriptions Receiving Data Matching the Default Rule

### ISSUE THREAD

**Issue by KZeronimo** [Azure/azure-service-bus-dotnet#344]
## Actual Behavior
1. When a subscription is first created, a default filter automatically gets created. That filter expression is 1=1.
2. Immediately after creating the subscription, a rule is created.  In between the time that the subscription is created and the rule is created and applied, there is some amount of data that is dumped into that subscription (based on the default rule that was automatically created).
3. When the client listens, it will get the data that was initialized into that subscription before the filter was created and applied. However, after that initial collection is sent, subsequent data will adhere to the filter criteria and it will perform exactly as expected.

## Expected Behavior
1. The semantic desired is create a subscription **with applied filter** - the client expects only to receive data that matches their filter.

## Versions  
- OS platform and version: Windows 10 
- .NET Version: .Net Core 2.0
- NuGet package version or commit ID: NuGet package 1.0.0

**Comment by binzywu** [comment]
@KZeronimo, this issue better to be posted to repo https://github.com/Azure/azure-service-bus. When you create subscription, you can add filters to it at the same time.

**Comment by KZeronimo** [comment]
@binzywu I believe that lib will not be supported inside a .NET core app

**Comment by nemakam** [comment]
@KZeronimo 
For dotnet-full framework (old client), this functionality is already present.
For dotnet-standard (or coreapp), this shall be taken care by  #65 . 
Marking this as duplicate
