### ISSUE TITLE
Message sender performance issue

### ISSUE THREAD

**Issue by KhushbooSinha01** [Azure/azure-service-bus-dotnet#345]
## Actual Behavior
While using service bus with the .net framework, able to send 750,000 records in 50 sec but with the core it is too slow like 10-20 message in 1 min.

## Expected Behavior
1. Able to send message 15000/sec to the service bus by using .net core

## Versions  
- OS platform and version: window 10
- .NET Version: 2.0 Standard
- NuGet package version or commit ID:1.0.0

**Comment by SeanFeldman** [comment]
Could you please share some information to understand the request?
1. Region used for bench-marking.
1. ASB tier (standard/premium).
1. Sending code.

**Comment by KhushbooSinha01** [comment]
Region used is South Central US
ABS - Standard
Sending Code is
namespace test
{
    using System.Threading.Tasks;
    using Microsoft.Azure.ServiceBus;
    public class MessageSender
    {
        private const string ServiceBusConnectionString = "ServiceBusConnectionString";
        private IQueueClient queueClient;
        private ITopicClient topicClient;

        public MessageSender()
        {
            queueClient = new QueueClient(ServiceBusConnectionString, "queueName", ReceiveMode.PeekLock, null);
            topicClient = new TopicClient(ServiceBusConnectionString, "topicname", null);
        }

        public async Task<int> SendMsgAsyncQueue(string[] lines)
        {
            int icount = 0;

            List<Message> msgs = new List<Message>();

            foreach (string s in lines)
            {
                msgs.Add(new Message(Encoding.UTF8.GetBytes(s)));
                icount++;
            }
            await queueClient.SendAsync(msgs);
            await queueClient.CloseAsync();
            return icount;
        }

        public async Task<int> SendMsgAsyncTopic(string[] lines)
        {
            int icount = 0;
            foreach (string s in lines)
            {
                var message = new Message(Encoding.UTF8.GetBytes(s));
                await topicClient.SendAsync(message);
                icount++;
            }
            await topicClient.CloseAsync();
            return icount;
        }
    }
}

**Comment by SeanFeldman** [comment]
Sending to topic is done one message at a time. That will be slow for sure.

Try the following:

```c#
var tasks = new List<Tasks>();
foreach (string s in lines)
{
  var msg = new Message(Encoding.UTF8.GetBytes(s));
  tasks.Add(client.Send(msg));
}
await Task.WhenAll(tasks);
```

**Comment by nemakam** [comment]
@KhushbooSinha01 
The experiment with old client v/s new client, what other parameters are different? 
Are they running from same machine? Are they running on the same namespace? 
Are they both targeting the same queue? Are both using same number of clients to send messages? 
Are both sending same batch size?

Also you mentioned you use service-bus standard namespace. Just FYI, that there are no performance guarantees that we provide for a standard namespace as it has shared resources and performance can greatly vary between different times of the day. (Read noisy-neighbor issue).
That said, 20 msgs per min is way too slow even for that. Try out @SeanFeldman's response and let us know if it resolves it. We have internal perf test that we do before we publish the library, and based on that, it holds on to the perf standards of the previous client.

**Comment by KhushbooSinha01** [comment]
@SeanFeldman 
I have tried the below code and got message size error. Message size is exceeding the Max message size limit.
var tasks = new List<Tasks>();
foreach (string s in lines)
{
  var msg = new Message(Encoding.UTF8.GetBytes(s));
  tasks.Add(client.Send(msg));
}
await Task.WhenAll(tasks);
