### ISSUE TITLE
Some examples of DotNet does not work

### ISSUE THREAD

**Issue by panicoenlaxbox** [Azure/azure-service-bus-dotnet#348]
Hi, 
I just clone the repository and create namespace and queue in azure portal but the projects _BasicSendReceiveUsingQueueClient_, _SendReceiveUsingMessageSenderReceiver_ and _BasicSendReceiveUsingTopicSubscriptionClient_ seem not work. Sending is ok but receiving does not occur.
However, the project _SessionSendReceiveUsingSessionClient_ works fine.
I have not tested the project _TopicSubscriptionWithRuleOperationsSample_.
I have tried a new project from scratch and neither with _MessageReceiver_ nor with _RegisterMessageHandler_ I am able to read messages from a queue.
The current version of the Microsoft.Azure.ServiceBus package is 1.0.0 and I'm using VS2017 (with lastest updates).
How can I help with this issue?
Thank you.

**Comment by SeanFeldman** [comment]
What exceptions do you get?

**Comment by panicoenlaxbox** [comment]
I don't receive any exception, the program simply wait and does not receive any message. After two minutes, I have deleted the queue from the azure portal and then the ExceptionReceivedHandler event has been thrown, at least, this event seems to work, the pump seems to be active :)
I have tried too to change from netcoreapp1.1 to netcoreapp2.0, but nothing changed. 
I am creating the namespace and queue without any customization, simply next > next in the azure portal (only for the example with works with session I have created a queue that supports session, but these concrete example, like I said later, works fine).
Tomorrow, I can try the examples in another machine, at my office. I will do it.

![image](https://user-images.githubusercontent.com/1210159/31318872-3c3e53ca-ac59-11e7-99b9-08173c9e15f8.png)

**Comment by panicoenlaxbox** [comment]
I think that I am experimenting the same behavior that this other issue [Not receiving messages](https://github.com/Azure/azure-service-bus/issues/89)

**Comment by SeanFeldman** [comment]
​Have you tried running the sample in a different environment?

**Comment by panicoenlaxbox** [comment]
Hello, I'm at the office and here it works!! Can be a problem with the network, maybe some port that it's not available at home? Later, when I arrive at home, I will probe it again, it's crazy :)

**Comment by SeanFeldman** [comment]
I suspect [TCP ports required by AMQP 1.0](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide) are blocked.

**Comment by SeanFeldman** [comment]
@Azure/azure-service-bus-write given this is a repeating question, perhaps the client should fail if it can't retrieve messages / connect.

**Comment by snavarropino** [comment]
I agree, client should fail in this case in order to let consumer know he is not going to receive any message. I am not very confident with this library if it does not ensure me I am going to receive messages

**Comment by panicoenlaxbox** [comment]
Finally, the situation is that is not a problem with my home or office network, I have two pcs, both with repository just cloned and the firewall disabled, in one pc works fine in any network and in the other not. In the pc that does not work I don`t know how to investigate more. I have seen that does not seem to be a problem with the network (picture attached) and in both pcs I can use [Service Bus Explorer](https://github.com/paolosalvatori/ServiceBusExplorer) to manage the queue.

![dotnet](https://user-images.githubusercontent.com/1210159/31512975-086808c0-af8d-11e7-8109-39ed8e3f4e30.png)

**Comment by nemakam** [comment]
@panicoenlaxbox  , meanwhile while we update the samples to use latest code, could you update it on your end and take a reference to Azure.Service.Bus 2.0.0 version and see if it resolves the issue.

**Comment by nemakam** [comment]
@snavarropino @SeanFeldman 
I agree. #351 which is now in release 2.0.0 should take care of that. We will no longer filter out expired messages.

**Comment by panicoenlaxbox** [comment]
@nemakam Right!, It's works updating to Azure.Service.Bus 2.0.0, thank you so much! I think that now I should close the issue, what do you think?

**Comment by heymega** [comment]
Just to add my own experience here as others might find it useful...

I had the exact same issue where messages were not being received, even when using the provided example.

It turns out my `SubscriptionClient` had no rules associated with it!

By default, you should have a rule which should accept all messages, named `$Default`. If you don't have this then you can re-add this by using the following snippet...

`await subscriptionClient.AddRuleAsync(new RuleDescription(RuleDescription.DefaultRuleName, new TrueFilter()));`

Hope this helps others.

**Comment by SeanFeldman** [comment]
@heymega what sample are you referring to? Thanks.

**Comment by heymega** [comment]
"BasicSendReceiveUsingQueueClient, SendReceiveUsingMessageSenderReceiver and BasicSendReceiveUsingTopicSubscriptionClient"

**Comment by SeanFeldman** [comment]
[BasicSendReceiveUsingTopicSubscriptionClient](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient/readme.md) has expectation for a subscription to be in place
> const string SubscriptionName = "{Subscription Name}";

A subscription w/o a single rule will not "capture" any messages, hence the behaviour you've seen.
Personally, I don't like samples that can't be executed properly w/o supplying multiple pieces of information, but in this case, either you use a properly constructed entity or you create one via code. I'll send a PR to clarify that in the `readme`.
