### ISSUE TITLE
How to create a Queue from a namespace connection string (SAS token) ?

### ISSUE THREAD

**Issue by NicolasDorier** [Azure/azure-service-bus-dotnet#358]
All example shows how to use `ServiceBusManagementClient` to create queues. 

But this is not what I want. I have my own namespace connection string with all the secrets necessary to make request for creating a queue. I could not find out how. (Previously was using the `NamespaceManager` class for that)

**Comment by SeanFeldman** [comment]
@NicolasDorier have a look at issue #65.

**Comment by NicolasDorier** [comment]
Thanks a lot, I was in the process of moving a software from MVC4 to .NET Core. 

If I understand, in a nutshell, this is not the way to do now and thus unsupported in the lib, we should migrate to the new recommended system shown in a sample somewhere. (using JWS)

I will either hold off .NET Core migration, or get rid of dependency to Azure Service Bus as I can't ask and document to all my users how to use the new system.

Feel free to close this issue if you think appropriate.

**Comment by SeanFeldman** [comment]
> If I understand, in a nutshell, this is not the way to do now and thus unsupported in the lib, we should migrate to the new recommended system shown in a sample somewhere

Yes and No. In his [detailed comment](https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-337565857) @clemensv had provided a hint to what will happen:

> Current status of the discussion is that the new client surface area for the "direct" management operations through the data plane will require a SAS token with "Manage" permission like before, but we're going to constrain it such that it is focused on the core runtime requirement to create/update/delete individual entities (queues, topics, subscriptions). The subscription client already allows managing rules. The new client will not provide access to user-supplied metadata, it will not have enumeration (paging) for entities, and it will not yield metrics. The latter requires some server work, because suppressing the metrics requires a protocol change. We also want to ditch XML, but that may be a further iteration.

This thread is connected to #65. Therefore I suggest to keep it there. Thanks for bringing your requirements up @NicolasDorier 🙂

**Comment by ChristianWolf42** [comment]
@NicolasDorier as @SeanFeldman says we will very likely enable some simple queue operations in a namespacemanager like fashion in which you can access those operations solely with you SAS token...
The not supported operations Clemens mentions in the other thread apply. I agree with Sean, let us stick to [#65](https://github.com/Azure/azure-service-bus-dotnet/issues/65)
