### ISSUE TITLE
Exception on Creating a new subscription from .Net Core API

### ISSUE THREAD

**Issue by kahootali** [Azure/azure-service-bus-dotnet#368]
## Actual Behavior
Creating Subscription from API gives exception

## Expected Behavior
Should be able to create new subscription from API rather than portal.

Using something like:
"var subsClient = new SubscriptionClient(connectionString, topicName, subscriptionName);"
throws an exception indicating that the subscription was not found. 

- NuGet package version or commit ID:
Microsoft.Azure.ServiceBus 2.0.0

**Comment by SeanFeldman** [comment]
@kahootali 

`var subsClient = new SubscriptionClient(connectionString, topicName, subscriptionName);`

[`SubscriptionClient`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.subscriptionclient?view=azure-dotnet) does **not** create a new subscription entity. It creates a subscription client required to work with an entity. I.e. entity has to exist to be used.

**Comment by kahootali** [comment]
Then how can I create a subscription if it does not exists previously through .Net Core 2.0. Because using .Net Framework I had a namespace manager and I could create Subscription using namespaceManager.CreateSubscription.

**Comment by SeanFeldman** [comment]
- [Can I manage Service Bus entities with this library?](https://github.com/Azure/azure-service-bus-dotnet#can-i-manage-service-bus-entities-with-this-library)
- [Management Operations](#65) (issue #65)

**Comment by kahootali** [comment]
Ok Thanks...
Closing it

**Comment by robvet** [comment]
Reopening this issue: In new ServiceBus library, Microsoft.AzureServiceBus (2.0.0.0), not seeing the NamespaceManager of a way to create a subscription programmatically if it does not exist. Any help would be appreciated.

**Comment by SeanFeldman** [comment]
@robvet see issue #65
