### ISSUE TITLE
Getting Microsoft.Azure.Management.ServiceBus.Models.ErrorResponseException : Operation returned an invalid status code '429' when trying to call SbManagementClient.Topics.CreateOrUpdateAsync inside "Task.Run."

### ISSUE THREAD

**Issue by shahbarkha** [Azure/azure-service-bus-dotnet#371]
Our Test Case looks like this:
We are trying to create 10 MessageBus , each trying to subscribe to a message published in the Bus. Before we subscribe to the messages, we ensure that topic is created for which we call EnsureTopicCreatedAsync as you will see below.  Inside this method we call SbManagementClient.Topics.CreateOrUpdateAsync which throws the above exception.
The internal of the exception is :

{"error":{"message":"SubCode=40901. Another conflicting operation is in progress. TrackingId:81b2c3fc-6c0f-4713-800c-d1170b592bc1_M2_M2_G6, SystemTracker:barkhas.servicebus.windows.net:test-messages, Timestamp:11/6/2017 5:28:15 AM CorrelationId: 568deea6-152b-4aca-88f6-a5f24cef4eeb","code":"429"}}

Any idea what could be wrong?
Message bus is created with following parameters

                    Topic = "test-messages",
                    ClientId = Configuration.GetSection("ClientId").Value,
                    TenantId = Configuration.GetSection("TenantId").Value,
                    ClientSecret = Configuration.GetSection("ClientSecret").Value,
                    ConnectionString = connectionString,
                    SubscriptionId = Configuration.GetSection("SubscriptionId").Value,
                    ResourceGroupName = Configuration.GetSection("ResourceGroupName").Value,
                    NameSpaceName = Configuration.GetSection("NameSpaceName").Value,
                    ReceiveMode = Microsoft.Azure.ServiceBus.ReceiveMode.ReceiveAndDelete,
                    SubscriptionWorkItemTimeout = TimeSpan.FromMinutes(5),
                    AutoComplete = false,
                    TopicEnableBatchedOperations = true,
                    TopicEnableExpress = true,
                    TopicEnablePartitioning = true,
                    TopicSupportOrdering = false,
                    TopicRequiresDuplicateDetection = false,
                    SubscriptionAutoDeleteOnIdle = TimeSpan.FromMinutes(5),
                    SubscriptionEnableBatchedOperations = true,
                    SubscriptionMaxDeliveryCount = int.MaxValue,
                    PrefetchCount = 500,
                    LoggerFactory = Log
            });

        [Fact]
        public override async Task CanReceiveMessagesConcurrentlyAsync() {
            const int iterations = 100;
            var messageBus = GetMessageBus();
            if (messageBus == null)
                return;

            var messageBuses = new List<IMessageBus>(10);
            try {
                var countdown = new AsyncCountdownEvent(iterations * 10);
                await Run.InParallelAsync(10, async i => {
                    var bus = GetMessageBus();
                    await bus.SubscribeAsync<SimpleMessageA>(msg => {
                        Assert.Equal("Hello", msg.Data);
                        countdown.Signal();
                    });

                    messageBuses.Add(bus);
                });
                ....
		....
        
    }

        public async Task SubscribeAsync<T>(Func<T, CancellationToken, Task> handler, CancellationToken cancellationToken = default(CancellationToken)) where T : class {
            _logger.Trace("Adding subscriber for {0}.", typeof(T).FullName);
            await EnsureTopicSubscriptionAsync(cancellationToken).AnyContext();
            await SubscribeImplAsync(handler, cancellationToken).AnyContext();
        }

 protected override async Task EnsureTopicCreatedAsync(CancellationToken cancellationToken) {
            if (_topicClient != null)
                return;

            using (await _lock.LockAsync().AnyContext()) {
                if (_topicClient != null)
                    return;

                var sw = Stopwatch.StartNew();
                try {
                    var sbManagementClient = await GetManagementClient().AnyContext();
                    if (sbManagementClient != null) {
// EXCEPTIO IS THROWN HERE
                        await sbManagementClient.Topics.CreateOrUpdateAsync(_options.ResourceGroupName,
                                _options.NameSpaceName, _options.Topic, CreateTopicDescription(), cancellationToken)
                            .AnyContext();

                    }
                }
                catch (InvalidOperationException e) {
                    if (_logger.IsEnabled(LogLevel.Error)) _logger.LogError(e, "Error creating Topic Entity");
                    throw;
                }
                catch (ErrorResponseException e) {
                    if (_logger.IsEnabled(LogLevel.Error)) _logger.LogError(e, "Error creating Topic Entity");
                    throw;
                }

                _topicClient = new TopicClient(_options.ConnectionString, _options.Topic);
                sw.Stop();
                if (_logger.IsEnabled(LogLevel.Trace)) _logger.LogTrace("Ensure topic exists took {0}ms.", sw.ElapsedMilliseconds);
            }
        }

protected override async Task EnsureTopicSubscriptionAsync(CancellationToken cancellationToken) {
            if (_subscriptionClient != null)
                return;

            await EnsureTopicCreatedAsync(cancellationToken).AnyContext();

            using (await _lock.LockAsync().AnyContext()) {
                if (_subscriptionClient != null)
                    return;

                var sw = Stopwatch.StartNew();
                try {
                    var sbManagementClient = await GetManagementClient().AnyContext();
                    if (sbManagementClient != null) {
                        await sbManagementClient.Subscriptions.CreateOrUpdateAsync(_options.ResourceGroupName, _options.NameSpaceName,
                            _options.Topic, _subscriptionName, CreateSubscriptionDescription()).AnyContext();
                    }
                }
                catch (ErrorResponseException) { }

                // Look into message factory with multiple recievers so more than one connection is made and managed....
                _subscriptionClient = new SubscriptionClient(_options.ConnectionString, _options.Topic, _subscriptionName, _options.ReceiveMode, _options.SubscriptionRetryPolicy);

                // Enable prefetch to speeden up the receive rate.
                if (_options.PrefetchCount.HasValue)
                    _subscriptionClient.PrefetchCount = _options.PrefetchCount.Value;

                // these are the default values of MessageHandlerOptions
                var maxConcurrentCalls = 1;
                bool autoComplete = true;
                if (_options.MaxConcurrentCalls.HasValue)
                    maxConcurrentCalls = _options.MaxConcurrentCalls.Value;

                if (_options.AutoComplete.HasValue)
                    autoComplete = _options.AutoComplete.Value;

                _subscriptionClient.RegisterMessageHandler(OnMessageAsync, new MessageHandlerOptions(OnExceptionAsync) { MaxConcurrentCalls = maxConcurrentCalls, AutoComplete = autoComplete });
                sw.Stop();
                if (_logger.IsEnabled(LogLevel.Trace)) _logger.LogTrace("Ensure topic subscription exists took {ElapsedMilliseconds}", sw.ElapsedMilliseconds);
            }
        }

**Comment by shahbarkha** [comment]
@nemakam Hi Neeraj, Can anyone help me out on this issue?
thanks

**Comment by nemakam** [comment]
@shahbarkha 
Could you retry the operation and see if its succeeding?

**Comment by nemakam** [comment]
Since you have enabled partitions, when one of the management operations failed on one of the partitions, we have a cleanup mechanism that cleans up this state. Retrying once the cleanup is done should work. Meanwhile, you'll be getting this conflict exception.

**Comment by shahbarkha** [comment]
@nemakam Thanks Neeraj. Retrying the operation works.
