### ISSUE TITLE
Expose public constructors on exception classes, to allow mocks to throw exceptions

### ISSUE THREAD

**Issue by dshpak-iq** [Azure/azure-service-bus-dotnet#373]
## Actual Behavior
1. The exception classes `MessageLockLostException`, `MessagingEntityDisabledException`, `MessagingEntityNotFoundException`, `QuotaExceededException`, `ServiceBusTimeoutException`, and `SessionLockLostException` have no public constructors.
2. Because of this, mocks of interfaces such as `IQueueClient` cannot throw these exceptions, making it difficult to unit test code that interacts with this library.
3. Note that `ServiceBusCommunicationException` is both public and non-sealed.

## Expected Behavior
1. Exception classes have public constructors, so that the Service Bus library can be mocked out for unit-testing purposes.

## Versions  
- OS platform and version: Windows 10 Pro
- .NET Version: .NET Framework 4.6.1
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 2.0.0

**Comment by dshpak-iq** [comment]
If the team agrees with this change in principle, I'm perfectly willing to submit a pull request to make this change.

**Comment by nemakam** [comment]
I don't see any reason to keep it internal. 
@dshpak-iq , sure. Submit a PR and we can push it through..
