### ISSUE TITLE
I get the exception: "No session-id was specified for a session receiver."

### ISSUE THREAD

**Issue by kasta76** [Azure/azure-service-bus-dotnet#375]
I have an empty service bus queue with sessions enabled.
I call on the receiver side in a loop: 
await SessionClient.AcceptMessageSessionAsync(TimeSpan.FromSeconds(10));

Every 10 seconds I get an ServiceBusTimeoutException. This is OK.
But sometimes (after some minutes) i get an ServiceBusException with the text "No session-id was specified for a session receiver."
What is the problem here? I dont have specified any session ID because I want to wait for any session.
Is it a Bug?

## Versions  
- OS platform and version: Windows 10
- .NET Version: 4.6.1
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 2.0.0

Here is the complete code:
while (!cancellationToken.IsCancellationRequested)
            {
                try
                {
                    IMessageSession session = await SessionClient.AcceptMessageSessionAsync(TimeSpan.FromSeconds(10));
                    if (session != null)
                    {
                         while (messageParts.Count < nMessageParts)
                        {
                            var messages = await session.ReceiveAsync(nMessageParts - 1, SessionTimeout);
                            if (messages == null)
                                break;

                            messageParts.AddRange(messages);
                        }  

                        // Complete the messages so that it is not received again and close the session.
                        // 
                       await session.CompleteAsync(messageParts.Select(m => m.SystemProperties.LockToken));
                       await session.CloseAsync();                        
                    }
                }
                catch (ServiceBusTimeoutException)
                {
                    // No new session in time -> ignore this exception
                }
                catch (ServiceBusException ex)
                {
                    // why i get sometimes the ServiceBusException "No session-id was specified for a session receiver."? 
                }
                catch (Exception ex)
                {
                    
                }

**Comment by nemakam** [comment]
This is a transient error from the service side where a session was not successfully received. The client throws this error when the service returns "sessionID" as null. The `ServiceBusException` that you receive has `IsTransient` set to true, so it is expected that the client retries the operation.
Now its a fair point that the exception message thrown is not super clear and could be improved. I'll leave this issue open to track that. 

Also, have a couple of questions - 
1. Do you override the default retry policy? What is the retry logic that you use?
1. Did you have a session in the queue when this exception was thrown?

**Comment by kasta76** [comment]
Thank you, I will check for the IsTransient Flag and if set I will ignore such exceptions.

No, I dont have a special retry policy, I use the default.
The exception occurs when the queue is empty.

Thank you
»Kay

_______________________________________________________________
Kay Stasch
Senior Software Architect, Dipl. Inf.
[cid:image001.png@01CE65BB.073F6D10]<http://www.twitter.com/derdack>[cid:image002.png@01CE65BB.073F6D10]<http://www.linkedin.com/company/derdack-gmbh>[cid:image003.png@01CE65BB.073F6D10]<http://www.xing.com/companies/derdackgmbh>[cid:image004.png@01CE65BB.073F6D10]<https://www.facebook.com/derdack?ref=ts>[cid:image005.png@01CE65BB.073F6D10]<https://plus.google.com/103184911804052357190/posts>[cid:image006.png@01CE65BB.073F6D10]<http://www.youtube.com/user/DERDACK>­[cid:image007.png@01CE65BB.073F6D10]<http://www.derdack.com/en/resources/expert-blogs/>

Derdack GmbH
Wilhelmgalerie, Friedrich-Ebert-Strasse 8
14467 Potsdam, Germany

Derdack Corp.
4470 Cox Road, Suite 250
Glen Allen, VA 23060, USA

https://www.derdack.com<https://www.derdack.com/>

DE +49 331 29878-23, Fax +49 331 29878-22
UK +44 (20) 88167095, US +1 (202) 4700885
HRB Potsdam 13071, Managing Director: Matthes Derdack
https://www.derdack.com/imprint
_____________________________________________________________________________
Visit Derdack at the following Events:

MS Ignite: September 25-29 – Orlando, FL
Visit Derdack at Microsoft Ignite in Orlando to experience live how modern business
operations can benefit from a 10x faster anywhere incident response and resolution.
With Derdack, companies in over 50 countries automate manual communication processes
and empower operations teams to respond rapidly from anywhere. Join us at Booth #1238!
#Derdack #msignite Connect and learn more<https://www.derdack.com/visit-derdack-at-microsoft-ignite-2017/>

**Comment by nemakam** [comment]
Updated the error message.

**Comment by tsahi** [comment]
I'd like to mention that the code example at the top of this issue is just about the only example on the web for accepting messages from session queues using the Microsoft.Azure.ServiceBus SDK. Documentation should be improved.

**Comment by nemakam** [comment]
@tsahi Thanks for the suggestion. Could you please open a new issue so that it can be tracked?

**Comment by tsahi** [comment]
All right, I'll take my word back. I found [this example](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/Sessions/Program.cs), but it's not linked from the [article on sessions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions). See MicrosoftDocs/azure-docs#6348

**Comment by nemakam** [comment]
@ChristianWolf42 @sethmanheim FYI

**Comment by ChristianWolf42** [comment]
@nemakam and @tsahi, we will add links to the samples from the session article.
