### ISSUE TITLE
Do you guys have any release date for dynamically create topic using Microsoft.Azure.Management.ServiceBus 

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [Azure/azure-service-bus-dotnet#380]
I need to create azure topic & subscription programmatically (.net core). So have you guys plan to do that ? any plan release date?

**Comment by SeanFeldman** [comment]
@LilanMadusankaSilva see #65.

**Comment by SeanFeldman** [comment]
@LilanMadusankaSilva could you please close this issue in favour of #65? Thank you.

**Comment by nemakam** [comment]
Duplicate of #65
