### ISSUE TITLE
Getting Exception on ReceiveBatch(IEnumerable<Int64>)

### ISSUE THREAD

**Issue by kogot** [Azure/azure-service-bus-dotnet#381]
Hi guys,

I need to get all messages from topic->subscription, do some logic, then complete some messages.

So I'm doing:

`var brokeredMessages=  subscriptionClient.PeekBatch(index, Convert.ToInt32(batchQty))`
`//some logic`
`var seqNumbers = filteredBrokeredMessages.Select(x => x.SequenceNumber).ToList();
var recievedMessages = subscriptionClient.ReceiveBatch(seqNumbers);//getting exception here`
`foreach (var brokeredMessage in recievedMessages)
		        {
			                brokeredMessage.Complete();
		        }`
Just for testing did next:
`var seqList = new List<long>() { 13569 }; //that msg defenitelly in queue
 var rMsg = subscriptionClient.ReceiveBatch(seqList); //still exception`

`//client settings 
subscriptionClient = new SubscriptionClient.CreateFromConnectionString(
                                                                    AzureSbConnectionString, AzureSbTopic,
                                                                    AzureSbSubscription, ReceiveMode.PeekLock)`

## Actual Behavior
1. Throw exception : Failed to lock one or more specified messages as they were not deferred messages.

## Expected Behavior
1.  Receive list of brokeredMessage, for future msg.Complete() call.
2. 

## Versions  
- OS platform and version: Windows 10
- .NET Version: 4.5.2
- NuGet package version or commit ID: 4.1.6

**Comment by vinaysurya** [comment]
@kogot, ReceiveBatch API with SequenceNumbers input only works if messages were first deferred using subscriptionClient.Defer () API.  If they were not deferred using that API, then you cannot Receive them by sequence numbers. There is no way to receive messages from a subscription using sequence numbers if they were not deferred before.

Also this github is for Microsoft.Azure.ServiceBus library only. For issues related to the WindowsAzure.ServiceBus full framework library you want to file issues https://github.com/Azure/azure-service-bus/issues instead
