### ISSUE TITLE
Compatibility messages .net full and .net standard

### ISSUE THREAD

**Issue by remcoongit** [Azure/azure-service-bus-dotnet#382]
Please see https://github.com/Azure/azure-service-bus-dotnet/issues/292

I have a huge dependency on the old service bus in the full .net framework.

I cannot change the old structure and need to send/receive messages in the .net standard version.

Can someone please share code that does the serialization/deserialization so that:

.net standard version:
receive message from full .net framework (brokeredmessage)
send messages from full .net framework (brokeredmessage)

I have been looking here and searching for real working answers but none seem to work.

**Comment by remcoongit** [comment]
Receiver (.NET Standard):
var serializer = DataContractBinarySerializer< YOUR TYPE HERE >.Instance;
using (MemoryStream stream = new MemoryStream(message.Body))
{
  obj = serializer.ReadObject(stream);
}

Sender (.NET FULL):
var brokeredMessage = new BrokeredMessage(INSTANCE OF YOUR MESSAGE TYPE HERE);
client.Send(brokeredMessage);

----------------------
Sender (.NET Standard):
var serializer = DataContractBinarySerializer<ServiceBusMessageWrapper>.Instance;
byte[] data;
using (MemoryStream stream = new MemoryStream())
{
 serializer.WriteObject(stream, wrapped);
 data = stream.ToArray();
}
var message = new Message(data);
client.Send(message);

Receiver (.NET FULL):
var message = client.Receive();
message.GetBody<YOUR TYPE HERE>();

**Comment by SeanFeldman** [comment]
There's an extensive description for the scenarios [here](https://github.com/Azure/azure-service-bus-dotnet/issues/239#issuecomment-320820562) listing all permutations going back and forth.

@remcoongit FYI, there's a [`MessageInteropExtensions`](https://github.com/Azure/azure-service-bus-dotnet/blob/560ed609c9d491cc77e05018a630cc169e176aa4/src/Microsoft.Azure.ServiceBus/Extensions/MessageInterOpExtensions.cs) that helps with receiving messages from the old client (`WindowsAzure.ServiceBus`) (your 1st scenario [here](https://github.com/Azure/azure-service-bus-dotnet/issues/382#issuecomment-350747060)).

For the 2nd scenario, it depends how `WindowsAzure.ServiceBus`-based client receives messages. If it gets the body as a stream, then you don't have to do the data contract serialization.

**Comment by remcoongit** [comment]
Hi @SeanFeldman 
My reply is a working solution.

I found it after retrying. I did see the other comment but that didn't help me completely. Hence the question here.

Anyway; got the solution working. Thanks anyway!
