### ISSUE TITLE
support namespace level high availability 

### ISSUE THREAD

**Issue by michaelburch** [Azure/azure-service-bus-dotnet#384]
I need a HA solution, such a paired namespaces
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-paired-namespaces

**Comment by SeanFeldman** [comment]
Paired namespace was far from a good solution for HA to be frank. I've captured some of my thoughts about it in [my post](https://weblogs.asp.net/sfeldman/service-bus-ha-with-paired-namespaces).

**Comment by SeanFeldman** [comment]
[Availability Zones](https://azure.microsoft.com/en-us/updates/service-bus-and-event-hubs-availability-zones-now-generally-available-ga/) are now offered and intended to provide HA.

For the future, features as this are broker features and should be raised in the [server-side/service repo](https://github.com/Azure/azure-service-bus/issues) and not the client repo.
