### ISSUE TITLE
Tests are not completed due to a lengthy execution time on AppVeyor

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#387]
> Build execution time has reached the maximum allowed time for your plan (60 minutes).

Tests running for both Full Framework and .NET Standard are taking longer than 60 minutes.
Current setup is a free setup, which is limited to 60 minutes. As a result of that, builds are terminated, with failing builds (inconclusive results).

Microsoft could fix this by running on a [paid tier](https://www.appveyor.com/pricing/) and supporting  AppVeyor for their great product to allow collaboration with the community such as the one on this project.

/cc @ChristianWolf42

**Comment by vinaysurya** [comment]
@SeanFeldman, I am not sure if moving to a paid tier will automatically resolve this. It looks like in any tier the build execution time is restricted to 60 mins. We should look at what is causing the issue first or if its just the length of tests execution itself.
![image](https://user-images.githubusercontent.com/20955970/34008390-01bbddcc-e0ba-11e7-951d-b09de466bce2.png)

**Comment by SeanFeldman** [comment]
@vinaysurya renamed the title of the issue to reflect it better. Some test executions fail not because they have failing tests, but because time is exceeding 60 minutes. Unfortunately, rather than reporting an "inconclusive state", AppVeyor reports that as a failure. Will close this issue for now.

**Comment by vinaysurya** [comment]
Reopening this. Will use this issue to check in the test execution related improvement related changes
