### ISSUE TITLE
Change MessagingEntityType to internal

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#39]
Traditionally, this was limited to 4 entity types
1. Queue
1. Topic
1. Subscription
1. Filter

Entities would reside under Namespace.

With the new client, `MessagingEntityType` is adding `Namespace` as an entity. Is namespace truly an entity? Are different concerns mixed together?

**Comment by jtaubensee** [comment]
You are correct. We will remove namespace as there are not currently any management operations, and we can also make the `MessagingEntityType` enum internal.

**Comment by SeanFeldman** [comment]
👍 for internalizing the `enum`. It shouldn't be public. 
Which should be resolved with #40, eventually.

**Comment by jtaubensee** [comment]
Marking this as a bug, to change `MessagingEntityType` to internal

**Comment by jtaubensee** [comment]
Closing based on #124
