### ISSUE TITLE
Not able to retrieve single message

### ISSUE THREAD

**Issue by giorgited** [Azure/azure-service-bus-dotnet#398]
We have NET Framework 4.6.X project as well as Net Core 2.0 project. In Net Framework we are using WindowsAzure.ServiceBus to send/receive messages to/from the queue. 

Our messages were received by doing the following:
`MessagingFactory factory = MessagingFactory.CreateFromConnectionString("OurServiceBusConnectionString");`
`MessageReciever messageReciever = await factory.CreateMessageReceiverAsync("workerqueue", ReceiveMode.ReceiveAndDelete);`
`var message = await messageReceiver.ReceiveAsync(TimeSpan.FromMinutes(2));`

But in Net Core 2.0 we cant seem to find any documentation that allows us to do the same using Microsoft.Azure.ServiceBus. Only thing that we see relatively close is RegisterMessageHandler which gets invoked every time a message is received, yet we need an api that allows to get only 1 message.

**Comment by nemakam** [comment]
@giorgited 
You can find the sample [here](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveLoop)
