### ISSUE TITLE
Azure Service Bus Namespace creation via .Net 

### ISSUE THREAD

**Issue by austinarban** [Azure/azure-service-bus-dotnet#400]
We are using .Net framework 4.6.x and looking for a way to create an azure service bus namespace from the azure.management sdk. Having trouble implementing programmatically, Any reference or direct documentation would be helpful.

**Comment by nemakam** [comment]
I believe we currently do not have a standalone sample for namespace creation. We will work on adding documentation on that.
Meanwhile, to unblock yourself, take a look at [this](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.ServiceBus.Messaging/GeoDR/SBGeoDR2/SBGeoDR2/Program.cs) GEO-DR sample. It has lot more intricate details than just creating a namespace, but should work as a neat reference meanwhile.

**Comment by ravicini** [comment]
@austinarban We're creating a complete namespace including the topology with the Azure Management Fluent Libraries.

You'll find the libraries here: https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/

And here you have an example on using them: https://github.com/Azure-Samples/service-bus-dotnet-manage-queue-with-basic-features
