### ISSUE TITLE
How to maximize receive throughput?

### ISSUE THREAD

**Issue by bremnes** [Azure/azure-service-bus-dotnet#402]
## Actual Behavior
Slow receive performance on a subscription, ~20-30 messages per second.

## Expected Behavior
\> 500 msg/sec

## Questions
Are there any guides or examples on how to maximize receive throughput? When following guides and code examples we end up with really poor performance.  For instance the MS example on [receiving messages from a subscription](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions#5-receive-messages-from-the-subscription) doesn't break the 20-30 msg/s even though we increase the `MaxConcurrentCalls` property.

For .net framework there is a really good performance tool on [Azure-Samples/service-bus-dotnet-messaging-performance](https://github.com/Azure-Samples/service-bus-dotnet-messaging-performance). Is there anything similar for the .net standard client?

## Versions  
- OS platform and version: locally Windows 10, also on ACS docker linux host.
- .NET Version: .net core 2.0
- NuGet package version: Microsoft.Azure.ServiceBus v2.0.0

**Comment by jaredcnance** [comment]
To add to this, I have attempted to set `MaxConcurrentCalls = 100` and experience no difference. I may have thousands of messages en-queued for processing but every time I break on the message handler, my process has **at most** 20 threads. Changing the `MaxConcurrentCalls` to 100 has the experienced behavior as setting it to a value of 1.

**Comment by nemakam** [comment]
Could you describe details on what your setup is? 
Are you sending and receiving at the same time? 
How many subscriptions exist for the topic? 
How many rules/filters exist? 
Are you receiving 20-30 msg/s per subscription or in total?
Is this premium or standard messaging?
Are you using partitioned or non partitioned entity?

**Comment by nemakam** [comment]
@jaredcnance 
Thread count is independent of the `maxConcurrentCalls` as they spawn tasks and not threads.

**Comment by nemakam** [comment]
Could you also check if prefetch is enabled or not? 
What is the value of the prefetch?

Do you see any difference while receiving from queue v/s subscription?

**Comment by SeanFeldman** [comment]
> For .net framework there is a really good performance tool on Azure-Samples/service-bus-dotnet-messaging-performance. Is there anything similar for the .net standard client?

@nemakam perhaps having a similar sample for .net standard client would make things simpler than troubleshooting a single GH issue? It would seem to be more productive as you A) answer @bremnes's question and B) have that as a sample for others. Just my 2c 🙂

**Comment by nemakam** [comment]
@SeanFeldman Agreed. The sample for .net standard client is already being worked on. 
https://github.com/Azure-Samples/service-bus-dotnet-messaging-performance/pull/8

**Comment by binzywu** [comment]
close this for now, please reopen if otherwise.
