### ISSUE TITLE
.ToString()-method of type Message does always throw an exception

### ISSUE THREAD

**Issue by Interface007** [Azure/azure-service-bus-dotnet#407]
## Actual Behavior
1. creating a Message "msg" with or without a MessageId
2. 'msg.ToString()' throws an exception of type 'System.FormatException'

## Expected Behavior
1. creating a Message "msg" with or without a MessageId
2. 'msg.ToString()' returns a string "MessageId:[messageid-member]"

## Versions  
- OS platform and version: Windows 10 Professional
- .NET Version: 4.6.1
- NuGet package version or commit ID: 602b1fb

Current source code of method:
        public override string ToString()
        {
            return string.Format(CultureInfo.CurrentCulture, $"{{MessageId:{this.MessageId}}}");
        }

Fix would be:
        public override string ToString()
        {
            return $"{{MessageId:{this.MessageId}}}";
        }

**Comment by SeanFeldman** [comment]
Not sure `CultureInfo.CurrentCulture` should be removed. Removing string interpolation does solve the issue. Will send a PR.
