### ISSUE TITLE
Microsoft.Azure.ServiceBus - Rules Creation for Topic Subscriptions

### ISSUE THREAD

**Issue by arunkumaresan** [Azure/azure-service-bus-dotnet#413]
## Actual Behavior
1.  Creating Rules in Topic Subscription needs Topic in Enabled Mode

## Expected Behavior
1. Rules creating should be allowed when Topic Subscriptions are in Disabled mode also. Mostly preferred for business cases

## Versions  
- Microsoft.Azure.ServiceBus

**Comment by nemakam** [comment]
@arunkumaresan  Since this is a service side request, could you move this request to https://github.com/Azure/azure-service-bus ? This repo is specific to the dotnet client.
