### ISSUE TITLE
Put Token Failed when sending message 

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-service-bus-dotnet#415]
## Actual Behavior
1. Referred to this [article ](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) to try sending messages to Service Bus Queue
2. Created a new Service Bus Queue and copied SAS in Service Bus (full with Endpoint param...)
3. Received error "Put token failed" with 404 error saying the messaging entity could not be found. 

<img width="493" alt="error-message-servicebus" src="https://user-images.githubusercontent.com/12892066/35666698-99979afe-075d-11e8-9f26-b4fdeff39116.PNG">

## Expected Behavior
1. Successfully sent message to Service Bus Queue
2. Return number of messages

## Versions  
- OS platform and version: Windows 10 Pro
- .NET Version: NET Core
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 2.0.0

**Comment by nemakam** [comment]
@thuansoldier 
This is a valid response that you have received from service, which means this isn't related to the dotnet-core client, and hence not related to this repo.
The ideal place for such queries would be through filing an Azure Support ticket. 
As an exception I took a look at your namespace and there is no queue called `queu02` in that namespace. Could you check for typos?
