### ISSUE TITLE
MessageSender and MessageReceiver do not support MSI

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#416]
## Expected Behavior

To be able to send and receive messages using `MessageSender` and `MessageReceiver`.

## Actual Behavior

Constractors of `MessageSender` and `MessageReceiver` do not support an overload that takes `ITokenProvider` like Queue/Subscription clients do.

While it's possible to workaround this issue, having entity type agnostic senders/receivers is important for libraries extending ASB.

**Comment by nemakam** [comment]
WIP #396

**Comment by SeanFeldman** [comment]
Now that PR #396 is merged into `dev`, this can be closed @nemakam

**Comment by nemakam** [comment]
Thanks @SeanFeldman
