### ISSUE TITLE
Fluent Client doesnt return proper values on Update

### ISSUE THREAD

**Issue by arunkumaresan** [Azure/azure-service-bus-dotnet#418]
The following properties of _QueueInner_ are returned _null_ on CreateOrUpdateAsync
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.servicebus.fluent.queuesoperationsextensions.createorupdateasync?view=azure-dotnet

## Actual Behavior
1. CountDetails = null
2. AccessedAt = null
3. CreatedAt = null
4. UpdateAt = null

## Expected Behavior
1. CountDetails = MessageCountDetails https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.servicebus.fluent.models.messagecountdetails?view=azure-dotnet
2. AccessedAt = DateTime
3. CreatedAt = DateTime
4. UpdateAt = DateTime

## Versions  
Assembly Microsoft.Azure.Management.ServiceBus.Fluent, Version=1.0.0.60, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Comment by SeanFeldman** [comment]
@arunkumaresan wouldn't it be better to raise this issue against the repo the package belongs to (https://github.com/Azure/azure-libraries-for-net/)?

**Comment by arunkumaresan** [comment]
@SeanFeldman Thanks for the direction. But, How to know which repo to write to. Last time when I raised some queries, they directed me to raise the issues related to dotnet clients here.

**Comment by SeanFeldman** [comment]
The client is definitely not the one that would have this code to be fixed. I'd start from the management client and if that team thinks it's an asb issue, raise a broker related issue in https://github.com/Azure/azure-service-bus/issues

**Comment by arunkumaresan** [comment]
There is no repo for management. I will raise it in azure-service-bus and hope to get answer. Thanks @SeanFeldman
