### ISSUE TITLE
Send-Via feature is missing

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#423]
With [Transactions support](https://github.com/Azure/azure-service-bus-dotnet/issues/6) in place (PR #421), `send-via` is missing to allow trasport transaction with source and destination be on the different queues (see https://github.com/Azure/azure-service-bus-dotnet/issues/6#issuecomment-366082384).

**Comment by jtaubensee** [comment]
👍  for `Send-Via` transaction support!  Sending a message to a different entity within a transaction is one of the primary reasons that I would want to use transactions in the first place. I personally, think that its not too common to send a message to the same entity that a message was just completed on (i.e. the example in #421).

**Comment by SeanFeldman** [comment]
Same here. 99% of my customers rely on transaction with send-via. This would make them so happy 🙂

**Comment by mindraptor** [comment]
I would like to add my vote to the Send-Via transaction support!
We are a customer of Sean and cannot move to .Net Core until this feature is implemented. Thank you.

**Comment by ChristianWolf42** [comment]
Hi All, we are currently working on releasing this feature. It should come in the next 2-3 month if we don't face unexpected delays.

**Comment by SeanFeldman** [comment]
:tada:
