### ISSUE TITLE
Support for RPC (request/response) pattern?

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-service-bus-dotnet#428]
Does this library have support for request/response patterns, where a specific client sends a request and then waits for a response?

I had initially thought of having the client create a randomly named, auto-deleting queue, and have the other end reply using that queue - but this library [doesn't support creating queues](https://github.com/Azure/azure-service-bus-dotnet/issues/65) (incredibly odd for a message bus library, but never mind!).

**Comment by nemakam** [comment]
@cocowalla 
If request-response is what you need, there are multiple things you can try (in descending order of my opinion)
1. Creating two permanent queues, one for request and one for response.
2. If the rate of message is slow, then you can re use the same queue and send a requestID as `message.MessageID` and then during response you can set `message.CorrelationID` as the previous messageID which helps you correlate things. 
3. Use different sessions instead of two different queues.

If you are interested in creating queues etc, you can keep an eye on #65.

**Comment by cocowalla** [comment]
@nemakam there will be a slow message rate, but there will be a lot of clients, and it's important the correct response goes to the correct sender - which I guess rules out both 1 and 2.

Regarding 3, yes, different sessions might work... but from a security perspective, is guessing the session ID the only thing standing in the way of reading another sender's responses?

**Comment by cocowalla** [comment]
@nemakam so I just tried to get this working with sessions, and hit a problem:

1. Client sends sessionful message
2. Server attaches to the next available session
3. Server receives the client's message
4. Server sends a response
5. Client tries to receive the response <-- KABOOM!

> `The requested session '80a763dd5ee14bad958f7613675dd229' cannot be accepted. It may be locked by another receiver.`

This happens, even if the server closes its receiver before it sends its response - a sort of race condition, it seems.

The server-side receiver is of course st

**Comment by nemakam** [comment]
@cocowalla 
>  The requested session '80a763dd5ee14bad958f7613675dd229' cannot be accepted. It may be locked by another receiver.

Are you facing this consistently or happened once? I'd still say you should check your code again for race conditions as we haven't seen any race condition in this path.
Can you provide a sample code on how you are using this?

**Comment by cocowalla** [comment]
@nemakam it was happening more times than not.

I did manage to get it working though, but by using _2_ different sessions:

1. Client generates a unique value to use as the response session - let's call it `replySessionId`
2. Client sends sessionful message, specifying the `ReplyToGroupId` property as `replySessionId`
3. Server attaches to the next available session
4. Server receives the client's request message
5. Server sends a response, setting the `GroupId` property to the value of the `ReplyToGroupId` of the client's request
6. Client receives the response using the session defined by `replySessionId`

Not sure if that's what I'm meant to be doing, but it seems to work.

I'm still left curious about security though - is the security of this method based only on the randomness of the session ID? Is there a maximum length for session ID?

**Comment by nemakam** [comment]
@cocowalla 
> Regarding 3, yes, different sessions might work... but from a security perspective, is guessing the session ID the only thing standing in the way of reading another sender's responses?

If you are interested in security/multiple receivers, then there are some other things you could consider. 
Security policy can currently be applied to Queues/Topics. Applying it to topic-subscription level is on the way. 
So you could use a topic and create a subscription for each receiver and add rules on the topic such that messages are forwarded to the right subscription. 
The client always receives from its assigned subscription. 

How many clients do you have?

**Comment by cocowalla** [comment]
@nemakam hah, I was just reading [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas) that you can issue SAS tokens that apply at the subscription level, and was thinking that may be a good way to simplify and secure!

Not sure how many clients we will have yet - probably up to 500 very soon after going into production, and hopefully ramping up to 5000 within a year after that.

**Comment by nemakam** [comment]
@cocowalla 
5000 subscriptions is not something that will work with service bus. The current limit is 2000 subscriptions. So be wary of that when you are designing your application. To have optimal performance I would recommend having fewer subscriptions that the upper limit.

**Comment by cocowalla** [comment]
@nemakam ah crap, I hadn't seem that limit on the limitations page. It does seem like a pretty major disadvantage... what to do if you have more that 2k clients? 

It strikes me that the only way to scale Azure Service Bus is by having multiple namespaces, which is especially problematic if you have a single tenant with more than 2k clients (an ambition, sure, but still).

**Comment by cocowalla** [comment]
@nemakam Sure. We are creating a multi-tenant SaaS system. Each tenant will run a daemon/service on a subset of their servers and/or workstations. These daemons will send data to an Azure Event Hub. They will also send and receive 'control' messages to/from Azure Service Bus - this will be for initial registration (request/response), heartbeat messages (publish), configuration changes (subscribe) etc.

Each tenant could have anywhere between 5 and 5000 clients. Obligatory ASCII diagram:

```
+-------------------+              +-------------------+
| Tenant 1 of many  |    HTTPS     | SAS Token Issuing |
|                   <-------------->      Web API      |
| +--------------+  |              +-------------------+
| |    Daemon    |  |
| +--------------+  |    AMQPS     +-------------------+
| +--------------+  <--------------> Azure Service Bus |
| |    Daemon    |  |              +-------------------+
| +--------------+  |
|       ...         |    AMQPS     +-------------------+
|                   +-------------->  Azure Event Hub  |
+-------------------+              +-------------------+

```

**Comment by nemakam** [comment]
@cocowalla 
Thanks for this explanation. Could you also provide details on throughput that you expect? As a simplistic measure, how many messages would you have per second per client? 

Designing the solution will need to consider throughput. If you have one entity on the namespace, you will have higher throughput, and as and when you add more entities, the throughput per entity might reduce. Topic-Subscription might provide good density, but might have slower throughput especially when you plan to have 1000s of filters.

**Comment by cocowalla** [comment]
@nemakam 
The vast majority of the data will be going to Event Hubs, but let's put that aside for now.

The clients will be sending and receiving very few messages through Service Bus - less than 1 message per second, maybe 1,500 messages per _day_.

Also, it feels like you're going above and beyond for me here, so just wanted to say thanks for your help so far!

**Comment by JamesBirdsall** [comment]
Have you looked at Azure's IoT offerings? It's intended for "devices" but based on your description each of your tenants behaves a lot like a device: you want bulk telemetry from the tenants to a central location, and then a command and control channel to each tenant, right? That is pretty much exactly what IoT offers, built on top of event hubs and service bus so they have already solved the problems you're encountering. Caveat: I don't know the deep details of IoT so there may be subtleties which mean it's not what you need, but I think it would be worth looking.

**Comment by cocowalla** [comment]
@JamesBirdsall no, I hadn't - when I think IoT, I think of tiny embedded devices running factories :)

We will have an on-prem version built on RabbitMQ, so we'd like to keep everything using AMQP if possible, and it seems that would work with IoT Hub.

After a brief look, you seem to right about the requirements matching IoT Hub capabilities - we need bulk telemetry from clients (Event Hub), with a command and control channel to each client (Service Bus) - so I now have even more research to do!

**Comment by FSou1** [comment]
Are there any updates?

Once I need to implement a request/reply pattern with ServiceBus (and probably amqp), what are my options?
