### ISSUE TITLE
Prefix environment variables with project specific identifier

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#43]
Given that one can work on multiple projects that require environment variable, would be nice to have env variables that are easier to identify. This is my environment variables (not the full list) and ASB client project`s env variable is just lost.

![image](https://cloud.githubusercontent.com/assets/1309622/21289117/c10389e0-c451-11e6-9419-1379d7678a09.png)

What if `ConnectionStringEnvironmentVariable` 
would be `azure-service-bus-dotnet/ConnectionString`?

In addition to that, the `EnvironmentVariable` suffix for an environment variable is not needed. Save bytes, save the world.

### Correction
Environment variable is called `SERVICEBUSCONNECTIONSTRING`. Exception thrown is PR #41 is misleading. Proposal is still valid. Instead of `SERVICEBUSCONNECTIONSTRING` call it `azure-service-bus-dotnet/ConnectionString`.

**Comment by jtaubensee** [comment]
closing as part of #41
