### ISSUE TITLE
Create new topic / queue / subscription from code using Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by niranjanbohra** [Azure/azure-service-bus-dotnet#430]
## Actual Behavior
1. Using Microsoft.ServiceBus nuget, we can create and check if it exists but there is not way to do same using Microsoft.Azure.ServiceBus nuget.

## Expected Behavior
1. We would like to create using SDK.

## Versions  
- OS platform and version: win10
- .NET Version: 4.7.1
- NuGet package version or commit ID: latest

**Comment by SeanFeldman** [comment]
Duplicate of #65.
Specifically, look at https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-338874419.
If you require this functionality, please chime on #65.
