### ISSUE TITLE
Inline documentation: Documentation on OnMessageAsync is insufficient

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-service-bus-dotnet#431]
This is a reference doc issue that requires a change to the underlying `///` comments.

From @sriramva (https://github.com/Azure/azure-docs-sdk-dotnet/issues/325):

> There is a nuance to this method that I did not catch Some remarks should help.
> 
> The delegate set with OnMessageAsync needs to be quick at going to a awaited state, or quick to complete. If the method has a of synchronous stuff it does before it goes to a awaited state, the subsequent messages are not picked up from servicebus until the thread really goes to the awaited state. Hence, in the worst case, serializing the handling of the messages to one at a time.

cc: @sethmanheim

**Comment by nemakam** [comment]
@sriramva
OnMessageAsync is expected to wait for your method (irrespective of sync or async) to finish before next message is retrieved. To increase parallelism, use the `Options` where you will have `MaxConcurrentCalls`. 
The nuance you are describing is not an expected behavior.
