### ISSUE TITLE
Exception when using Microsoft.Azure.Amqp 2.2

### ISSUE THREAD

**Issue by tsahi** [Azure/azure-service-bus-dotnet#432]
## Steps to reproduce
1. Install Microsoft.Azure.ServiceBus package. the package depends on  Microsoft.Azure.Amqp (>= 2.1.2), so version 2.1.2 is installed.
2. since the latest version of  Microsoft.Azure.Amqp is 2.2, upgrade it to this version
3. write code to send a message to a queue, and execute. I followed roughly [this tutorial](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues).
## Actual Behavior
An exception is thrown from the `queueClient = new QueueClient(ServiceBusConnectionString, QueueName);` line (in my case it was in a class library called from an Azure Function, but other than that it was essentially the same). Message text is: "Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.":"Microsoft.Azure.Amqp, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
## Expected Behavior
Message should be sent without errors

## Versions  
- OS platform and version: Windows 10 Enterprise
- .NET Version: 4.6.1
- NuGet package version or commit ID: 2.0.0

**Comment by SeanFeldman** [comment]
Looks like NuGet is misleading.
Version 2.0.0 of Microsoft.Azure.ServiceBus client is locked to use Microsoft.Azure.Amqp version 2.1.3 ([see project file](https://github.com/Azure/azure-service-bus-dotnet/blob/b44265e233c9d950035a749c1a2f55600398fc26/src/Microsoft.Azure.ServiceBus/Microsoft.Azure.ServiceBus.csproj#L33)). 

Have you tried binding redirect?

@Azure/azure-service-bus-write is that a intent to lock against specific version or should there be a range?

**Comment by nemakam** [comment]
That should be a range. This will have to be fixed.

**Comment by tsahi** [comment]
No, I havn't tried redirect. I'll try next week.

**Comment by SeanFeldman** [comment]
It was pointed out to me that the csproj and nuget info are matching.
`Version="2.1.3"` should translate into `version >= 2.1.3`.

Range would make sense if the dependency is following SemVer and any major version can introduce breaking changes. Therefore any major should be tested first. Hence the range 
`Version="[2.1.3, 3.0.0)`. Otherwise it's not needed.

**Comment by tsahi** [comment]
Well, while the app.config of the library where this is implemented has this piece of XML:
```xml
<dependentAssembly>
  <assemblyIdentity name="Microsoft.Azure.Amqp" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
</dependentAssembly>
```
under the `<runtime>` element, this is a library used by an Azure Function, which doesn't support app.config. It has local.settings.json file, which isn't even deployed. You're suppose to add your key-value settings separately to the deployed function. So there is no way I know of to do binding redirect in an Azure Function. See also Azure/azure-functions-host#992

**Comment by SeanFeldman** [comment]
@nemakam could you please update the `Milestone` to indicate what version would have this fixed? Thanks.

**Comment by Fredborg** [comment]
When is this fixed?

**Comment by nemakam** [comment]
@Fredborg  Will release 3.0 next week.
