### ISSUE TITLE
Tracking dependencies changes

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#435]
The client library has a few dependencies that are constrained to a specific version a range.
For libraries following SemVer, a major version bump might indicate breaking changes.
Need a way to get notified about dependency library updates to test and release updates to this client.

**Comment by ChristianWolf42** [comment]
@SeanFeldman Wouldn't our new branching strategy we discussed in issue 224 together with the release notes suffice?

**Comment by SeanFeldman** [comment]
This was a different issue. See PR that fixed this issue.

**Comment by ChristianWolf42** [comment]
@SeanFeldman I see, closing this one then.
