### ISSUE TITLE
Subscription Client RemoveRuleAsync sporadic exceptions

### ISSUE THREAD

**Issue by vigneshmsft** [Azure/azure-service-bus-dotnet#442]
I have the below code to create a subscription client.
```

  _subscriptionClient = new SubscriptionClient(connectionString, topicName, subscriptionName, retryPolicy: RetryPolicy);

  await _subscriptionClient.RemoveRuleAsync(RuleDescription.DefaultRuleName);
  await _subscriptionClient.AddRuleAsync(new RuleDescription(RuleDescription.DefaultRuleName, new TrueFilter()));
```

But I receive the below exception every now and then when trying to initialize my application

>  The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:cd159554-32b2-48a6-81a3-e2202b239779, TrackingId:165a83c5-64b1-43ca-b914-98a99c9ab51a_G18, SystemTracker:NoSystemTracker, Timestamp:4/14/2018 8:23:23 PM

and the below stack trace

> Microsoft.Azure.ServiceBus.Amqp.AmqpSubscriptionClient+<OnRemoveRuleAsync>d__27.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification Microsoft.Azure.ServiceBus.SubscriptionClient+<RemoveRuleAsync>d__53.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification Xxxx.Messaging.AzureServiceBus.AzureEventSubscription+<CreateSubscriptionClient>d__5.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification Xxxx.Messaging.AzureServiceBus.AzureEventSubscription..ctor Xxx.XxxxxxxxXxxxxxxx.Startup.<RegisterXxxxxxxxxxxEventBus>b__15_0 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite lambda_method Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices Xxxx.Xxxxxxx.Controllers.XxxxController.Xxxxx lambda_method Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification System.Runtime.CompilerServices.TaskAwaiter.GetResult Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification System.Runtime.CompilerServices.TaskAwaiter.GetResult Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification System.Runtime.CompilerServices.TaskAwaiter.GetResult Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification System.Runtime.CompilerServices.TaskAwaiter.GetResult Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification System.Runtime.CompilerServices.TaskAwaiter.GetResult Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__7.MoveNext System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification XXXX.Middleware.ExceptionLoggerMiddleware+<InvokeAsync>d__2.MoveNext

Microsoft.Azure.ServiceBus version 2.0.0
Microsoft.Azure.Management.ServiceBus 1.2.0

I can see this has been raised few time earlier and fixed in the past, but it is not working.

**Comment by nemakam** [comment]
This is not a client related issue. Please raise a support request and someone will take a look at it for you. Closing this issue.

**Comment by Eneuman** [comment]
Did you ever find out what the problem was?
We have the same problem.

**Comment by deus42** [comment]
Same here, any hints or ideas?
