### ISSUE TITLE
Include TryReceive and TryReceiveAsync methods in IMessageReceiver

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-service-bus-dotnet#443]
@nisubr commented on [Fri Apr 06 2018](https://github.com/Azure/azure-docs-sdk-dotnet/issues/571)

Please provide the following methods in IMessageReceiver:
```
bool TryReceive(out Message msg, TimeSpan timeout)
Task<bool> TryReceiveAsync(out Message msg, TimeSpan timeout)
```
So that we can use these like:
```
if (TryReceive(out Message msg, TimeSpan.FromSeconds(30))
{
    ...
}
else
{
    ...
}
```

**Comment by nemakam** [comment]
@CamSoper 
This is just a syntactic sugar right? Any other reason for this request?
Also, we do not plan to support sync calls as of now.

**Comment by nemakam** [comment]
The above question is for @nisubr

**Comment by CamSoper** [comment]
@nemakam Beat me to it. 🙂

**Comment by SeanFeldman** [comment]
> Also, we do not plan to support sync calls as of now.

You already do! `OperationAsync().GetAwaiter().GetResult()`

Jokes aside, an entirely IO-centric library shouldn't really cater for synchronous code.

**Comment by nemakam** [comment]
Closing as there is no response and is just a syntactic sugar.
