### ISSUE TITLE
QueueClient.ScheduleMessageAsync in high traffic does not working as expected

### ISSUE THREAD

**Issue by sygnowskip** [Azure/azure-service-bus-dotnet#447]
Hi, 
I have a little problem with QueueClient.ScheduleMessageAsync method (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.queueclient.schedulemessageasync?view=azure-dotnet)

In low traffic or test cases it working exactly as expected. But when traffic are high, some of the execution of ScheduleMessageAsync does not schedule message to Azure Service Bus. 

What are the symptoms of that? 
Some of "scheduled" message are missing on Azure Service Bus, returned `sequenceNumber` is 0, no exception appeared and enqueuing a message takes as long as operation timeout is set on QueueClient. I also wanted to add, that my QueueClient is shared through multiple threads, because I wanted to avoid creating multiple clients per seconds (maybe this is the root cause of the issue?).

I cannot find any information in documentation what does it means and what should I do in that case - should I just try to execute this method again? Or how can I fix that?

## Versions  
- OS platform and version: Windows 7 / Azure Service Fabric
- .NET Version: .NET 4.6.1
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus@2.0.0

**Comment by nemakam** [comment]
@sygnowskip 
What is the rate of messages being scheduled?
Is this a partitioned entity or a non partitioned entity?
And do you need the sequenceNumber back? If not, you could use the other alternative which is call `queueclient.send` and set the `scheduledEnqueueTimeUtc` in that message. The difference between the two methods from a user perspective is that `ScheduleMessageAsync` also returns the sequence number in case you need it for cancelling it. If not, then i'd recommend sending normal messages with the property set.

**Comment by sygnowskip** [comment]
@nemakam thanks for help :smiley: 
I did change method from `QueueClient.ScheduleMessageAsync` to `QueueClient.SendAsync` and it's working as expected, even with higher traffic. I didn't know that `QueueClient.SendAsync` allows to scheduling messages, thanks!

What I mean as a "high traffic" in our case is about 500 scheduled messages per minute, on partitioning queue.

**Comment by SeanFeldman** [comment]
@nemakam should rate? I'd fully expect `ScheduleMessageAsync()` to succeed just as `SendAsync(message with ScheduledEnqueueTimeUtc)` would. If `SequenceNumber` is needed upon scheduling, `SendAsync()` is not an option.

**Comment by nemakam** [comment]
@SeanFeldman 
Yes. Both of them should succeed. Regarding the performance, ideally both should have similar performance but since send() goes through normal AMQP link, and `ScheduleMessageAsync()` goes through a request response link, there could be a difference. Based on how AMQP 1.0 protocol works, it is difficult to return a response for a send() operation. It is a one way streaming protocol. This additional perf hit comes while taking care of this.
That said, 500 msgs per minute is a very small number for an AMQP link, and it is something that should definitely be supported in both the cases.

**Comment by SeanFeldman** [comment]
@sygnowskip did you close the issue because you got `ScheduleMessageAsync()` to work or because you've switched to `SendAsync(message with ScheduledEnqueueTimeUtc)`?
