### ISSUE TITLE
Closing MessageReceiver doesn't wait for current processing message to finish

### ISSUE THREAD

**Issue by qetza** [Azure/azure-service-bus-dotnet#448]
## Actual Behavior
1. Calling CloseAsync on a QueueClient or SubscriptionClient will close the underlying connection even though messages are being processed by the handler
2. When the handler finishes exception are thrown because object is closed and messages cannot be completed

## Expected Behavior
1. Calling CloseAsync should stop receiving messages and wait for current message processing to be finished

## Versions  
- OS platform and version: Windows
- .NET Version: 4.6
- NuGet package version or commit ID: 2.0.0

**Comment by nemakam** [comment]
> Calling CloseAsync should stop receiving messages

This is already the way it works.

> and wait for current message processing to be finished

This isnt ideal as message processing can take seconds to maybe even days. Close shouldn't wait for the message processing to be finished. The alternative, which again exists, is the `CancellationToken` that is passed to the handler. Check whether the token is cancelled or not before attempting to complete the message. The token is cancelled the moment closeAsync() is invoked. 

Reopen the issue if you have concerns.
