### ISSUE TITLE
BUG: System.TimeoutException is NOT retried by RetryPolicy.

### ISSUE THREAD

**Issue by rossdempster** [Azure/azure-service-bus-dotnet#449]
## Actual Behavior
I am getting frequent intermittent dropped messages with errors of the form "System.TimeoutException: The operation did not complete within the allocated time 00:00:59.9999930 for object request2." when attempting to post to the service bus.

I have a RetryExponential policy configured with a maximum backoff of 5 minutes. As best I can tell, my policy is not being honoured and I'm losing these messages.

## Expected Behavior
Configured RetryPolicy should apply for timeouts.

## Versions  
- .NET Version: .NET Core 2.0.1
- NuGet Package: Microsoft.Azure.ServiceBus  2.0.0

**Comment by nemakam** [comment]
The retry policy has an upper limit of `OperationTimeout` which is set on the `MessageSender` / `ServiceBusConnection`.
Try increasing that value. 
The retry policy honors the max operation timeout that has been specified.

Reopen the issue if it doesn't solve your problem
