### ISSUE TITLE
ArgumentNullException in ServiceBusDiagnosticSource.SetTags after updating to 3.0.0

### ISSUE THREAD

**Issue by frankbuckley** [Azure/azure-service-bus-dotnet#459]
Since upgrading to version 3.0.0 we are seeing exceptions thrown from the message receiver

    System.ArgumentNullException: Value cannot be null.
    Parameter name: source
    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
    at Microsoft.Azure.ServiceBus.ServiceBusDiagnosticSource.SetTags(Activity activity, IList`1 messageList) in C:\Repos\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\ServiceBusDiagnosticsSource.cs:line 742
    at Microsoft.Azure.ServiceBus.ServiceBusDiagnosticSource.ReceiveStop(Activity activity, Int32 messageCount, Nullable`1 status, IList`1 messageList) in C:\Repos\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\ServiceBusDiagnosticsSource.cs:line 227
    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout) in C:\Repos\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 393
    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout) in C:\Repos\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 323
    at Microsoft.Azure.ServiceBus.MessageReceivePump.MessagePumpTaskAsync() in C:\Repos\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\MessageReceivePump.cs:line 64

## Actual Behavior
1. Message receiver throws exceptions 

## Expected Behavior
1. Message receiver does not throw exceptions

### OS platform and version / .NET Version:

	.NET Core SDK (reflecting any global.json):
	 Version:   2.1.300-rc1-008673
	 Commit:    f5e3ddbe73

	Runtime Environment:
	 OS Name:     Windows
	 OS Version:  10.0.17134
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

	Host (useful for support):
	  Version: 2.1.0-rc1
	  Commit:  eb9bc92051

	.NET Core SDKs installed:
	  1.0.4 [C:\Program Files\dotnet\sdk]
	  1.1.0 [C:\Program Files\dotnet\sdk]
	  2.0.0 [C:\Program Files\dotnet\sdk]
	  2.0.2 [C:\Program Files\dotnet\sdk]
	  2.0.3 [C:\Program Files\dotnet\sdk]
	  2.1.2 [C:\Program Files\dotnet\sdk]
	  2.1.3 [C:\Program Files\dotnet\sdk]
	  2.1.4 [C:\Program Files\dotnet\sdk]
	  2.1.100 [C:\Program Files\dotnet\sdk]
	  2.1.101 [C:\Program Files\dotnet\sdk]
	  2.1.102 [C:\Program Files\dotnet\sdk]
	  2.1.103 [C:\Program Files\dotnet\sdk]
	  2.1.104 [C:\Program Files\dotnet\sdk]
	  2.1.105 [C:\Program Files\dotnet\sdk]
	  2.1.200-preview-007589 [C:\Program Files\dotnet\sdk]
	  2.1.200-preview-007597 [C:\Program Files\dotnet\sdk]
	  2.1.200 [C:\Program Files\dotnet\sdk]
	  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

	.NET Core runtimes installed:
	  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Also seen in container based on `microsoft/dotnet:2.1-aspnetcore-runtime-bionic`

### NuGet package version or commit ID:

3.0.0

**Comment by nemenos** [comment]
Same happens for me... lots and lots of exception.
After upgrading to 3.0.0 also old topics, only used by old version, started to throw!

**Comment by nemakam** [comment]
@frankbuckley @nemenos  Do you have AppInsights enabled on your service?

**Comment by nemakam** [comment]
@nemenos Yes, this looks like not a real error, and a null exception in the diagnostic path (which gets triggered when app insights is enabled, and there are no messages received). Will fix this soon...
@SeanFeldman This was opened before #460 :)

**Comment by frankbuckley** [comment]
@nemakam Yes.

**Comment by nemakam** [comment]
I'll work on releasing the fix soon. Meanwhile, I'd recommend ignoring the error if you cannot disable app insights..
