### ISSUE TITLE
Ability to purge a queue

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#46]
There are scenarios where purging a queue is necessary
- Testing scenarios
- Removing all messages because they are no longer needed
- Clearing out deferred messages when sequence numbers are no longer retained by an app

Similar functionality: [ASQ`s CloudQueue.ClearAsync()](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.queue.cloudqueue.clearasync.aspx).

This would apply to both queue/subscription and associated DLQs.

**Comment by jtaubensee** [comment]
This is something we can revisit in the future. We currently have an internal project that would make this much easier for us. The project will manage state against partitions.

**Comment by SeanFeldman** [comment]
> We currently have an internal project that would make this much easier for us.

Where's the OSS community in "us" when it's internal? Sharing is carrying, right? 😃

**Comment by jtaubensee** [comment]
The project I am referring to is for our cluster management. It will simplify transactions across shards, allowing us to better ensure that messages have been purged from all.

**Comment by jtaubensee** [comment]
This issue was moved to Azure/azure-service-bus#1
