### ISSUE TITLE
MSI - Management Operations

### ISSUE THREAD

**Issue by grik001** [Azure/azure-service-bus-dotnet#462]
Hi,

Is it possible to manage Topics, Queues etc using MSI, If yes are any Samples available?

From some research, it seems that this is still under development correct and will will it support MSI?

**Comment by grik001** [comment]
Hey Sean, yes I think I must have worded my question incorrectly. To Clarify what I am asking is if Managment Operations are possible using MSI Authentication.

And yes, my goal is to eliminate all form of passwords from my configs.

**Comment by SeanFeldman** [comment]
If your application that is using the ASB client is authorized to work against ASB namespace, then yes.

The question is about client and if it's capable of performing managing operations. This client (.NET Standard client) **as of today** cannot do that. MSI or not. Once management operations API is added, the scenario will be possible.

**Comment by nemakam** [comment]
@SeanFeldman has answered it all! 
1. #65 can be used to tracked management operations support
2. Once it is supported, you will be able to use MSI to do management operations. 

Closing this thread since we already have #65.
