### ISSUE TITLE
The receiver cannot continue to accept new messages after running for a period of time

### ISSUE THREAD

**Issue by Itoktsnhc** [Azure/azure-service-bus-dotnet#463]
## Actual Behavior

The receiver cannot continue to accept new messages after running for a period of time

As shown in the figure, the receiver cannot continue to accept the messages in the queue after running for a period of time. The OnJobItemMessageHandler() method cannot be executed as expected, it does not occupy the CPU, and the memory usage is stable

## Expected Behavior

The receiver should be able to continue accepting new messages

## Versions  
- OS platform and version: windows 10 x64 1803 17134.48
- .NET Version: .net core 2.0
- NuGet package version or commit ID: 3.0.0

![image](https://user-images.githubusercontent.com/11204672/40202090-897f1d10-5a53-11e8-937a-731d1c06a17a.png)

Demo which can reproduce this issue: 
[ServicebusFrezeReceive.zip](https://github.com/Azure/azure-service-bus-dotnet/files/2014648/ServicebusFrezeReceive.zip)

**Comment by nemakam** [comment]
In your code, you are not using ExceptionHandler.
Could you log all the exceptions that you are receiving and share it?

**Comment by Itoktsnhc** [comment]
@nemakam  no message in ExceptionHandler

**Comment by nemakam** [comment]
> The receiver cannot continue to accept new messages after running for a period of time
What is the time period here?

**Comment by nemakam** [comment]
We have tests running that run for 24 hours and hasn't shown this behavior. 
Do you see this behavior only on dev machine or on production as well?
And how consistently can you reproduce this issue?

**Comment by Itoktsnhc** [comment]
sorry my fault.
need some init msgs in queue , like this
![image](https://user-images.githubusercontent.com/11204672/40571561-5ecfd61a-60cd-11e8-9696-bd7d16cc1094.png)
updated gist
https://gist.github.com/Itoktsnhc/088157c4abea5e9053fa273c04a64ab8
and the            
` Console.WriteLine($"Received Msg {count}");` in line https://gist.github.com/Itoktsnhc/088157c4abea5e9053fa273c04a64ab8#file-program-cs-L48
will stop print  “ Received Msg {count} ” after receiver about 5500~ msg。
memory usage and cpu useage are stable

**Comment by nemakam** [comment]
@Itoktsnhc 
1. You still aren't logging ExceptionHandler.
2. You aren't completing all messages. That can definitely lead to this issue. Please complete all messages (or abandon it).

**Comment by Itoktsnhc** [comment]
@nemakam 
1.  updated Debugger.Break();
2. Machine failures, network failures, or operating system failures can make the program unable to perform Abandon or Complete correctly, or the purpose is not to Abandon or Complete messages, or to wait until LockToken expires. Or is there any rule that prompts the receiver not to get a new message when the number of incorrect Abandon or Complete messages reaches a certain number?

**Comment by nemakam** [comment]
@Itoktsnhc 
Take a look at https://github.com/Azure/azure-service-bus-dotnet/issues/470#issuecomment-392160900

**Comment by Itoktsnhc** [comment]
@nemakam   

Ok I see。Thanks for the update. I will consider the options
