### ISSUE TITLE
System.IdentityModel.Tokens.Jwt 5.0+

### ISSUE THREAD

**Issue by rokonec** [Azure/azure-service-bus-dotnet#464]
## Actual Behavior
1. Using Microsoft.Azure.ServiceBus >=3.0.0 on ASP.NET 4 (not net.core) is not possible as System.IdentityModel.Tokens.Jwt 5.0+ has breaking changes and is basically Core only.  See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/327

So this makes Microsoft.Azure.ServiceBus no longer net-standard - if I understand it correctly.

## Expected Behavior
1. If possible reference System.IdentityModel.Tokens.Jwt <5.0.0

## Versions  
- OS platform and version: Windows 10
- .NET Version: 4.7
- NuGet package version or commit ID: 3.0.0

**Comment by serkantkaraca** [comment]
I am not able to reproduce the issue. I built an app with Microsoft.Azure.ServiceBus 3.0.0 and System.IdentityModel  .Net 4.0. It builds and send messages to a queue just fine.

Can you please provide more details where you are observing the conflict? At the build or the runtime? If  possible, can you provide a small sample project that fails?

**Comment by nemakam** [comment]
Reopen if still facing issue...

**Comment by rokonec** [comment]
I am not sure I explained this issue correctly.
Microsoft.Azure.ServiceBus >=3.0.0 has dependency on System.IdentityModel.Tokens.Jwt (>= 5.2.2 && < 6.0.0)

System.IdentityModel.Tokens.Jwt >= 5.0 is core only as stated for example here: 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
https://community.auth0.com/t/webapi-owin-example-is-not-working/9704
https://github.com/IdentityServer/IdentityServer3/issues/3017

So, If package of Microsoft.Azure.ServiceBus is upgraded to the newest version it makes hosted process ASP.NET core only (OWIN 3).  If something is core specific it is no longer .net standard. Am I correct?

The way System.IdentityModel.Tokens.Jwt handle it is that they branch/fork packages and making parallel released into version 5 and 4 as you can see here https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/

I don't like that approach at all and whoever made the decision to make System.IdentityModel.Tokens.Jwt >= 5.0 core only (as opposed to new package name) is probably regretting this decision now (as do I), but the question is how to live with it.

I don't know how many breaking changes are there but I am currently struggling with TokenValidationParameters.IssuerSigningKeyResolver signature change.

Any idea?

**Comment by SeanFeldman** [comment]
> System.IdentityModel.Tokens.Jwt >= 5.0 is core only

Looking at [5.2.4](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/5.2.4), it supports **.NET Standard 1.4**. Therefore ASB package can be used with anything that supports 1.4 Standard.
