### ISSUE TITLE
SemVer non-complient version number

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#467]
Latest release (3.0.1) has generated a version that is not SemVer complient - [3.0.1.16](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/3.0.1.16).
/cc @nemakam

**Comment by SeanFeldman** [comment]
@geekcubed repo for Microsoft.Azure.Amqp is https://github.com/Azure/azure-amqp. I raised an [issue](https://github.com/Azure/azure-amqp/issues/105) to fix their package to have project URL.

**Comment by nemakam** [comment]
Do you see the requirement for a correction package?
Will make sure the next release doesn't have a build number mentioned.

**Comment by SeanFeldman** [comment]
@nemakam it would be better to unlist 3.0.1.16 and release 3.0.2, but I can understand if it's too much to ask.

**Comment by nemakam** [comment]
Unlisting is not an option. 
Now the question is, does it break some one's build/automation? If not, I believe it can wait for next release.

**Comment by SeanFeldman** [comment]
I honestly don't know 😞
I'm good 🙂

**Comment by SeanFeldman** [comment]
Well, perhaps the issue should be closed when milestone `3.0.2` is addressed? To keep it around as a work item that _will_ be addressed in 3.0.2
