### ISSUE TITLE
ServiceBus - MessageReceiver - No Data after multiple runs

### ISSUE THREAD

**Issue by grik001** [Azure/azure-service-bus-dotnet#470]
I have a message receiver which I am reusing from one call to the other. It seems that after I hit the call multiple times (in the thousands) data is no longer retrieved. To check that I did not run out of messages, I re-instantiated messageReceiver and it immediately starting retrieving data again.

```
messageReceiver = new MessageReceiver(
    connectionString, 
    EntityNameHelper.FormatSubscriptionPath(topic, subscription),
    receiveMode
);

messageReceiver.ReceiveAsync(
    batchSize, 
    TimeSpan.FromMilliseconds(timeoutMilliSeconds)
);
```

So to summarize everything:

1. I have a single instance of messageReceiver
2. I am running a Load test around 3000-9000 calls
3. At one point no data is returned, and unlocked data is still available in servicebus
4. If I re initialize messageReceiver it starts working(using immediate window)
5. If I hit the same service bus from another API targeting the same subscription data is retrieved
6. Has anyone encountered such an issue? Also what I have noticed is that after I let some time pass(did not measure but around 15-30min) the message Receiver starts retrieving data again.

**Comment by nemakam** [comment]
@grik001 
How are you calling it 1000s of times? 
Are they in parallel in multiple threads? 
Are you just calling 'async' methods without awaiting? 
What is the Timeout you are using?
Did any of those calls return any exception?

If this is a consistent behavior, could you provide a small repro?

**Comment by remcoongit** [comment]
I had some similar experience but only after not completing/abandoning a message. Are you sure this is done?

**Comment by grik001** [comment]
How are you calling it 1000s of times?
**I am using the VS Load tests - without wait times and user count 10**

Are they in parallel in multiple threads?
**Yes, since user count is 10 they are in parallel**

Are you just calling 'async' methods without awaiting?
**No, all my code has awaits**

What is the Timeout you are using?
**I am ranging between 50ms to 50000ms - I kept increasing to ensure its not a timeout issue**

Did any of those calls return any exception?
**No, I tried locally with a debugger and hosted on Azure with App Insights, not a single exception, ReceiveAsync just returns null**

If this is a consistent behavior, could you provide a small repro?
**This is a bit hard since its part of a project I have for work. But yes it is reproducible because I wanted to be 100% certain before posting this. To replicate, first post enough messages to a topic with a subscription(I posted around 60k). Then start hitting ReceiveAsync constantly with minimal think times. Ensure to have a single instance of messageReceiver. After 500-1k calls the issue starts occurring.**

**Comment by nemakam** [comment]
Okay.. We definitely have load tests which run at much larger scale. They run perfectly well. The only difference I see is you do not complete/abandon.
I can definitely see how that can cause a HUGE leak in the client. The way AMQP protocol works is that when you receive a message, it is not completely disposed and part of delivery information is kept in memory till you dispose it (complete / abandon / deadletter / defer). In technical terms, this is called as `settlement`. If you keep receiving without settling the message, there's going to be a huge leak in your connection object (technically, `AMQP-Link` object).
If you want the messages to continue living, I'd suggest you `abandon` the messages when you receive.
I have a feeling that should solve this issue for you.

**Comment by remcoongit** [comment]
As alternative (as I also didn't want to complete/abandon/deadletter/defer the message) I actually close the messagereceiver. 

@nemakam perhaps I'm also using it in the wrong way; I have a default lock configured for 5 minutes (queue configuration). When I need to re-process the same message I actually close the messagereceiver and create a new one. The reason I don't abandon the message is that I actually don't want the message on the next  .ReceiveAsync() again. I actually only want it after the 5 minute lock expires.

**Comment by nemakam** [comment]
I guess what you are looking for is #52 . You could probably give you vote there.
Meanwhile, its up to you on how you want to handle this situation. You have two options.
1. Complete the message and schedule another message for 5 mins later.
2. Close the receiver() and open a new one. There's one optimization you could do here. This settlement happens on amqp-link and not the connection. So you could create your connection object and reuse the connection object. Close and recreate the messageReceiver with the same connection object to create a new link.

**Comment by nemakam** [comment]
@grik001 
I'm closing this issue. Reopen if this doesn't solve your problem.

**Comment by SeanFeldman** [comment]
👍 for #52.

> Complete the message and schedule another message for 5 mins later.

Would this cause a proble if you'd need to preserve message ID and have de-duplication turned on @nemakam ?

**Comment by nemakam** [comment]
@SeanFeldman  Yup.. I guess so..

**Comment by SeanFeldman** [comment]
So I thought. I'll post on the appropreate issue.

**Comment by grik001** [comment]
@nemakam 

Thanks for the update. I will consider the options above, but at least now I know what is causing the issue as it was quite strange.

Thanks!
