### ISSUE TITLE
Throw if underlying connection is closed

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#480]
``` c#
var sender = new MessageSender(connectionString, queueName);
var message = new Message(Encoding.UTF8.GetBytes("Message"));
			
await sender.SendAsync(message);
await sender.CloseAsync(); // closing sender that owns the connection

var connection = sender.ServiceBusConnection;
sender = new MessageSender(connection, queueName);
message = new Message(Encoding.UTF8.GetBytes("Message 2"));
await sender.SendAsync(message); // Times out with exception 

```
## Actual Behavior
Times out with exception "Timed out trying to create FaultTolerantAmqpObject`1"

## Expected Behavior
Throw `ObjectDisposedException` exception immediately stating the underlying connection is closed.

## Versions  
- OS platform and version: Windows 10 1803 x64
- .NET Version: any
- NuGet package version or commit ID: 3.0.2

**Comment by nemakam** [comment]
Resolved with #506
