### ISSUE TITLE
Impossible to know if underlying connection is shared or not

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#482]
When clients are created, they can be instantiated with a `connection-string` or a `connection`.
The second method allows `connection` sharing. It is also exposed via [`IClientEntity.ServiceBusConnection`](https://github.com/Azure/azure-service-bus-dotnet/blob/5e5fd3333f0cc9759fa4f0c4a78379e6584d3bcb/src/Microsoft.Azure.ServiceBus/IClientEntity.cs#L53). Unfortunately, there's no was to know if `connection` is **owned** by a client or not. 

In scenarios, where a decision has to be made based on the fact that a client does or does not own a connection, there's no way to determine that information. The information _is_ stored internally on each client, and could be exposed via `IClientEntity` as a read-only property.

**Suggestion** - expose `OwnsConnection` read-only property on `IClientEntity` for all clients to implement.

Modifying `IClientEntity` would cause a breaking change and require a new major version.
Alternative route would be to introduce `OwnsConnection` in a minor release and expose as part of the 
`IClientEntity` interface in the next major.

## Versions  
- NuGet package version or commit ID: 3.0.2

**Comment by nemakam** [comment]
What is the real-world use case here?
You have created your own client. So you already do know which one is shared, and which one is not.

**Comment by SeanFeldman** [comment]
> What is the real-world use case here?

Trying to implement `MessageSender` pooling and when returning a message sender back, information required to determine what to do about the returned sender is not enough.

> You have created your own client. So you already do know which one is shared, and which one is not.

In an application that span a larger code base, getting a sender from a pool (creation) and returning (verification that sender owns its connection) are not necessarily related.

**Comment by SeanFeldman** [comment]
@nemakam I could send a PR if you'd like.

**Comment by SeanFeldman** [comment]
@nemakam now thinking about it, I don't necessarily think we need a two-staged approach. Adding new API in a non-breaking manner is aligned with SemVer.

Adding this property to `IClientEntity`, which would be implemented by `ClientEntity`, which will propogate that change to the rest of the clients (`MessageSender`, `MessageReceiver`, `QueueClient`, `TopicClient`, `SubscriptionClient`, and `SessionClient`). That would be adding to an existing API, not breaking. That's why I think this should be a single PR (this PR).
