### ISSUE TITLE
Custom Header x-opt-enqueue-sequence-number

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#484]
Messages sent w/o a single custom header arrive with one customer header `x-opt-enqueue-sequence-number` with a numeric value. What's this header and shouldn't `UserProperties` collection remain empty if sending code didn't add anything?

Repro:

``` c#
var sender = new MessageSender(connectionString, queueName);
var receiver = new MessageReceiver(connectionString, queueName);

var message = new Message();
await sender.SendAsync(message);
var msg = await receiver.ReceiveAsync();
foreach (var kvp in msg.UserProperties)
{
  kvp.Dump();
}
await receiver.CompleteAsync(msg.SystemProperties.LockToken);
```

![image](https://user-images.githubusercontent.com/1309622/41183725-75b8c08c-6b39-11e8-9abf-a173080939b6.png)

NuGet package: 3.0.2

**Comment by nemakam** [comment]
Will be fixed by #511
