### ISSUE TITLE
Custom or additional metrics dimensions

### ISSUE THREAD

**Issue by FSou1** [Azure/azure-service-bus-dotnet#494]
# Description
I'd like to have an opportunity to divide my topic's metrics based on additional properties (e.g. different app service instances (as well as a business units) use the same topic) at Azure dashboards and alerting rules.

## Actual Behavior
Based on [documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-metrics-azure-monitor#metrics-dimensions) there is just one metric dimension called EntityName (Service Bus supports messaging entities under the namespace).

## Expected Behavior
Is there a way to provide custom metric dimensions for further filtering metrics based on provided dimensions/properties?

**Comment by nemakam** [comment]
@FSou1 
What other dimensions / properties are you looking for?

**Comment by nemakam** [comment]
Since this is a service side request, could you please re open this issue at https://github.com/Azure/azure-service-bus ? Thanks
