### ISSUE TITLE
Equality on descriptors

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#496]
Equality on descriptors requires implementation of several things. It is not enough to implement `IEquatable<T>`.

Also required:

-  Override `Equals(Object)` and `GetHashCode()`
- Override equality operators
-  Optional: Implement ` IComparable<T>`

Sources:

- MSDN [doco](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netframework-4.7.1#notes-to-implementers)
- CLR team [blog post](https://blogs.msdn.microsoft.com/jaredpar/2009/01/15/if-you-implement-iequatablet-you-still-must-override-objects-equals-and-gethashcode/)

**Comment by nemakam** [comment]
Will override `Equals(object)` and `GetHashCode()`.
Wont need to implement `IComparable<T>`

**Comment by SeanFeldman** [comment]
Will you do `==` and `!=` as well? 🙂

**Comment by nemakam** [comment]
You mean operator overloading?

**Comment by SeanFeldman** [comment]
Yes

**Comment by SeanFeldman** [comment]
From the MSDN documentation linked above:

> In addition, you **should overload** the `op_Equality` and `op_Inequality` operators. This ensures that all tests for equality return consistent results.

**Comment by nemakam** [comment]
Done in #481

**Comment by SeanFeldman** [comment]
👍
