### ISSUE TITLE
SubscriptionDescription.EnabledBatchedOperation is missing

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#499]
Connects to #481

The old client was able to set [`SubscriptionDescription.EnabledBatchedOperation`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription.enablebatchedoperations?view=azure-dotnet#Microsoft_ServiceBus_Messaging_SubscriptionDescription_EnableBatchedOperations), but the new client cannot.

**Comment by nemakam** [comment]
Ack!

**Comment by nemakam** [comment]
Pushed into #481
