### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by onovotny** [Azure/azure-service-bus-dotnet#50]
Despite being a .NET Standard 1.3 library, it doesn't currently work on UWP due to the dependency on `System.Reflection.Emit`. Not all libraries (outside of the NETStandard.Library) necessarily support all plaforms and RefEmit has never been supported on Store/UWP apps.

If you need this as an optimization, can you please cross-compile to a uap10.0 target that has an alternative?

FWIW, using VS 2017 and the new .NET Core CSProj format, you can easily multi-target to all platforms, including UWP:
https://github.com/Reactive-Extensions/Rx.NET/blob/15cc575c2ccd5f650ed392b3a22f6b122b436110/Rx.NET/Source/System.Reactive/System.Reactive.csproj#L2-L32

**Comment by terrajobst** [comment]
I second Oren's assessment -- it would be good to avoid the hard dependency on ref-emit. In some cases, you might get away with expression trees as UWP supports those using interpretation. Otherwise, cross-compilation might be the best option.

I'm happy to meet and discuss options.

**Comment by jtaubensee** [comment]
@onovotny, @terrajobst - The library will actually build without the `System.Reflection.Emit` reference, so I think it was inadvertently kept in the dependencies. Without knowing too much about UWP, if we remove that reference, will we still need to explicitly add the following?
```json
  "uap10.0": {
    "dependencies": {
      "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2
    }
```
cc @vinaysurya

**Comment by onovotny** [comment]
@jtaubensee I believe the Sys.Ref.Emit was the only issue, but the easiest way to test is to create a UWP project and try to install the package :) It'll fail on restore if there's an issue. I don't think you'd need a UWP version.

One suggestion: you may want to use `NETStandard.Library` 1.6.1 as your baseline reference as that does resolve some issues installing into some Xamarin profiles that 1.6.0 had. You're likely to get issues with people trying to use the library with Xamarin projects otherwise.

Lastly, you also may want an `.rd.xml` file with any runtime directives for .net native. Those can be hard to determine, but it is possible to test if you run the unit tests on a release mode build of the xUnit for Devices UWP runner:

http://xunit.github.io/docs/getting-started-devices-uwp.html 

For truly testing .NET Native, you do need to alter the default .rd.xml that comes with the UWP project to look something like this:
https://github.com/Reactive-Extensions/Rx.NET/blob/master/Rx.NET/Source/Tests.System.Reactive.Uwp.DeviceRunner/Properties/Default.rd.xml

You can see how we verify this for Rx.NET on a UWP runner here:
https://github.com/Reactive-Extensions/Rx.NET/tree/master/Rx.NET/Source/Tests.System.Reactive.Uwp.DeviceRunner

We share all of the unit tests with .NET Core / .NET Desktop and just run them in release mode on .NET Native.

**Comment by jtaubensee** [comment]
Thank @onovotny - We can work with that! Expect something after the new year.

**Comment by onovotny** [comment]
@jtaubensee I'm always happy to help and/or review things, just ping me whenever :)

**Comment by jtaubensee** [comment]
On hold until #87 is closed.

**Comment by MaxKhlupnov** [comment]
Any progress on this? Still getting errors:  System.Reflection.Emit.ILGeneration 4.3.0 when trying install NuGet for UWP target

**Comment by jtaubensee** [comment]
@MaxKhlupnov - I've just submitted PR #150 to add an output for this, so we should have this in our next release. Please keep in mind, that we have not fully tested this yet.

**Comment by jtaubensee** [comment]
Closing based on #150

**Comment by MaxKhlupnov** [comment]
Thanks, @jtaubensee !
0.0.5-preview installed successfully from NuGet  and compiled in my Xamarin project (Android and UWP).
