### ISSUE TITLE
Descriptors are missing UserMetadata

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#501]
Connects to #481

All three descriptors* (Queue, Topic, and Subscription are missing [`UserMetadata`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription.usermetadata?view=azure-dotnet#Microsoft_ServiceBus_Messaging_SubscriptionDescription_UserMetadata) on their descriptors.

\* technically, should be "all four", as `RuleDescriptor` should have it as well (see #500)

**Comment by nemakam** [comment]
Committed in #481
