### ISSUE TITLE
Allow creating subscription w/o $Default rule

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#502]
Motivation: I need to create a subscription where rules are added later and catch-all rule is harmful.

**Comment by nemakam** [comment]
This is already exposed in the #481 
`Task<SubscriptionDescription> CreateSubscriptionAsync(SubscriptionDescription subscriptionDescription, RuleDescription defaultRule, CancellationToken cancellationToken = default)`

Just send a `FalseFilter()` as the default rule while creating subscription

**Comment by SeanFeldman** [comment]
Would that create a false filter on the backend? I.e. a filter with a SQL rule `1=0`?
I'd rather have no rules at all in this case.

**Comment by nemakam** [comment]
What is the scenario that you want' to do right now which cannot be done?

**Comment by SeanFeldman** [comment]
It’s not about scenario that cannot be implemented @nemakam.
Systems create subscriptions per endpoint and each endpoint adds rules based on what messages it wants to receive. There should be no rules added if an endpoint has not subscribed to anything. Adding default rules was wrong and we had to remove it. Adding default rule that catches nothing is pointless. Right way would be adding a subscription w/o any rules if no rule was specified.

**Comment by nemakam** [comment]
That maybe for your use-case, but not the 80% scenario. 80% scenario is where people don't even manipulate with rules in fact. They just say "subscribe me to this topic", which essentially means, start listening to all events (unless specified with some different rule).
We do realize people have different use cases and hence you can manipulate your default rule while creating the subscription.

**Comment by SeanFeldman** [comment]
> That maybe for your use-case, but not the 80% scenario

Note that "my use-case" is **every single ASB customer that uses our product** case. Which quite a few 😉 And ALL of them do need this. So when I bring this, I'm speaking on their behalf. It sounds wasteful to have a rule that is evaluated for each subscription for no good reason?

I suspect this would be a server-side change involved to not create a default rules, hence the push back.

**Comment by nemakam** [comment]
Its a service side change, as well as a breaking change.

**Comment by SeanFeldman** [comment]
> ts a service side change, as well as a breaking change.

Should have started from that 😞

**Comment by SeanFeldman** [comment]
Close this, but still think this is a wrong default behaviour.
