### ISSUE TITLE
Enable issue selector on GitHub

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#507]
As per GitHub [documentation](https://help.github.com/articles/about-issue-and-pull-request-templates/) it's possible to present users with a choice between reporting a bug vs requesting a feature. Could you please enabled that?

[Stepts to enable templates](https://help.github.com/articles/creating-issue-templates-for-your-repository/).

**Comment by apjanke** [comment]
Here's a PR to do this: #665.
