### ISSUE TITLE
ClientEntity.Abort reference documentation unclear

### ISSUE THREAD

**Issue by CamSoper** [Azure/azure-service-bus-dotnet#508]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

From azure-docs-sdk-dotnet created by [daviburg](https://github.com/daviburg) : Azure/azure-docs-sdk-dotnet#688  

What does Abort do and when do we use it as compared to Close?

Is this alike WCF where in normal execution we do close but when cleaning-up because of exception we use abort? If we create a message receiver but end up not using it, do we call close or do we call abort? Does abort throw? Does abort touch the network?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb566d4c-f64e-ae5a-d792-5ce126d06714
* Version Independent ID: e2df49ef-d8ae-ff52-0fe7-c781b957cb8e
* Content: [ClientEntity.Abort Method (Microsoft.ServiceBus.Messaging)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.cliententity.abort?view=azure-dotnet#Microsoft_ServiceBus_Messaging_ClientEntity_Abort)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/ClientEntity.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/ClientEntity.xml)
* Service: **service-bus**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by nemakam** [comment]
The concept is pretty much alike WCF. Unless you run into exception, you would want to call close(). Close() sends a close command to the service and waits for the response and is a clean way of closing. 
Abort() just aborts everything on the client side. It may touch the network (depending on the protocol / class), but that would all be asynchronous and doesn't get blocked on it. Abort will not throw.
