### ISSUE TITLE
Should SharedAccessSignatureTokenProvider constructors be public?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#518]
Right now they are all internal

**Comment by nemakam** [comment]
`TokenProvider.Create*TokenProvider` has exposed the constructors.. :)

**Comment by SeanFeldman** [comment]
That class (`TokenProvider`) feels weird.
Whey to have a public abstract class that all it does is validate arguments passing into specific token provider constructors. Why not to expose the constructors and validate the arguments there?

**Comment by SeanFeldman** [comment]
True that. It's just really confusing and unnecessary. Rather see that validation on the classes directly and be able to instantiate those rather than going through unnecessary level of abstration. `TokenProvider` to drive a contruct for `GetToken()` and that's it.

**Comment by nemakam** [comment]
I would think it was designed this was to have a single view of all types of token providers that is natively supported. Its an easier way to discover say MSI or AAD like this. 
Given that its been like this for a while, don't think we can remove those methods from `TokenProvider`. Now not sure if its worth exposing the constructors given that the older ones cannot be removed.

**Comment by nemakam** [comment]
I'm gonna stick to "wont fix".. No real benefit...
