### ISSUE TITLE
Management Client does not provide API to retrieve tier information

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#522]
To enable certain operations such as
- queue size
- partitioning
- message/batch size

it requires to know the SKU. Without the API, these operations are either require manual input or lowest common denominator (standard). For automated tools and frameworks that's not an option. Having an API would resolve this.

**Comment by SeanFeldman** [comment]
@nemakam this would be a great addition to the `ManagementClient`.

**Comment by nemakam** [comment]
Agreed.. But it needs changes on service side.. 
Honestly, it will take a couple of months before this is exposed. But it *will* be done sooner or later.

**Comment by apjanke** [comment]
Is “tier” here the Pricing Tier? I'm asking because I'm running into a minor usability issue with Service Bus Explorer that I think would require knowing the Pricing Tier to resolve.

**Comment by SeanFeldman** [comment]
> Is “tier” here the Pricing Tier

Yes.

**Comment by SeanFeldman** [comment]
This is addressed by `NamespaceInfo` added in 3.3.0 and can be closed.

**Comment by apjanke** [comment]
Excellent. Thanks.
