### ISSUE TITLE
Service Bus TimeOut Exception

### ISSUE THREAD

**Issue by SergeBerwert** [Azure/azure-service-bus-dotnet#529]
Hi
Since we switch to the new Service Bus client library (From: WindowsAzure.ServiceBus 4.1.10  To: Microsoft.Azure.ServiceBus 3.0.2) we experience a lot of TimeOut Exceptions. We talked to Azure Support Team and it looks like I could be related to the new Protocol AMQP.
We only have the problems during receiving the messages never during sending. Our Code is pretty basic.
Any Idea what the problem could be?

Exception:
```
Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ErrorCode: TimedOut

Microsoft.Azure.ServiceBus.Core.MessageReceiver+<OnReceiveAsync>d__87.MoveNext():709
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<>c__DisplayClass65_0+<<ReceiveAsync>b__0>d.MoveNext():125
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.RetryPolicy+<RunOperation>d__18.MoveNext():445
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
Microsoft.Azure.ServiceBus.RetryPolicy+<RunOperation>d__18.MoveNext():731
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<ReceiveAsync>d__65.MoveNext():482
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<ReceiveAsync>d__63.MoveNext():118
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.MessageReceivePump+<MessagePumpTaskAsync>d__11.MoveNext():312
Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.ServiceBusConnection+<CreateConnectionAsync>d__38.MoveNext():218
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1+<OnCreateAsync>d__5.MoveNext():0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.Amqp.Singleton`1+<CreateValue>d__20.MoveNext():0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13.MoveNext():0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator+<CreateAndOpenAmqpLinkAsync>d__11.MoveNext():186
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task):0
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<CreateLinkAsync>d__102.MoveNext():466
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1+<OnCreateAsync>d__5.MoveNext():0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.Amqp.Singleton`1+<CreateValue>d__20.MoveNext():0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13.MoveNext():0
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):39
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):0
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<OnReceiveAsync>d__87.MoveNext():322

```
 
Code:
 ```
               var options = new MessageHandlerOptions(e => _log.LogServiceBusException($"Could not execute '{nameof(ProceedDataUpdate)}'.", e))
                {
                    AutoComplete = true,
                    MaxAutoRenewDuration = TimeSpan.FromMinutes(1),
                    MaxConcurrentCalls = 1
                };

                _dataClient = _connector.GetSubscriptionClientForImportResults(name);
                _dataClient.RegisterMessageHandler(ProceedDataUpdate, options);

```

```
        private async Task ProceedDataUpdate(Message message, CancellationToken token)
        {
            try
            {
                var results = message.GetLz4MessagePackObject<ImportResult[]>();

                var updates = ChangeDescription.Convert(results).ToArray();

                _log.LogInformation($"Proceed updates: {ChangeDescription.ToString(updates)}");

                await CallGridOnDataUpdate(updates);
            }
            catch (Exception ex)
            {
                _log.LogError(ex, "ProceedCacheUpdate faild with unexpected exception");
            }
        }

```

**Comment by nemakam** [comment]
How often do you run into this? 
Also, to check if it is due to AMQP, you could switch to AMQP on the old client and see if the repro exists. I believe the protocol shouldn't make a difference.

**Comment by SergeBerwert** [comment]
@nemakam When the servers are running after a restart it works for 1 to 3 days then the exceptions start to happen. After a while service bus client does not work anymore at all. And we have to restart the service. Besides the code update, we had to do for the new library we did not change a lot. We got forced to use the new library, going back would be a lot of work.

**Comment by SeanFeldman** [comment]
@SergeBerwert thanks for the update. I don't see in the [shared log](https://github.com/Azure/azure-service-bus-dotnet/issues/529#issue-338825812) anything from the `LogServiceBusException`, hence [my question](https://github.com/Azure/azure-service-bus-dotnet/issues/529#issuecomment-403050243) if you could add it. Would like to see what's logged when timeout is happening.

> we don’t have the code public. But it is for sure embedded in a large and kind of complex app.

Not asking to share your code as-is, but if you could **create** a repro, that would help to validate if the behaviour can be replicated or not.

**Comment by SeanFeldman** [comment]
`Microsoft.Azure.ServiceBus.ServiceBusCommunicationException` sounds like connectivity issue.

Are you running your service on-premises?
Our solution is to use a circuit breaker if there is a problem receiving messages for longer than two minutes, allowing customers to act when CB is triggered.

Will let ASB team try http you.

**Comment by SergeBerwert** [comment]
@SeanFeldman sorry for my late response I was busy.
We host our service in azure. We have a scale set with 3 Servers running Docker Deamon. Our applications run insight a container. I guess the Timeouts somehow are connected to network issues. 
About that CB trigger, you were talking. Is there any way to not stop trying? It makes no sense for me to stop after two minutes. If there is an issue it will take easy more then two minutes. And when everything is back online my app still doesn’t work because I have to restart the apps. I could make a retry logic but that sounds a little redundant for me.

**Comment by SeanFeldman** [comment]
@SergeBerwert the CB I'm referring to is our custom solution. Technically, if you want infinite retries, you could extend `RetryPolicy` to create your own. Though I'm not sure if that's effective. And yes, when our CB is armed and fired, we expect process to restart.

**Comment by northtyphoon** [comment]
We hit similar issue. The symptom we observed is the subscription client suddenly stopped receiving message from ASB. We had to restart the service to recover. We use 2.0 SDK. 
A related problem is when the issue occurred, we didn't get any exception or error. We could see the message count in the subscription kept going up. 
Is there any way to detect and log the error inside messagepump if it encounters any issue?

**Comment by SeanFeldman** [comment]
@northtyphoon sounds like #549

**Comment by SergeBerwert** [comment]
Had another really bad day with service bus again. The library just stops receiving Messages. I have a queue contains more than 10’000 messages. Every time I start the app it processes a couple hundred messages and stops again.  No Exception just stops receiving. 
I Implemented a log message to make sure that it does not stock in my code. I also monitor the IsCloasedOrClosing property to observe if the client closed the connection. But it did not. What can I do to figure out the problem?

**Comment by SergeBerwert** [comment]
I would need to write an application to do that. the application is based on a lot of repos and dependencies. One option could be giving you access to a vm where everything is set up to test.

**Comment by SeanFeldman** [comment]
Rather use code only to try out from different environments. It will also
help ASB team to see it in isolation.

**Comment by SergeBerwert** [comment]
I Download the source code from the library and integrated into my project. I was hoping I could figure out more. But after I removed the NuGet package and referenced the source code I could proceed all 10k messages. I still can not say what the problem is but it looks like there is a problem with the auto-commit mechanism. 

I enabled all Exception I was hoping I could find out if there is an internal problem I could not see one. But I figured out that internally an exception gets thrown after every message. However, it seems not to be a problem but it looks bad code to me.

![17-08-_2018_15-10-00](https://user-images.githubusercontent.com/7489837/44288409-e2647180-a235-11e8-8680-e7a620a3ffb5.png)

I can send you the code but you would not be able to run it.

**Comment by nemakam** [comment]
@SergeBerwert 
Can you try updating to latest `Microsoft.Azure.Amqp` v2.3.5 and see if that fixes your problem? It contains an important fix.
And regarding the exception for every message, we have a #548 in progress which will be worked out soon.

**Comment by nemakam** [comment]
It does not solve the connection problems you are facing (which might not even be related to the client), but it does fix a problem where you stop receiving messages.

**Comment by sirarsalih** [comment]
This happened to me because of a company firewall. When I allowed the connection through the firewall, then this error stopped.

**Comment by harryariyanto** [comment]
Hi, Got the same problem now. But for me it is on `sessionClient.AcceptMessageSessionAsync()` and it always return 

> TimeoutException: The operation did not complete within the allocated time 00:00:59.8411375 for object receiver8.

i'm using 

> .net core 2.1.1

 and 

> Microsoft.azure.servicebus 3.4.0
