### ISSUE TITLE
Reevaluate returning List<T> instead of IList<T>

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-service-bus-dotnet#53]
Similar to 

https://github.com/dotnet/coreclr/issues/1579
https://github.com/dotnet/coreclr/pull/4468

Could you reevaluate the usage of `IList` on the APIs called on the hot path? For example in `MessageReceiver.OnReceiveAsync(int maxMessageCount)` you could directly return `List<BrokeredMessage>.` There is no value in abstracting it, not even for inheritors. 

Please also consider where you know the message count or the amount of messages that the client wants to fetch to preallocate the lists with that count for better perf.

https://github.com/danielmarbach/MicroBenchmarks/blob/master/MicroBenchmarks/Linq/EnumerableVsList.cs

![image](https://cloud.githubusercontent.com/assets/174258/21457702/a55c24d8-c931-11e6-9b80-5b61843eecbe.png)

As you can see the interface dispatch and the GC overhead can mean a lot when you are receiving multiple messages

Happy to provide a PR if you agree.

**Comment by SeanFeldman** [comment]
Title is misleading. Sounds like it should have been "Reevaluate returning List<T> instead of IList<T>".

**Comment by danielmarbach** [comment]
Fair enough, changed

**Comment by vinaysurya** [comment]
I hear conflicting guidelines about these:
1) From looking at the guidelines at the link below it looks it is recommended that we offer more generic interfaces instead of specific ones.
   https://msdn.microsoft.com/en-us/library/dn169389(v=vs.110).aspx
2) OTOH, I also hear argument about being generic in the input path where as being as specific as possible in the output path.

So although I see value in what you mention, not certain which of the ones to go with.

Another idea, that @dstuckims was mentioning was introduce a type called BrokeredMessageCollection, which can be internally implement a behavior similar to lists but also be generic enough that will allow us to change our implementation later on. So that is another possibility.

**Comment by danielmarbach** [comment]
@vinaysurya 

Here is my totally personal take on this. The framework guidelines are great for general purpose libraries/frameworks and user-centric code. But here we are talking about essentially a communication library which is going to be used in many application and systems out there. I think a communication library or driver should be as optimised as possible without necessarily sacrificing the user experience. That why I'd avoid Enumerables or collection interfaces on the hot path. There is almost no difference in terms of speed and allocations between `List<T>` and `T[] `as long as the user specifies the length of the list. Just accepting `T[]` from a library perspective can be too restrictive since there might be user scenarios where they dynamically determine the elements T and therefore I'd naturally lean towards `List<T>`.

Generic on the input path and specific on the output path is probably the best middle way so far if you don't want to go down this "extreme" path.

No offence @dstuckims but I would try to avoid to write custom collection as much as possible. The framework collections are heavily optimised and satisfy many use cases. In my point of view there is no justification other than we might replace the inner workings but this doesn't justify the complexity that is involved in custom implementing a collection.

Hope that helps to make up your minds.

Daniel

**Comment by jtaubensee** [comment]
Hi @danielmarbach - This is not an optimization that feel comfortable making now. The good news is that since we would move from IList to List, this would not be a breaking change in the future. We can always reopen if needed. Thanks for the idea though!
