### ISSUE TITLE
MessageSession.RenewSessionLockAsync() throws SessionLockLostException

### ISSUE THREAD

**Issue by snrnats** [Azure/azure-service-bus-dotnet#530]
I am using Azure Service Bus Queue with enabled sessions. I am trying to implement code that will handle `SessionLockLostException`. I this case I would like to try to renew session and continue my work if it succeed. Note that each session has only one consumer.
Here is a simple example:
 ```
var client = new SessionClient(...);
var session = await client.AcceptMessageSessionAsync(sessionId);
var message = await session.ReceiveAsync();
try
{
    await Task.Delay(40000); // Actual work
    await session.CompleteAsync(message.SystemProperties.LockToken);
}
catch (SessionLockLostException)
{
    await session.RenewSessionLockAsync();
    await session.CompleteAsync(message.SystemProperties.LockToken);
}
```

## Actual Behavior
I am getting `SessionLockLostException` when I call `session.RenewSessionLockAsync()`.
```
Microsoft.Azure.ServiceBus.SessionLockLostException
  HResult=0x80131500
  Message=The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:c38ba7c50000318600005ab75b3f91b5_G6_B31, SystemTracker:..., Timestamp:7/6/2018 3:59:15 PM
  Source=Microsoft.Azure.ServiceBus
  StackTrace:
   at Microsoft.Azure.ServiceBus.MessageSession.<OnRenewSessionLockAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```
Also I noticed that thrown exception is the same exception object that was thrown at `session.CompleteAsync()`. I suppose it's how `MessageSession` is implemented. It caches exception and don't allow any other operations. But is it suppose to deny attempt to renew session lock?
## Expected Behavior
Session is renewed when I call `RenewSessionLockAsync()`

## Versions  
- OS platform and version: Version	10.0.16299 Build 16299
- .NET Version: .Net Core 2.0
- NuGet package version or commit ID: 3.0.2

**Comment by nemakam** [comment]
```csharp
catch (SessionLockLostException)
{
   await session.RenewSessionLockAsync();
   await session.CompleteAsync(message.SystemProperties.LockToken);
}
```

You are trying to renew the session once the session is already lost, which isn't useful. When you accept a session, you will have `session.LockedUntilUtc`. Use that time and renew the session before that time expires.
Once you hit `SessionLockLostException`, there is no way you can perform operations on that session. The only way forward is to accept the session again.
