### ISSUE TITLE
Options for coexisting with WindowsAzure.ServiceBus-based consumer

### ISSUE THREAD

**Issue by mjordan73** [Azure/azure-service-bus-dotnet#532]
We have legacy code that subscribes to a topic on Azure Service Bus (ASB) written against the WindowsAzure.ServiceBus library.  We are developing new code in .Net Core against the Microsoft.Azure.ServiceBus to send messages to this topic.  I am having issues where I cannot seemingly consume messages created with the new library with my existing legacy consumer based on the old .Net Framework library.

I had noted there were some issues with earlier versions of the .Net Core library but it wasn't clear if a workaround existed or not (particularly that didn't require rework of legacy code).

## Actual Behavior
1.  Messages are ending up as dead letters due to max retries being exceeded
2. The subscribing service doesn't seem to pick messages up (i.e. SubscriptionClient.OnMessageAsync isn't firing) from the new sending code at all (but works fine with messages sent from WindowsAzure.ServiceBus-based code) although inspecting the messages using Service Bus Explorer doesn't reveal any obvious difference.

## Expected Behavior
Would expect interchange of messages between old and new libraries to be compatible.
 
## Versions  
- OS platform and version: Windows 10 & Windows Server 2012
- .NET Version:  .Net Framework 4.6.1 & .Net Core 2.0
- NuGet package version: WindowsAzure.ServiceBus 3.3.2 & Microsoft.Azure.ServiceBus 3.0.2

**Comment by SeanFeldman** [comment]
@mjordan73 have a look at #239

**Comment by mjordan73** [comment]
Thanks @SeanFeldman. I went through that issue again and have ended up with a slightly hacky solution where i've added an optional message property which tells my 'old world' receiver to treat the body as a stream and not a string.  So changes needed on the receiver  and sender, but at least small ones and any legacy senders are unaffected.

I'll echo what others have said though that it seems bonkers that there doesn't seem to be backwards compatibility out of the box.

**Comment by tonjohn** [comment]
My team hit the same issue. To address this, we updated our listener with a helper method that attempts to figure out which type the body is and extract accordingly:

    private static JObject GetBody(BrokeredMessage brokeredMessage)
            {
                string objAsJson;
                object objIsStream;
    
                brokeredMessage.Properties.TryGetValue("isStream", out objIsStream);
                bool bIsStream = objIsStream != null ? (bool)objIsStream : brokeredMessage.DeliveryCount % 2 == 0; // Default delivery method is String; Retry String as Stream if it fails
    
                if (bIsStream)
                {
                    // Azure Functions and Logic Apps send messages as Stream
                    // Service Bus Explorer defaults to Stream but can send as String
                    Stream stream = brokeredMessage.GetBody<Stream>();
                    StreamReader reader = new StreamReader(stream);
                    objAsJson = reader.ReadToEnd();
                }
                else
                {
                    // Our services send messages as String
                    objAsJson = brokeredMessage.GetBody<string>();
                }
    
                return JObject.Parse(objAsJson);
            }
