### ISSUE TITLE
ReceiveBatch support not in NetStandard library

### ISSUE THREAD

**Issue by kmleow** [Azure/azure-service-bus-dotnet#533]
Trying to port from the old Nuget to the new .NET Standard then realised there is no support for batching. i.e. https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.receivebatch?view=azure-dotnet

Reason for wanting this:
Receive in batch from bus then send this data to another repository in batches.

May I know if this is ever going to be implemented or is something you advise against having please?

**Comment by SeanFeldman** [comment]
There was an architectural change in the .NET Standard client. `QueueClient` is no longer exposes receiving of messages directly. Instead, it exposes a higher level construct known as Message Pump and allows to register a message handler to handle messages one-by-one.
Should you need to receive batches, you'd need a "lower" level API and use `MessageReciever.ReceiveAsync()`.
