### ISSUE TITLE
Handle count growing

### ISSUE THREAD

**Issue by alanwales** [Azure/azure-service-bus-dotnet#535]
## Actual Behavior
(Moved from https://github.com/Azure/azure-amqp/issues/113)
We noticed that the handle count on our azure web app is continually growing:

![image](https://user-images.githubusercontent.com/17590123/43221165-4f8f9678-904c-11e8-96f2-a4f3cbdf0bd1.png)

After taking a full process dump and analyzing the retained objects we can see that the ServiceBusConnection has a TimedHeartBeat that creates TimerQueueTimer objects. We see that the number of these objects (2.8k in the screenshot) approximately matches the number of handles shown on the web app. A follow-up process dump showed a similar story (3k TimerQueueTimer objects and 3k handles).

![image](https://user-images.githubusercontent.com/17590123/43221172-5816660a-904c-11e8-814a-803dbbe12ec1.png)

We are following the best-practice guidelines and reusing the MessageSender objects (31 in total). It would be great to understand if there is a setting we can apply or a fix provided, thanks

## Expected Behavior
Handles counts are stable

## Versions  
- OS platform and version: Windows NT 10.0.14393.0 x64
- .NET Version: .Net core 2.1
- NuGet package version or commit ID: Referenced from Microsoft.AspNetCore.All metapackage 2.1.0

**Comment by nemakam** [comment]
I'll take a look at this and get back to you... Looks like some connections are getting leaked. 
If you still have the dump, could you check the number of `ServiceBusConnection` objects and the number of `AmqpConnection` objects in the dump?

**Comment by alanwales** [comment]
I checked both process dumps and see the same pattern:

ServiceBusConnection: 20
FaultTolerantAmqpObject<AmqpConnection>: 20
AmqpConnection: 4
TimedHeartBeat: 4
TimerQueueTimer: 2800 (first dump), 3200 (second dump)

**Comment by tomkerkhove** [comment]
We have the same issue

**Comment by tomkerkhove** [comment]
Any update on this @nemakam?

**Comment by moshegutman** [comment]
@alanwales How did you capture that dump? I think my app is experiencing the same issue.

**Comment by alanwales** [comment]
You can do it by getting a memory dump of your running process. If you are using Azure App Service you can do it like this:

* Make sure your app is running x86 first (I was never able to get our x64 memory dump readable but your mileage may vary), you can set that in the Properties blade
* Go to Advanced Tools and click Go (to launch Kudo console)
* Click Process Explorer
* Right-click on the process running your app (w3wp.exe, not the one with the scm label)
* Download memory dump > Full dump

Then open this file in DotMemory and dig into the largest objects and key retention paths.

We still experience this issue but so far doesn't seem to impact the actual running of the app

**Comment by nemakam** [comment]
@tomkerkhove @alanwales 
Do you guys create your own RetryPolicy or use the default in built retry policy?

**Comment by tomkerkhove** [comment]
We add our own retry as well

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by nemakam** [comment]
Closing based on #587

**Comment by moshegutman** [comment]
Do you know when this fix will ship via NuGet?

**Comment by SeanFeldman** [comment]
![image](https://user-images.githubusercontent.com/1309622/46968911-ca607100-d071-11e8-86ac-7dcac1f2b556.png)

In case you're asking for a specific date, that's a hard one. Just like exact weather forecasts 🙂
