### ISSUE TITLE
MessageExtensions should not be public

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#542]
`MessageExtensions` is made public when it should be internal.
`ExtractActivity()` is public, but should be made internal.
This issue should be tackled along with #541 since changing class visibility will be a breaking change and will require a new major.

**Comment by lmolkova** [comment]
> ExtractActivity() is public, but should be made internal.

ExtractActivity must be public - this is used for tracing when messages are processed manually (not with handler)

**Comment by nemakam** [comment]
Yes. If users need to integrate app insights with the way they process the message, and want to keep track of end-to-end time spent in each layer, they would need to extract the diagnostics activity and integrate into their code.

**Comment by lmolkova** [comment]
@SeanFeldman exactly, when lib users want to correlate telemetry between consumer and producer, they have to extract tracing context (Activity) from the message and stamp it on the telemetry when the message is processed

This article https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing#trace-message-processing and code xml documentation provide more info about it.

**Comment by SeanFeldman** [comment]
In that case it is better to have it in a separate extension class specific for Diagnostics (i.e. #541).
Thank you for explanation.
