### ISSUE TITLE
UWP suport

### ISSUE THREAD

**Issue by marjoballabani** [Azure/azure-service-bus-dotnet#545]
## Actual Behavior
1. Package restore failed. Rolling back package changes for 'App14'.

## Expected Behavior
1. Trying to install NugetPackage on my UWP app. My app is just new blank app no changes done to it.

## Versions  
- OS platform and version: Windows 10 Enterprise, Version 1803 
- .NET Version: 4.7.2
- NuGet package version or commit ID: 5.0

**Comment by axisc** [comment]
@marjoballabani  - Could you try the latest SDK version and if it still fails, please share the errors.

closing it for now. feel free to open if there are more questions.
