### ISSUE TITLE
Connections lost

### ISSUE THREAD

**Issue by nemenos** [Azure/azure-service-bus-dotnet#549]
## Actual Behavior
1. If connections are lost it does not reconnect automatically

## Expected Behavior
1. Connection does not get lost or library can reconnect on its own

## Versions  
- OS platform and version: Azure App Service
- .NET Version: 4.7
- NuGet package version or commit ID: 3.0.1

I'm working with Azure ServiceBus, standard tier.

I'm trying to figure out what's happened since a couple of weeks, (it seems it started when bus traffic has increased, maybe 10-15 messages per second).

I have automatic creation of subscription using

`
subscriptionOpts.AutoDeleteOnIdle = TimeSpan.FromHours(3);
`
Starting from lasts weeks, (when we got a traffic increment), sometimes our subscriptionclients stopped receiving messages and after 3 hours they get deleted.

`
var messageOptions = new MessageHandlerOptions(args =>
    {
         Emaillog.Warn(args.Exception, $"Client ExceptionReceived: {args.Exception}");
         return Task.CompletedTask;
    }) { AutoComplete = true };
`
`
_subscriptionClient.RegisterMessageHandler(async (message, token) => await OnMessageReceived(message, $"{_subscriptionClient.SubscriptionName}", token), messageOptions);
`

Is it possible that a subscription client gets disconnected and doesn't connect anymore? I have 4-5 clients processes that connect to this topic, each one with his own subscription. When I find one of these subscriptions deleted, sometimes they have all been deleted, sometimes only some of them have been deleted.

I haven't found anything on the documentation about possibility of disconnections of the client and eventual need (and ways) to reconnect, because actually that's what's happening
Is it a bug? The only method call I do on the subscriptionClient is RegisterMessageHandler. I don't manage manually anything else...

We can already reproduce (a bug?) that if you change a setting on a Subscription, all Active clients are disconnected and do not connect again. This seems similar.

Thank you in advance

**Comment by SeanFeldman** [comment]
@nemenos to sum it up what you're saying is: changes made to an entity (subscription) a client is connected to causes that client to silently (w/o any errors) disconnect. 👍/👎

**Comment by nemenos** [comment]
That's for sure. In addition I get (random?) disconnections which do not reconnect also not changing anything on the subscription.

**Comment by northtyphoon** [comment]
We had similar issue. Current investigation leads us to suspect the problem is the code was stuck in ISubscrptions.CompleteAsync for some reason which prevented releasing `maxConcurrentCallsSemaphoreSlim` in `MessageReceivePump`. So it just stopped receiving the new message unless restarting the process.

We are using SDK 2.0 on .Net Framework 4.7/Windows Server 2016.

**Comment by northtyphoon** [comment]
I think it's the root cause https://github.com/Azure/azure-amqp/issues/114

**Comment by nemenos** [comment]
any ETA on this fix? For us it's a huge bug and we need to get an update soon or a workaround!!

**Comment by axisc** [comment]
The fix is available in AMQP library 2.3.3.

**Comment by mohitgoyal91** [comment]
Is the same fix available in any of the java version also?
