### ISSUE TITLE
ISenderClient:SendAsync(IList<Message> messageList) throws null reference when messageList is empty

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [Azure/azure-service-bus-dotnet#550]
## Actual Behavior
1. SendAsync throws null reference exception when given collection of messages is empty.

## Expected Behavior
1. No exception should be thrown.

## Simplest repro
```csharp
        [Fact]
        [DisplayTestMethodName]
        void Empty_Collection_Of_Messages_Returns_Empty_AMQP_Message()
        {
            var messages = new Message[0];

            var batchedMessage = AmqpMessageConverter.BatchSBMessagesAsAmqpMessage(messages);

            Assert.NotNull(batchedMessage);
        }
```

> System.NullReferenceException : Object reference not set to an instance of an object.
>    at Microsoft.Azure.ServiceBus.Amqp.AmqpMessageConverter.BatchSBMessagesAsAmqpMessage(IEnumerable`1 sbMessages)
>    at Microsoft.Azure.ServiceBus.UnitTests.AmqpConverterTests.Empty_Collection_Of_Messages_Returns_Empty_AMQP_Message()

## Reason
https://github.com/Azure/azure-service-bus-dotnet/blob/6f144e91310dcc7bd37aba4e8aebd535d13fa31a/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs#L59
`dataList` is initalized in a foreach loop, so when there is no messages it will be null.
Later one, its used by `amqpMessage = AmqpMessage.Create(dataList);` what causes null reference exception.

## Versions  
- OS platform and version: Windows 10
- .NET Version: .NET Core 2.1
- NuGet package version or commit ID: 3.1.0-preview, master

I can pick up this issue if you want.

**Comment by axisc** [comment]
Sorry for the late response. If you'd still like to fix it please proceed and submit a pull request.

thank you !

**Comment by thomaslevesque** [comment]
I just hit the same bug

**Comment by lukasz-pyrzyk** [comment]
Oh, now i have the reason to fix it :) I will do it this week

**Comment by thomaslevesque** [comment]
> Later one, its used by `amqpMessage = AmqpMessage.Create(dataList);` what causes null reference exception.

Are you sure about this? Looking at [the code for `AmqpMessage`](https://github.com/Azure/azure-amqp/blob/1de6c4b66437a214a72f5a924cfd78941032489e/Microsoft.Azure.Amqp/Amqp/AmqpMessage.cs#L213), I don't see how it could throw, since it doesn't dereference `dataList`.

**Comment by thomaslevesque** [comment]
Anyway, in the meantime the workaround is simple. Don't call `SendAsync` if you don't have any message...

**Comment by lukasz-pyrzyk** [comment]
I think in the past it was throwing on the `amqpMessage = AmqpMessage.Create(dataList);` when `dataList` was null. Currently it throws later, on the `firstMessage.MessageId`. Not sure if I was mistaken or `Microsoft.Azure.Amqp.AmqpMessage` was updated and `AmqpMessage.Create` changed

**Comment by SeanFeldman** [comment]
`SendAsync()` should not allow sending empty or null collection.
Guard for null collection is in place. Guard for empty collection is missing. 
PR #641 will address this.

**Comment by thomaslevesque** [comment]
> `SendAsync()` should not allow sending empty or null collection.

I would have expected `SendAsync()` with an empty collection to be a no-op

**Comment by SeanFeldman** [comment]
> I would have expected `SendAsync()` with an empty collection to be a no-op

Interesting. Could you elaborate why an empty collection would be a no-op, but a `null` message would throw? I'm trying to understand the rationale behind this though. Both imo are invalid cases and messages should not be attempted to be dispatched. But I might not be seeing another pov. Thanks.

**Comment by thomaslevesque** [comment]
> Interesting. Could you elaborate why an empty collection would be a no-op, but a `null` message would throw? I'm trying to understand the rationale behind this though. . But I might not be seeing another pov. Thanks.

Well, the method expects a list. Null isn't a list, so obviously it should be rejected, but an empty list is still a valid list. There are many examples of methods in the BCL that accept an empty collection: `List<T>.AddRange`, collection constructors, Linq methods, `Task.WaitAll`, `String.Concat`, `Parallel.ForEach`, `Stream.Write`...

**Comment by SeanFeldman** [comment]
Convinced. PR #642 will replace the original PR.

**Comment by thomaslevesque** [comment]
@SeanFeldman thanks!
