### ISSUE TITLE
Missing MessagingFactory

### ISSUE THREAD

**Issue by jwisener** [Azure/azure-service-bus-dotnet#556]
## Actual Behavior
1.  Upgrading our older code (framework 4.6) and attempting to target the .net core 2
2. The Messaging Factory was specifically used to allow scalability without exhausting tcp ports.

## Expected Behavior
1.  Was Messaging Factory removed? Expected some congruent class that offers the same type functionality.

## Versions  
- OS platform and version: Windows/Azure
- .NET Version: .net core
- NuGet package version or commit ID: 3.1.0

**Comment by SeanFeldman** [comment]
While `MessagingFactory` is gone, the idea of connection pooling and sharing connections is there. When you create your clients, passing a connection will reuse it. When passing a connection string, will cause clients to establish a new connection.
