### ISSUE TITLE
OnMessage/OnMessageAsync very slow invocation with AMQP 

### ISSUE THREAD

**Issue by jr01** [Azure/azure-service-bus-dotnet#557]
Consider the following simple code:
```
namespace ConsoleApp
{
    using System;
    using System.Diagnostics;
    using Microsoft.ServiceBus.Messaging;

    class Program
    {
        static void Main(string[] args)
        {
            var messagingFactory = MessagingFactory.CreateFromConnectionString(
                "Endpoint=sb://xxxxxx.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;" +
                "SharedAccessKey=xxxxxx=;TransportType=Amqp");

            var queueClient = messagingFactory.CreateQueueClient("myqueue");
            
            var sw = new Stopwatch();
            sw.Start();

            queueClient.OnMessage(
                b =>
                {
                });

            Console.WriteLine("Took: " + sw.Elapsed);
            Console.ReadLine();
        }
    }
}

```
## Actual Behavior
1. When using `TransportType=Amqp` the `OnMessage` invocation often takes more than 10 seconds, while without Amqp it takes around 0.5 second.  Sometimes with Amqp it is fast though.
When there are many queues to listen to and thus multiple queue clients / OnMessage invocations (we are using webjobs framework) it takes a long time to just startup the application.

## Expected Behavior
1. Invoking OnMessage/OnMessageAsync should be fast.

## Versions  
- OS platform and version: Win10 Enterprise
- .NET Version: 4.6.1
- NuGet package version or commit ID: tested with WindowsAzure.ServiceBus 3.4.6 and 5.00

**Comment by SeanFeldman** [comment]
@jr01 this is a new client repository (`Microsoft.Azure.ServiceBus`), not the client you're using.
If this is a new project, I recommend moving off the old client and use the new one.

**Comment by jr01** [comment]
@SeanFeldman  - Yes it looks I created the issue in the wrong place.  Any suggestion to get it at the right place / team would be appreciated!  We have an older project that uses the Microsoft [webjobs](https://github.com/Azure/azure-webjobs-sdk) framework. The webjobs project is switching to the newer client for their upcoming v3 version.

**Comment by SeanFeldman** [comment]
The old client doesn't have a repo, but you could try 
https://github.com/Azure/azure-service-bus/issues/
