### ISSUE TITLE
Possible null reference exception if response.Content == null

### ISSUE THREAD

**Issue by dlstucki** [Azure/azure-service-bus-dotnet#562]
This expression will return null instead of a Task if response.Content == null:
https://github.com/Azure/azure-service-bus-dotnet/blob/e278f87b0b3aa563ab055918e988baec9ec155a3/src/Microsoft.Azure.ServiceBus/Management/ManagementClient.cs#L898

Calling await on a null Task results in a NullReferenceException.

**Comment by nemakam** [comment]
Closed with #572
