### ISSUE TITLE
QueueDescription/TopicDescription are not forward compatible

### ISSUE THREAD

**Issue by dlstucki** [Azure/azure-service-bus-dotnet#563]
https://github.com/Azure/azure-service-bus-dotnet/blob/e278f87b0b3aa563ab055918e988baec9ec155a3/src/Microsoft.Azure.ServiceBus/Management/QueueDescriptionExtensions.cs#L13

If in the future some new property is added to QueueDescription/TopicDescription this existing code will drop that unknown new property upon reading the QueueDescription. Then if an update is performed the serialized version will not include the not understood property and it will clear that property instead of leaving it as it was.

DataContract solves the issue using IExtensibleDataObject. This current XElement based approach would need to store a collection of not understood properties when deserializing and serialize them on the other side.

**Comment by nemakam** [comment]
Closed with #572
