### ISSUE TITLE
Forced batching by MessageSender even when queue doesn't support batching, throws exception

### ISSUE THREAD

**Issue by damongr-msft** [Azure/azure-service-bus-dotnet#565]
## Actual Behavior
On a queue that has partitioning and duplication detection enabled.
1. Calling MessageSender.SendAsync (with single message) multiple times
2. Get exception: System.InvalidOperationException: Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled.

## Expected Behavior
1. Disable batching by setting Batching = false or set something equivalent to the BatchFlushInterval to Zero
2. Call SendAsync (single message) as much as we want but no batching will take place

## Versions  
- OS platform and version: Windows
- .NET Version: .Net Standard 2.0/4.6.1
- NuGet package version or commit ID: 3.0.2

**Comment by SeanFeldman** [comment]
> 3.0.2

Could you try with the latest 3.1.0?

**Comment by damongr-msft** [comment]
Ok, I believe I've found out what is going on, there was an older version of our code which wasn't setting the MessageId after we converted all of our Queues to enable duplication detection. If you don't set the MessageId on a service bus queue that has duplication detection enabled, then you get the following error even if you send a single message:
**System.InvalidOperationException: Batching brokered messages with distinct SessionId, PartitionKey, or MessageId is not supported for an entity with partitioning and duplicate detection enabled.**

This error is very strange as Batching is not involved and also it seems completely wrong since MessageId is mandatory not that it isn't supported.
