### ISSUE TITLE
System.BadImageFormatException Microsoft.ServiceBus.PerformanceCounters.MessagingPerformanceCounters

### ISSUE THREAD

**Issue by carlberg74** [Azure/azure-service-bus-dotnet#566]
Using ServiceBus TopicClient or any other similar api gives runtime error:

System.BadImageFormatException: Could not resolve field token 0x04000861, due to: Could not load type of field 'Microsoft.ServiceBus.PerformanceCounters.MessagingPerformanceCounters:counterSet' (3) due to: Could not resolve type with token 010001ae from typeref (expected class 'System.Diagnostics.PerformanceData.CounterSet' in assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') assembly:System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:System.Diagnostics.PerformanceData.CounterSet member:(null) assembly: Microsoft.ServiceBus.dll type:MessagingPerformanceCounters member:(null)
File name: 'Microsoft.ServiceBus'
  at Microsoft.ServiceBus.Messaging.MessagingFactorySettings..ctor (Microsoft.ServiceBus.Messaging.MessagingFactorySettings other) [0x0001e] in <8f017c5ee0664dfca2149ed0718e520a>:0 

Works on Windows, but give runtime error on linux.

Any idea what I should look for to fix this?

## Tested with versions
NuGet: Micrsosoft.Azure.ServiceBus version 3.1.0 
(also tested with NuGet: WindowsAzure.ServiceBus 5.0.0, same error)
Mono 5.14.0.177 and 4.2.1.
Compiled: .Net Framework 4.6.1 and 4.7.1
OS: Ubuntu 16.04.5 LTS.

**Comment by SeanFeldman** [comment]
This client (Micrsosoft.Azure.ServiceBus) does not work with performance counters. The old client (WindowsAzure.ServiceBus) does. The old client is **not** .NET Standard compliant and cannot run on anything other than Windows.

**Comment by carlberg74** [comment]
Can I some how disable the performance counters when running on mono?

**Comment by SeanFeldman** [comment]
You don't need to do that when using the new client... Send like you're
mixing the two.

**Comment by carlberg74** [comment]
Ahh,, now I see:
Microsoft.ServiceBus  => old
Microsoft.Azure.ServiceBus => new

Yep, I am mixing!  thanks!
