### ISSUE TITLE
Update the samples to use the latest version of the ASB client

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#567]
Currently it's targetting 2.x when 3.x is out.

**Comment by nemakam** [comment]
Is there a better way to do this rather than updating all samples everytime there's a new version?

**Comment by SeanFeldman** [comment]
Absolutely. That's what I've done in PR https://github.com/Azure/azure-service-bus/pull/230/files
It uses the major rather than a specific version. That's the best you could do with Nuget ATM.
