### ISSUE TITLE
Can't use MessageSender & MessageReceiver

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#57]
## Expected Behavior
Use `MessageSender` and `MessageReceiver` to send/receive messages. 

## Actual Behavior
Classes are abstract and cannot be used.

Version: [current master](https://github.com/Azure/azure-service-bus-dotnet/blob/fc95ccf00125fd7046b121aeb8ac5b025c1454c5/src/Microsoft.Azure.ServiceBus/MessageReceiver.cs#L12)
Commit: https://github.com/Azure/azure-service-bus-dotnet/commit/a34fbdb62eee0387ab9b08844c089a8ce5e32e26

**Comment by binzywu** [comment]
Hi @SeanFeldman, could you please elaborate a little more about the scenarios that you will need this?

**Comment by SeanFeldman** [comment]
Absolutely @binzywu 
When a process is receiving messages, it handles messages from queues and subscriptions. The process doesn't differentiate the entity type messages come from as messages contain information required for proper processing. Same is applied for sending, messages are sent out using a path, w/o differentiating if destination is a topic or a queue.

With both `MessageSender` and `MessageReceiver` abstract it is not possible with the new client.

**Comment by binzywu** [comment]
@SeanFeldman, @nemakam will be working on this.

**Comment by SeanFeldman** [comment]
👍 @binzywu 
I'll be following the PR the moment it shows up.

**Comment by nemakam** [comment]
You can track the changes in PR #82

**Comment by jtaubensee** [comment]
Closing in favor of #87

**Comment by nemakam** [comment]
Reopening the issue since MessageSender and MessageReceiver are made internal in #87 .

**Comment by jtaubensee** [comment]
Also, a reminder to rename the `Peek()` operation to `Browse()` in order to avoid confusion between `PeekLock` mode.

**Comment by SeanFeldman** [comment]
:-1: for `Browse`.
`Peek` is a well established term for the operation and means exactly what it does. Not to mention that other messaging and queueing technologies use the same nomenclature.

**Comment by jtaubensee** [comment]
Closing based on #146
