### ISSUE TITLE
QueueClient.RegisterSessionHandler (Error receiving messages from session-enabled queue)

### ISSUE THREAD

**Issue by saboco** [Azure/azure-service-bus-dotnet#576]
## Actual Behavior
1. Create a queueClient  (var queuClient = QueueClient(connectionString,queue);)
2. queue has been created with session enabled.
3. Register a SessionHandler via -> queueClient.RegisterSessionHandler(handler, sessionOptions)
4. Gettings this error: 
**It is not possible for an entity that requires sessions to create a non-sessionful message receiver.** 

## Expected Behavior
1. Since the name of the methode is RegisterSessionHandler and the implementation seems to be handling the session
2. Receive messages from any session

## Versions  
- OS platform and version: Windows 10 Pro 1709 Build 16299.125
- .NET Version: dotnetcore 2.1.402
- NuGet package version or commit ID:  Microsoft.Azure.ServiceBus 3.1

**Comment by nemakam** [comment]
@saboco  That seems interesting.
Is this partitioned or non-partitioned queue?
And is it consistent repro?

**Comment by nemakam** [comment]
Could you send a repro of your code? I just tried the scenario and it works as expected.

**Comment by saboco** [comment]
It is particioned.
I will send you a repro code as soon as possible.

**Comment by saboco** [comment]
In the mean time if it can helps this is the tracking identifiers:

TrackingId:a66038cc-5d03-4c0f-9463-4d795506a18f_B32,
Timestamp:9/25/2018 9:00:13 AM 
TrackingId:671be9b10e324592af6c77be1a41ed2d_G2,
SystemTracker:gateway7, 
Timestamp:9/25/2018 9:00:13 AM 
TrackingId:671be9b10e324592af6c77be1a41ed2d_G2, 
SystemTracker:gateway7, 
Timestamp:9/25/2018 9:00:14 AM

**Comment by nemakam** [comment]
> In the mean time if it can helps this is the tracking identifiers:

We will need namespace name along with tracking ID to make sense of it.

**Comment by saboco** [comment]
yes sorry:
SystemTracker:airbnb-api-dev:queue:listings_management/listing_creation~15,

**Comment by saboco** [comment]
This code reproduces the error every time:
https://github.com/saboco/azure-servicebus-example

**Comment by nemakam** [comment]
Have you tried running it on a different queue and see if it reproduces? It doesn't sound like a client issue. For service issues that you are facing on your namespace, its better to contact azure support

**Comment by saboco** [comment]
I ran this test in a newly created queue.
It should be the parameters I use for the creation.
I will contact azure support, thank you!

**Comment by nemakam** [comment]
@saboco 
I tried your code and it throws.
But it throws in the callback method where you complete/abandon the message
```csharp
| true -> return! queueClient.CompleteAsync(message.SystemProperties.LockToken)
| false -> return! queueClient.AbandonAsync(message.SystemProperties.LockToken)
```
Basically, you need to complete/abandon using the `session` object and not the `queueClient` object
