### ISSUE TITLE
MessageReceiver.CompleteAsync with empty list throws ArgumentNullException

### ISSUE THREAD

**Issue by WhiteRabbit68** [Azure/azure-service-bus-dotnet#579]
## Actual Behavior
1. CompleteAsync(new List&lt;string&gt;())
2. throws ArgumentException with "Value cannot be null" ParamName=lockTokens

This is misleading because the parameter is NOT null. Why is it an error to supply an empty list? Just return without doing anything.

## Expected Behavior
1. CompleteAsync(new List&lt;string&gt;())
2. No exception thrown

## Versions  
- OS platform and version: Windows
- .NET Version: Standard 2.0
- NuGet package version: 3.1.0

**Comment by SeanFeldman** [comment]
@WhiteRabbit68 while I don't disagree, it could go the other way - why don't you avoid unnecessary method invocation if there are no messages to complete? Worse if it's on the hot path.

Or would you prefer to see an exception with a different message that is more meaningful?

**Comment by SeanFeldman** [comment]
The exception message is indeed incorrect. Fixing that.
