### ISSUE TITLE
Max value of DuplicateDetectionHistoryTimeWindow incorrectly set to 1 day

### ISSUE THREAD

**Issue by LeroyK** [Azure/azure-service-bus-dotnet#592]
## Actual Behavior
1. Setting DuplicateDetectionHistoryTimeWindow to a value higher than 1 day throws an exception when trying to create a queue/topic:
`System.ArgumentOutOfRangeException: 'The value must be between 00:00:20 and '1.00:00:00'`

## Expected Behavior
1. A value up to 7 days is allowed according to Service Bus specs (https://docs.microsoft.com/en-us/azure/service-bus-messaging/duplicate-detection).

This can be fixed here:
https://github.com/Azure/azure-service-bus-dotnet/blob/58f08b7910a4dc1818dfb411d06c07bf8405a9e6/src/Microsoft.Azure.ServiceBus/Management/ManagementClientConstants.cs#L36

## Versions  
- OS platform and version: Windows 10
- .NET Version: Core 2.1.403
- NuGet package version or commit ID: 3.1.1

**Comment by SeanFeldman** [comment]
PR is pending.
