### ISSUE TITLE
Missing properties in QueueDescription, TopicDescription, and SubscriptionDescription

### ISSUE THREAD

**Issue by dshpak-iq** [Azure/azure-service-bus-dotnet#596]
## Actual Behavior
The `QueueDescription`, `TopicDescription`, and `SubscriptionDescription` objects do not contain fields representing the current state of the Service Bus entity, e.g. number of messages and size in bytes.

These values appear to be deliberately ignored: https://github.com/Azure/azure-service-bus-dotnet/blob/e5552e8cd2cb3072808ab306de164462bfd6c553/src/Microsoft.Azure.ServiceBus/Management/QueueDescriptionExtensions.cs#L144 (similar code exists in TopicDescriptionExtensions.cs and SubscriptionDescriptionExtensions.cs)

Because these values are being so explicitly ignored, I'm wondering: is there is a reason these have been excluded? They're available in the WindowsAzure.ServiceBus .NET Framework package.

## Expected Behavior
These values are deserialized from the API response and made available to the client.

## Versions  
- NuGet package version or commit ID: Observed in Nuget package 3.1.1. At time of writing, the dev branch has the same issue, and is at commit e5552e8cd2cb3072808ab306de164462bfd6c553

**Comment by SeanFeldman** [comment]
Those are captured in [`QueueRuntimeInfo`](https://github.com/Azure/azure-service-bus-dotnet/blob/e5552e8cd2/src/Microsoft.Azure.ServiceBus/Management/QueueRuntimeInfo.cs) and can be obtained via [`ManagementClient.GetQueueRuntimeInfoAsync()`](https://github.com/Azure/azure-service-bus-dotnet/blob/e5552e8cd2/src/Microsoft.Azure.ServiceBus/Management/ManagementClient.cs#L279).

Is that what you're looking for @dshpak-iq ?

**Comment by dshpak-iq** [comment]
Yes, that's exactly what I was looking for — thanks!
