### ISSUE TITLE
The operation did not complete within the allocated time exception

### ISSUE THREAD

**Issue by odysseus1973** [Azure/azure-service-bus-dotnet#597]
## Actual Behavior
1.  Sometimes receive exception in message handler, like

`The operation did not complete within the allocated time 00:01:00 for object request16. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:adc1727b-d95e-4f32-905a-17b98f0bbfff_G33, SystemTracker:NoSystemTracker, Timestamp:10/29/2018 2:23:36 PM`

## Expected Behavior
1.  Lock Timeout in queue set to 5 minutes. So this exception should not be thrown.

## Versions  
- OS platform and version: Windows Server 2016 (Service Fabric)
- .NET Version: .Net Core 2.1
- NuGet package version or commit ID: 3.02

**Comment by SeanFeldman** [comment]
@odysseus1973 exception with `TrackingId` could be troubleshooted with Azure support.
Providing `TrackingId:adc1727b-d95e-4f32-905a-17b98f0bbfff_G33` value to the support would help with understanding what went wrong with that specific request. Have you tried this route?

**Comment by axisc** [comment]
Please open a support ticket if you still see these issues.

Preferably a more recent tracking id will be helpful
