### ISSUE TITLE
5.0.1: "Strong name signature could not be verified"

### ISSUE THREAD

**Issue by TradePeg** [Azure/azure-service-bus-dotnet#601]
New [nuget package](https://www.nuget.org/packages/WindowsAzure.ServiceBus) 5.0.1 could not load with the following exception:

"Could not load file or assembly 'Microsoft.ServiceBus' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key."

Rolling back to 5.0.0 seems to solve this

**Comment by SeanFeldman** [comment]
Wrong repo. See https://github.com/Azure/azure-service-bus/issues/248, which is exactly for this issue.
