### ISSUE TITLE
IsLockTokenSet is always false

### ISSUE THREAD

**Issue by RockyBalboa2018** [Azure/azure-service-bus-dotnet#604]
i need to monitor locked messages in a subscription queue.
### Scenario
for my test, i have one message, and i lock it for 5 minutes by using the rest API via postman.
when i browse messages, IsLockTokenSet is set to false

```csharp
MessageReceiver receiver = new MessageReceiver(connectionString, entityPath);           
while (true)
{
	var message = await receiver.PeekAsync();
	if (message == null)
		break;
	bool isLocked = message.SystemProperties.IsLockTokenSet;
	// isLocked is always false...
}
```

**Comment by SeanFeldman** [comment]
From `IsLockTokenSet` XML documentation (remark section):

> A lock token will only be specified if the message was received using `ReceiveMode.PeekLock`

When you peek a message, you're not really receiving the message from the broker perspective. If anything, I'd argue `ReceiveMode` should have a third mode, `Peek`.

**Comment by RockyBalboa2018** [comment]
So there is no way to know if a message is currently locked ?
Informations like LockedUntilUtc, are updated only after the message is unlocked

**Comment by SeanFeldman** [comment]
> So there is no way to know if a message is currently locked (_by another competing consumer_)?

Correct.

> Informations like LockedUntilUtc, are updated only after the message is unlocked

Information such as `LockedUntilUtc`, `IsLockTokenSet`, and `LockToken` are there when a message is **received**.

**Comment by SeanFeldman** [comment]
Given this is a question and not an issue with the client, going to close this issue.
