### ISSUE TITLE
Provide a ValueTask return type for QueueClient.RegisterMessageHandler

### ISSUE THREAD

**Issue by bbougot** [Azure/azure-service-bus-dotnet#609]
Based on Stephen Toub's topic regarding ValueTask [here](https://blogs.msdn.microsoft.com/dotnet/2018/11/07/understanding-the-whys-whats-and-whens-of-valuetask/) it would be great considering adding/replacing the  QueueClient.RegisterMessageHandler return type as a ValueTask, which could vastly improve performances by reducing the amount of task allocations as the number of messages received grows.

**Comment by SeanFeldman** [comment]
@bbougot are you referring to the registered handler `Func` using `RegisterMessageHandler(Func<Message, CancellationToken, Task> handler, ...)`?

(This will also require .NET Standard 2.1 or [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions) package.)

**Comment by bbougot** [comment]
Yes absolutely.

**Comment by SeanFeldman** [comment]
In that case it could be also applied on `exceptionReceivedHandler` (that is only awaited internally)` to be converted from `Func<ExceptionReceivedEventArgs, Task>` to `Func<ExceptionReceivedEventArgs, ValueTask>` as well.

**Comment by SeanFeldman** [comment]
I've created a spike PR #611, but it really should be tested for performance improvements to assume using `ValueTask` will improve any performance. Would you like to take a stab at verifying performance impact @bbougot?

**Comment by bbougot** [comment]
@SeanFeldman Bench setup detailed [here](https://github.com/Azure/azure-service-bus-dotnet/pull/611#issuecomment-442026452).

**Comment by SeanFeldman** [comment]
Given the findings in the PR #611 and the fact that `ValueTask` should not be surfaced to the public API, I'm going to close this issue. Should you disagree with the decision @bbougot, please re-open and provide the reasons to continue on this route. Thanks.
