### ISSUE TITLE
SendAsync InvalidOperationException

### ISSUE THREAD

**Issue by AceHack** [Azure/azure-service-bus-dotnet#612]
## Actual Behavior
1. When calling SendAsync I sometimes get InvalidOperationException
![invalidoperation](https://user-images.githubusercontent.com/578953/49196572-737cd580-f359-11e8-927e-f772e4969de3.jpg)
System.InvalidOperationException: Can't create session when the connection is closing.
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at Arch.TestService.ServiceBusTest.RunAsync() in /build/src/Arch.TestService/ServiceBusTest.cs:line 131

## Expected Behavior
1. To always work when calling SendAsync

## Versions  
- OS platform and version: docker container microsoft/dotnet:2.1.5-aspnetcore-runtime-stretch-slim
- .NET Version: core 2.1.5
- NuGet package version or commit ID: 3.2.0

**Comment by axisc** [comment]
@AceHack - do you see this issue when sending messages after a long while. Inactive connections may be closed depending on how you set up the connection. 

could you share a repro?

**Comment by AceHack** [comment]
It’s random, I’m just sending a 20 byte message in a loop every one second.  Also there is a message lock exception that happens sometimes too.

**Comment by AceHack** [comment]
Also, the abstraction for TopicClient is an always working connection.  I should not see any errors unless there are actual network errors, it uses fault tolerant amqp connection underneath.  I'm using the default retry strategy as well so it should have handled this.

**Comment by SeanFeldman** [comment]
> Also there is a message lock exception that happens sometimes too.

Lock exception on a message sent out?

**Comment by axisc** [comment]
if you still see this issue, please open a support ticket. 
closing this issue for now.
