### ISSUE TITLE
Dependency of Microsoft.IdentityModel.Clients.ActiveDirectory 

### ISSUE THREAD

**Issue by xeo545x39** [Azure/azure-service-bus-dotnet#613]
Why 'Microsoft.Azure.ServiceBus 3.1.1' has dependency for Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.17.2 && < 4.0.0). I have a project with on .NET Framework 4.6.1 and Microsoft.IdentityModel.Clients.ActiveDirectory with version 4.3.0. I cannot use Microsoft.Azure.ServiceBus 3.1.1 because maximum supported version of ActiveDirectory library is 4.0.0. How to deal with it?

## Actual Behavior
1. I cannot use newest Microsoft.Azure.ServiceBus 3.1.1 because maximum supported Microsoft.IdentityModel.Clients.ActiveDirectory is wrong

## Expected Behavior
1. I should be able to attach Microsoft.Azure.ServiceBus 3.1.1 to my project

## Versions  
- OS platform and version: Windows 10
- .NET Version: Framework 4.6.1
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 3.1.1

**Comment by SeanFeldman** [comment]
Have you tried 3.2.0 version of the client? It has [dependency range updated](https://github.com/Azure/azure-service-bus-dotnet/blob/9b22eabf5a12789ea7fe1a792051a54522cc9583/src/Microsoft.Azure.ServiceBus/Microsoft.Azure.ServiceBus.csproj#L32).
