### ISSUE TITLE
RetryPolicy is causing transaction exception for connectivity issue

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#615]
When an ambient transaction exists, operations such as `SendAsync` [enlist into existing ambient transaction](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/86cf1b11ff45e99ed204bd8aebea1d3bec46bcac/src/Microsoft.Azure.ServiceBus/Core/MessageSender.cs#L533-L537). `RetryPolicy` is taking that operation later and [executes](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/86cf1b11ff45e99ed204bd8aebea1d3bec46bcac/src/Microsoft.Azure.ServiceBus/Core/MessageSender.cs#L250). When an operation is failing to execute due to **connectivity problems**, `RetryPolicy` re-executes that operation, which includes repeated transaction enlistment. This in turn throws an exception `System.InvalidOperationException: 'Local transactions are not supported with other resource managers/DTC.'` thrown by [`AmqpTransactionManager.EnlistAsync()`](https://github.com/SeanFeldman/azure-service-bus-dotnet/blob/86cf1b11ff45e99ed204bd8aebea1d3bec46bcac/src/Microsoft.Azure.ServiceBus/Amqp/AmqpTransactionManager.cs#L40), completely masquerading connectivity problem.

<details>
<summary>Stacktrace</summary>
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageSender.cs:line 562
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\RetryPolicy.cs:line 83
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\RetryPolicy.cs:line 105
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageSender.cs:line 252
   at ReproApp.Program.Main(String[] args) in C:\Users\Sean\Desktop\RetryPolicyRepro\ReproApp\Program.cs:line 33
   at ReproApp.Program.<Main>(String[] args)
</details>

## Expected Behavior
1. Operation retried due to connectivity problem should not fail with incorrect transaction exception
1. Transaction for the same operation should not be enlisted more than once

## Steps to reproduce this issue:
1. Run the following code (bellow, available at this [repo](https://github.com/SeanFeldman/RetryPolicyRepro))
1. Block the outgoing TCP port 5671

```c#
static async Task Main(string[] args)
{
    var connectionString = Environment.GetEnvironmentVariable("AzureServiceBus_ConnectionString");

    var management = new ManagementClient(connectionString);

    if (!await management.QueueExistsAsync("queue"))
    {
        await management.CreateQueueAsync("queue");
    }

    var sender = new MessageSender(connectionString, "queue");

    while (true)
    {
        using (var tx = new TransactionScope(TransactionScopeOption.RequiresNew, TransactionScopeAsyncFlowOption.Enabled))
        {
            Debugger.Break();
            await sender.SendAsync(new Message(Encoding.Default.GetBytes(DateTime.Now.ToString("s"))));
            tx.Complete();
        }
    }

    await management.CloseAsync();
    await sender.CloseAsync();
}
```

## Versions  
- OS platform and version: Windows 10
- .NET Version: .NET Framework 4.6.1 / .NET Core 2.2
- NuGet package version or commit ID: 3.2.0

**Comment by SeanFeldman** [comment]
Unfortunately it’s difficult for me to provide exact numbers related to how many of our customers this impacts, but just from an anecdotal perspective, just yesterday we had support cases related to this exception from 3 separate customers.

**Comment by nemakam** [comment]
Well, for transactions, you cannot really have a retry within the same transaction.
The only way out would be to use `RetryPolicy.None` and have an uber retry outside of the transaction. Within a transaction its difficult to even define a retry. The first retry needs to fail. 
The fix we will have to do in SDK is to throw an exception if they have a retry policy set within a transaction.

**Comment by SeanFeldman** [comment]
SBMP client did not have this issue. How did this work with SBMP client?

**Comment by SeanFeldman** [comment]
Looks like the old client didn't have this issue and was bubbling connectivity exception right away (`MessagingCommunicationException`). I've added a second project with the old client to show that.

There's another problem with applying `RetryPolicy` the way it is today - if an `operation` passed to retry policy is containing a `using(){}` statement, any disposable resources in that statement will be release upon first execution and subsequent execution of the `operation` will run into `ObjectDisposedException`.
