### ISSUE TITLE
CreateQueueAsync creates 16 GB queue by default

### ISSUE THREAD

**Issue by flacidsnake** [Azure/azure-service-bus-dotnet#619]
## Actual Behavior
1. MaxSizeInMB not set. When queue is created, size is 16 GB
2. When MaxSizeInMB is set to 2048, the size of the created queue is 32 GB

## Expected Behavior
1. Queue size should be 1 GB

## Versions  
- OS platform and version:Windows 10 Pro 1803
- .NET Version:4.6.1
- NuGet package version or commit ID:3.2.0

`Microsoft.Azure.ServiceBus.Management.ManagementClient sbManager = new Microsoft.Azure.ServiceBus.Management.ManagementClient(asbConnectionString);
Microsoft.Azure.ServiceBus.Management.QueueDescription newQueue = new Microsoft.Azure.ServiceBus.Management.QueueDescription("queueName");
newQueue.EnableDeadLetteringOnMessageExpiration = true;
newQueue.EnablePartitioning = true;
newQueue.LockDuration = new TimeSpan(0, 0, 30);
newQueue.MaxDeliveryCount = 10;
newQueue.MaxSizeInMB = 1024; // Default value

newQueue = await sbManager.CreateQueueAsync(newQueue);
`

**Comment by flacidsnake** [comment]
Ok, I tried the same code without enabling partitioning and now the maximum size is 1 GB

**Comment by SeanFeldman** [comment]
This is normal behaviour in standard tier.
16 partitions multiply entity size.
See this d [ocument](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning) for more info. Except it has a [mistak(https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#feedback) 🙂
