### ISSUE TITLE
Feature request: Need to be able to obtain number of messages in queues and topics in ServiceBus from .NET Core project

### ISSUE THREAD

**Issue by Andrey-Anatolyevich** [Azure/azure-service-bus-dotnet#620]
## Actual Behavior
1. Have no way of obtaining count of how many messages there is in queues and topics' subscriptions

## Expected Behavior
1. Need to be able to get number of messages in queues and topics using this library on top of .NET Core project

## Versions  
- OS platform and version: Ubuntu 18.4
- .NET Version: 2.2.101
- NuGet package version or commit ID: 3.2.0

Comment:
It is so frustrating to see such basic functionality cut for "So much loved by Microsoft" NetStandard compatible library as opposed to **Windows**Azure.ServiceBus, which is for WINDOWS only!
Guys, it pisses off and pushes faar-far away from any of your products.

**Comment by SeanFeldman** [comment]
Don't get frustrated @Andrey-Anatolyevich.
You can find message counts under `ManagementClient.GetQueueRuntimeInfoAsync` and similar. Cheers.

**Comment by Andrey-Anatolyevich** [comment]
@SeanFeldman, Thank you for fast response. Also, could you advice a code snippet by a chance?
This is what I see in suggested class & method result:
![image](https://user-images.githubusercontent.com/9977125/49908995-d8442f80-fe31-11e8-9125-6ff770544b96.png)
It doesn't look like the result has any details on queue size.

I feel like I'm missing something big and obvious whereas working with WindowsAzure.ServiceBus was very smooth and intuitive.

**Comment by Andrey-Anatolyevich** [comment]
![image](https://user-images.githubusercontent.com/9977125/49959246-ee013580-fec1-11e8-89c0-4f7080878a1d.png)

@SeanFeldman, Thank you. I got the counts.

Snippet for those, who might struggle as well:
`var mgmtClient = new ManagementClient(connectionString);`
`var runtimeInfo = mgmtClient.GetQueueRuntimeInfoAsync("[QUEUE-NAME]").GetAwaiter().GetResult();`
`var activeCount = runtimeInfo.MessageCountDetails.ActiveMessageCount;`
`var deadletterCount = runtimeInfo.MessageCountDetails.DeadLetterMessageCount;`
`var transferCount = runtimeInfo.MessageCountDetails.TransferMessageCount;`
