### ISSUE TITLE
Package version conflict with Microsoft.Net.Sdk.Functions

### ISSUE THREAD

**Issue by NathanYukai** [Azure/azure-service-bus-dotnet#627]
## Package version conflict with Microsoft.Net.Sdk.Functions in .NET Core
The Functions package requires: Microsoft.Azure.WebJobs (>= 3.0.0 && < 3.1.0) for .NETStandard, 
while this package requires the beta version of WebJobs for .NETStandard.

How can I use both packages in my project?
Thanks.

**Comment by SeanFeldman** [comment]
@NathanYukai `Microsoft.Azure.ServiceBus` has no dependency on `Microsoft.Azure.WebJobs` package and vice versa. 

[Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/):
![image](https://user-images.githubusercontent.com/1309622/50708741-a3875a80-1022-11e9-9d92-98cb5f87ad7a.png)

[Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus)
![image](https://user-images.githubusercontent.com/1309622/50708766-c285ec80-1022-11e9-942e-15b508c0a962.png)

Could you please provide more details about the issue you're having?

**Comment by SeanFeldman** [comment]
Unless you're referring to [`Microsoft.Azure.WebJobs.ServiceBus`](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus/) which takes a dependency on `Microsoft.Azure.ServiceBus` in its latest beta versions. In that case you'd need to raise an issue with [WebJobs SDK](https://github.com/Azure/azure-webjobs-sdk) project.

**Comment by NathanYukai** [comment]
> Unless you're referring to [`Microsoft.Azure.WebJobs.ServiceBus`](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus/) which takes a dependency on `Microsoft.Azure.ServiceBus` in its latest beta versions. In that case you'd need to raise an issue with [WebJobs SDK](https://github.com/Azure/azure-webjobs-sdk) project.

Ah, you are right, thanks!

**Comment by SeanFeldman** [comment]
np.
