### ISSUE TITLE
QueueClient RegisterMessageHandler to non-existent queue name causes an infinite number of exceptions to be raised

### ISSUE THREAD

**Issue by bryancrosby** [Azure/azure-service-bus-dotnet#632]
I have tried settings the `RetryPolicy` when creating the `QueueClient` but to no avail. Now I know, obviously, we can create the queue if it does not exist, and I appreciate the detailed exception message. However, would it be possible to not have the framework infinitely retry connecting to a non-existent queue?

Sample below
```c#
var queueClient = new QueueClient(queueConnection, "queue-that-doesnt-exist");

queueClient.RegisterMessageHandler(instance.HandleAsync, new MessageHandlerOptions(
	async ex =>
	{
		//This is invoked infinitely
	}));
```

## Actual Behavior
1. When creating a new instance of `QueueClient` and calling `RegisterMessageHandler` to a non-existent queue, an infinite number of exceptions are thrown stating that the queue does not exist.

(connection path and queue name redacted below)

Put token failed. status-code: 404, status-description: The messaging entity 'sb://xxx.servicebus.windows.net/queue-name' could not be found. TrackingId:18339d54-88c9-4578-a027-4a8bf461def6_G40, SystemTracker:xxx.servicebus.windows.net:queuename, Timestamp:2019-01-16T21:32:56.

## Expected Behavior
1.  One exception is thrown and is not retried, because the exception is not transient.

## Versions  
- OS platform and version: Debugging on Windows 10 10.0.15063
- .NET Version: 4.6.1
- NuGet package version or commit ID:   Microsoft.Azure.ServiceBus version 3.2.1

**Comment by SeanFeldman** [comment]
@bryancrosby can see how a constantly thrown `MessagingEntityNotFoundException` might feel unnecessary at first. What you're are suggesting is that if entity is not found, throw exception once and never do it again. Does it mean the pump should shutdown since it only works with a single entity that is not found? That does start feeling a bit dangerous.

The intent behind message pump is to continuously receive a stream of messages from a defined entity. If entity doesn't exist, then there's something fundamentally wrong. I'd rather see user code decide what to do with that by either shutting down the pump/host or making any other decision on how to handle this critical issue.  But not the client muting exception after it has been thrown. Thoughts?

**Comment by bryancrosby** [comment]
> @bryancrosby can see how a constantly thrown `MessagingEntityNotFoundException` might feel unnecessary at first. What you're are suggesting is that if entity is not found, throw exception once and never do it again. Does it mean the pump should shutdown since it only works with a single entity that is not found? That does start feeling a bit dangerous.
> 

I can see your point, it could potentially be a slippery slope. Do you think the `IsTransient` property is the most clear way to communicate this to clients?

Or, perhaps the currently assigned retry policy to the queue client (or a separate connection based retry policy) could be honored in this case?

> The intent behind message pump is to continuously receive a stream of messages from a defined entity. If entity doesn't exist, then there's something fundamentally wrong. I'd rather see user code decide what to do with that by either shutting down the pump/host or making any other decision on how to handle this critical issue. But not the client muting exception after it has been thrown. Thoughts?

I pretty much agree with you here. Ideally, exceptions should be obvious. Do you think there would be any benefit for a circuit breaker here? Infinitely throwing exceptions when there is no hope of any normal operation just sounds a tad preventable IMHO. Agree with you though that the users ultimately need to handle them.

**Comment by SeanFeldman** [comment]
> I can see your point, it could potentially be a slippery slope. Do you think the `IsTransient` property is the most clear way to communicate this to clients?

Exception callback receives `ExceptionReceivedEventArgs`. Which provides all the data necessary to understand what error has taken place. The `Exception` property in this case will be of type `MessagingEntityNotFoundException`. As any `ServiceBusException`, `MessagingEntityNotFoundException` will have its `IsTransient` property set to `false`, indicating that retrying will not help. This information is intended for users of the ASB client, and is fairly accepted way of responding to exceptions raised by the client.

> Or, perhaps the currently assigned retry policy to the queue client (or a separate connection based retry policy) could be honored in this case?

The way I see it, `RetryPolicy` should not be involved here. It's not even always enabled. Anyone could turn it off and then it not play any role in taking the decision wherever message pump execution should or should not be paused/stopped.

> Do you think there would be any benefit for a circuit breaker here? Infinitely throwing exceptions when there is no hope of any normal operation just sounds a tad preventable IMHO. Agree with you though that the users ultimately need to handle them.

Thinking out loud: anyone registering a callback is going to expect a stream of messages coming in for processing. These messages would be coming from a single queue (per message pump). Assuming it's a project that does at minimum some sort of logging, the problem will be resolved quickly if such an important entity (queue or subscription) does not exist. 

Let's focus not on the message pump for a second, but on the entity. Before messages can be received, they need to be **sent** to that entity. I suspect that would fail even earlier than the receiving party if entity is not found. And this has nothing to do with the issue we're discussing, right? Which brings me back to the idea I was conveying in my earlier comment - this is not a message pump concern. The entity needs to be provisioned _prior_ to any operation, sending or receiving, taking place. Starting from lower environments (dev/QA) and all the way to production. Exception callback for message pump should respond to one off exceptions, but expect to be executed continuously. A circuit breaker would not help as the missing entity would not show up, it's probably missing for a reason it was not there (or got deleted, which is bad on its own). But I can see how your error callback take control of things and make a decision what should happen to the process that essentially doesn't do what it supposed to be doing.

Hope my write-up makes sense 🙂

**Comment by bryancrosby** [comment]
Appreciate your thoughtful perspective. I'm ok with checking the `MessagingEntityNotFoundException` property and then shutting down the pump or taking some other action.
