### ISSUE TITLE
OnMessageCallback functionality missing in Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by james-novino** [Azure/azure-service-bus-dotnet#634]
We have legacy code that subscribes to a queue on Azure Service Bus that was written using the WindowsAzure.ServiceBus library. We are developing new code in .Net Core aganist Microsoft.Azure.ServiceBus to send and consume from topics. However, there doesn't seem to be any corresponding functionality in Microsoft.Azure.ServiceBus for something like this : 

```
member x.ConcurrentMessageRetrieval<'In, 'Out> 
        (decoder: Message -> Async<'In>,
         handler: 'In -> Async<'Out>, 
         beforeMessageComplete: 'Out -> Async<unit>,
         duringMessageComplete: 'Out -> Async<unit>,
         afterMessageComplete: bool -> 'Out -> Async<unit>,
         maxConcurrency: int) =
         
        receiveClient.OnMessageAsync(
            Func<BrokeredMessage, Task> (
                x.OnMessageCallback 
                    decoder 
                    handler 
                    beforeMessageComplete
                    duringMessageComplete
                    afterMessageComplete),
            new OnMessageOptions(AutoComplete = false, MaxConcurrentCalls = maxConcurrency) 
        )
```
We have an implemention that is heavily reliant on the fact that we can execute callbacks both before, during and after message completion. 

I had noted there were some issues with earlier versions of the .Net Core library but it wasn't clear if a workaround existed or not (particularly that didn't require rework of legacy code).

## Actual Behavior
1. Unable to register callbacks for message completions
2. Insufficient examples for how to deal with concurrent consumption of Service Bus Queues

## Expected Behavior
1. The ability or corresponding functionality to the OnMessageAsync functionality in WindowsAzure.ServiceBus
2. Improved examples for consuming from queues concurrently or in Batches

## Versions  
- OS platform and version: Windows 10 & Windows Server 2012
- .NET Version:  .Net Framework 4.6.1 & .Net Core 2.0
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus (3.2.1)

**Comment by SeanFeldman** [comment]
@james-novino `RegisterMessageHandler` on both `QueueClient` and `SubscriptionClient` does exactly that. Have you examined it?

Readme.md calls has a [section for samples](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/README.md#where-can-i-find-examples-that-use-this-library). Two of those do exactly [what you ask](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/Program.cs).

 Except certain things that I didn't quite understand how you've achieved with the old client. Specifically: decoder and  before/during/after. That feels to me like your in-house customization.

**Comment by james-novino** [comment]
I was able to figure out how to do it using the RegisterMessageHandler, after some additional investigation. Thank you, @SeanFeldman feel free to close the issue.
