### ISSUE TITLE
Management client doesn't return correct NamespaceInfo

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#637]
Two issues:

1. `ManagementClient.GetNamespaceInfoAsync()` invocation for premium tier never returns number of MUs.
2. `NamespaceType` is always `NamespaceType.Others` as broker returns `Messaging` for ASB namespaces, not `ServiceBus`.

This is a broken functionality as it doesn't do what it supposed.

Tested version: 3.3.0

Running simple test on standard and premium namespaces returns the following:

![image](https://user-images.githubusercontent.com/1309622/51653954-f03fc080-1f52-11e9-98c5-03bc90c15a4a.png)

**Comment by axisc** [comment]
@SeanFeldman - thanks for reporting this. Agree that this is a bug. will have the team investigate.

**Comment by SeanFeldman** [comment]
@axisc FYI there's an ongoing PR #638 for this issue

**Comment by axisc** [comment]
Ah, missed that ! 😀
