### ISSUE TITLE
Question: what name requirements are defined a connectionstring, queue-name, topic-name and subscription-name?

### ISSUE THREAD

**Issue by StefH** [Azure/azure-service-bus-dotnet#651]
## Question
The ConnectionString, queue-name, topic-name and subscription-name are following a validation pattern. Which regex is used to validate these?

I want to apply a regular expression attribute on my **Options** class which defines the fields for ConnectionString, queue-name, topic-name and subscription-name.

**Comment by SeanFeldman** [comment]
I would advise against your own validation and let the broker do it for you. But if you insist, [queue](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-queues-and-metadata)

**Comment by SeanFeldman** [comment]
Same with the connection string. Let [`ServiceBusConnectionStringBuilder`](https://github.com/Azure/azure-service-bus-dotnet/blob/b70ddf652c4c520fc127407be209b0811bcc50ce/src/Microsoft.Azure.ServiceBus/ServiceBusConnectionStringBuilder.cs#L280) do the work.
