### ISSUE TITLE
Question - How to abandon a queue message with some updates to UserProperties?

### ISSUE THREAD

**Issue by vanthoainguyen** [Azure/azure-service-bus-dotnet#655]
I attempt to requeue/defer a message due to some application logic by doing this

```
var retryTimespan = TimeSpan.FromMinute(1);
message.UserProperties["RetryCount"] = retryCount++;
await _queueClient.AbandonAsync(lockToken, new Dictionary<string, object>
    {
        {nameof(Message.ScheduledEnqueueTimeUtc), DateTime.UtcNow.Add(retryTimespan)},
        {nameof(Message.UserProperties), message.UserProperties}
    });
```

## Actual Behavior
1.  The library throw SerializationException as seen in AmqpMesageConverted.TryGetAmqpObjectFromNetObject method

## Expected Behavior
1. The message should be abandon and next time when it is delievered in next 1 minute, the delivered message should have message.UserProperties["RetryCount"] set with value higher than last time.

If it is not the recommended way, please suggest alternative approach. Thanks.

## Versions  
- OS platform and version: Tested during development on WINDOWS 10
- .NET Version: .NET core 2.1.5
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 3.3.0

**Comment by SeanFeldman** [comment]
@vanthoainguyen when you abandon a message, you have to provide a dictionary of primitives. `message.UserProperties` is not a primitive and contains all the properties already found on the message you've received.

**Comment by SeanFeldman** [comment]
To get a faster response, it's would be better to post questions such as this one at forums similar to [StackOverflow](http://stackoverflow.com). You'd receive the [answer above](https://github.com/Azure/azure-service-bus-dotnet/issues/655#issuecomment-469745360) and [additional information](https://weblogs.asp.net/sfeldman/azure-service-bus--abandon-with-reason) to get your answer. The issue tracker here is mostly intended for bugs and features.
