### ISSUE TITLE
.Net Core version of receiving message session from a queue

### ISSUE THREAD

**Issue by harryariyanto** [Azure/azure-service-bus-dotnet#678]
Hi, i have this code which works perfectly on the full .Net Framework to retrieve all message sessions from the specified queue name.
 `var queueClient = QueueClient.CreateFromConnectionString(AppSettings.ServiceBusConnection, queueName);`
         `   var sessions = await queueClient.GetMessageSessionsAsync();`
          `  return sessions;`

But when i'm trying to implement the code to .Net Core framework, it give me the following error:

> Could not load type &#x27;System.UriTemplate&#x27; from assembly &#x27;System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&#x27;.

Is there any way to retrieve the message sessions from the specified queue on .Net Core?

Thanks.

**Comment by axisc** [comment]
Look at [SessionClient](https://github.com/Azure/azure-service-bus-dotnet/blob/dee85b66b464a297452578fcced526d0806cf8c5/src/Microsoft.Azure.ServiceBus/ISessionClient.cs)

Closing this - please reopen if there are further questions
