### ISSUE TITLE
Object reference not set to an instance of an object (while Send and Recv) on develop

### ISSUE THREAD

**Issue by dmasur** [Azure/azure-service-bus-dotnet#679]
## Actual Behavior
My Applications is behind a corporate firewall and i want to use amqp with websockets and a proxy (thx for the feature in 3.4.0). But i get an Exception every time i try to send or receive messages.

## Expected Behavior
Send and Receive Messages are working

## Versions  
- OS platform and version: Windows 8.1
- .NET Version: Core 2.2
- NuGet package version or commit ID: 3.4.0 / develop

I tried to use the packages direct instead of NuGet to get a better Callstack.
The Error is in WebSocketTransport.cs Line 72:

`Task task = this.webSocket.SendAsync(buffer, WebSocketMessageType.Binary, true, CancellationToken.None);`

Latest CallStack:
```
   at System.Net.WebSockets.ClientWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Transport.WebSocketTransport.WriteAsync(TransportAsyncCallbackArgs args) in C:\Users\User\Desktop\azure-amqp-2.4.0\Microsoft.Azure.Amqp\Amqp\Transport\WebSocketTransport.cs:line 72
   at Microsoft.Azure.Amqp.AsyncIO.AsyncBufferWriter.Write(TransportAsyncCallbackArgs args) in C:\Users\User\Desktop\azure-amqp-2.4.0\Microsoft.Azure.Amqp\Amqp\AsyncIO.cs:line 812
```

This is the state of the WebSocketObject:
![2019-03-27 16_42_31-HrApi (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/83548/55090465-6fff1e00-50af-11e9-8bfa-64c70e067a89.png)

Is there anything i can try or test for more infos?

**Comment by SeanFeldman** [comment]
2.4.0 is an outdated version. The latest 3.4.0 can be found here: https://github.com/Azure/azure-service-bus-dotnet/releases/latest

**Comment by dmasur** [comment]
@SeanFeldman yes you are right. Sorry I use 2.4.0 from azure-amqp and 3.4.0 and develop from azure-service-bus

My mistake with mixing this.

**Comment by axisc** [comment]
@dmasur  - are you able to repro without the proxy?

If it doesn't repro without the proxy setup, then consider browsing through the code [here](https://github.com/dotnet/corefx/blob/1ae46a2b2a7719e0fd8d30b5df14b7e181d1c963/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs#L161) to perhaps help debug your setup.

Closing it for now. Please reopen if needed.
