### ISSUE TITLE
Extend API for BrokeredMessage: IsReceived bool property

### ISSUE THREAD

**Issue by snboisen** [Azure/azure-service-bus-dotnet#68]
The BrokeredMessage API is problematic in the sense that there are several public properties that may throw exceptions, when attempting to read them. This includes all the properties that are only available for a BrokeredMessage that has been sent by Service Bus.

## Scenario ##

I am currently attempting to write a generic WebAPI MediaTypeFormatter for BrokeredMessage. With the current API, this leads to ugly code:
```csharp
public static bool IsReceived(BrokeredMessage message)
{
    try
    {
        int dummy = message.DeliveryCount;
        return true;
    }
    catch (InvalidOperationException)
    {
        return false;
    }
}
```

## API proposal ##
I propose to add a new property:
```csharp
bool IsReceived { get; }
```

The definition would be: `IsReceived` will return `true` if and only if `ThrowIfNotReceived` does not throw. Or by the current implementation, if `receiverHeaders != null`.

**Comment by binzywu** [comment]
@snboisen mind to explaining a little more of your scenario?

**Comment by snboisen** [comment]
Sure! We have an ASP.NET WebAPI webservice running in Azure App Service. It uses Azure Service Bus queues to communicate with an App Service WebJob.

I am adding some diagnostic calls to the service, so that I can inspect the queues and peek on the messages they contain. So I have written a WebAPI `MediaTypeFormatter` for serializing the messages along with their headers.

It is when I serialize the headers, that I currently need the ugly try/catch hack, since the formatter don't know - and should not care - about where the messages came from. It should be able to handle newly created unsent messages (useful for testing) as well as messages received from Service Bus.

**Comment by jtaubensee** [comment]
@snboisen - We should be able to expose this functionality pretty easily, by making the `BrokeredMessage.IsLockTokenSet` property public. Expect this by our first NuGet package release.

**Comment by SeanFeldman** [comment]
@jtaubensee this could be a community contribution with a bit of guidance from the team 😉

**Comment by SeanFeldman** [comment]
`BrokeredMessage.IsLockTokenSet` vs `BrokeredMessage.IsReceived` reads very differently. This is where I'd agree with @snboisen that from a user point of view, `IsReceived` makes more sense.

Also, `IsLockTokenSet` cannot be used. When in `DeleteAndReceive`, a message that is _recieved_ will have `IsLockTokenSet = false`. Which is wrong, since message was received.

I'm working on PR #78 for this.

**Comment by snboisen** [comment]
@jtaubensee As @SeanFeldman wrote, IsLockTokenSet will not match the desired definition, since a Peek'ed message should return false from IsLockTokenSet even if it is received and received headers such as DeliveryCount are available.

But with that said, I would actually also like to see IsLockTokenSet made public, since that would allow me to get rid of more ugly code:

```csharp
        private static bool CanAccessLockProperties(BrokeredMessage message)
        {
            try
            {
                DateTime dummy = message.LockedUntilUtc;
                return true;
            }
            catch (InvalidOperationException)
            {
                return false;
            }
        }
```

So in summary, I would like to see both an IsReceived and an IsLockTokenSet on the public API surface.
