### ISSUE TITLE
Add appropriate Retry policies

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#7]
_From @vinaysurya on October 12, 2016 2:13_

_Copied from original issue: Azure/azure-messaging-dotnet#11_

**Comment by jtaubensee** [comment]
Doing some cleanup @SeanFeldman - Is this what you were looking for?
https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Primitives/RetryPolicy.cs

**Comment by SeanFeldman** [comment]
👍 good to close

**Comment by jtaubensee** [comment]
Oops. This isn't actually complete yet. @SeanFeldman - Asleep at the wheel there, huh?

**Comment by SeanFeldman** [comment]
I'm a co-pilot at best.
But yes, my bad.

**Comment by nemakam** [comment]
PR #110 implements this.
