### ISSUE TITLE
Failing CI / Unit Tests

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#73]
These tests are currently failing in AppVeyor:
* .NET Core:
  * QueueClientTests.BasicRenewLockTest("non-partitioned-queue")
  * QueueClientTests.BasicRenewLockTest("partitioned-queue")
  * QueueClientTests.PeekLockDeferTest("partitioned-queue")
  * TopicClientTests.TopicClientRenewLockTestCase("non-partitioned-topic")
  * TopicClientTests.TopicClientRenewLockTestCase("partitioned-topic")
  * TopicClientTests.TopicClientPeekLockDeferTestCase("non-partitioned-topic")
  * TopicClientTests.TopicClientPeekLockWithAbandonTestCase("partitioned-topic")
* .NET 4.5.1
  * QueueClientTests.PeekLockWithAbandonTest("non-partitioned-queue")
  * QueueClientTests.PeekLockWithAbandonTest("partitioned-queue")
  * QueueClientTests.PeekLockDeferTest("partitioned-queue")
  * TopicClientTests.TopicClientPeekLockWithAbandonTestCase("non-partitioned-topic")

Here are the details of the tests: https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.79/tests

**Comment by vinaysurya** [comment]
@jtaubensee, sent a fix for what I think was causing this issue

https://github.com/Azure/azure-service-bus-dotnet/pull/74/files

**Comment by jtaubensee** [comment]
The latest build passed: https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.86
