### ISSUE TITLE
PR builds do not log (execute?) tests

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#79]
## Expected Behavior

To see test results

## Actual Behavior

> The build job has not produced any test results.

Example: [sample output](https://ci.appveyor.com/project/jtaubensee/azure-service-bus-dotnet/build/1.0.138/tests)

**Comment by jtaubensee** [comment]
@SeanFeldman - This is part of the AppVeyor build model. We use secure environment variables, that could be potentially exposed with a Console.WriteLine in the unit tests. Thats why we do not build public PR's and any development from our team is done on a branch in this repo (allowing it to be built).

**Comment by SeanFeldman** [comment]
@jtaubensee wasn't this addressed by the fact that each build spins up and tears down a new namespace?

**Comment by jtaubensee** [comment]
No, because there are still credentials that are tied to our Azure Active Directory App, and are consistent between builds.
