### ISSUE TITLE
Simple vs. advanced API set

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#87]
Created a new issue from #57.

Since this is a new client, our team has taken some time to reevaluate the current usage of our past library, and we want to make this new one as simple as possible. In order to do so, we are planning to use clients (i.e. Queue, Topic, Subscription) for general messaging scenarios, while using message senders/receivers for more advanced scenarios. As such we are proposing the following:

* Keep clients in the root namespace, and move sender/receivers to a separate namespace. We would like to keep the root namespace as simple as possible, allowing new customers to get started quickly without the need to learn too many concepts.
* Limit clients to a message pump model (i.e. `OnMessage`), and reserve direct receive calls for the `MessageReceiver`.
* Remove static create methods from the clients, and instantiate them through constructors.
* Some sort of connection pooling for clients, and allow customers to implement their own pooling algorithms for senders/receivers (this would come much later though).

After some initial investigation, the QueueClient interface can look something like this:
```csharp
    public interface IQueueClient
    {
        public IQueueClient(string connectionString, ReceiveMode mode);   
        public string QueueName;
        public ReceiveMode Mode;
        public int PrefetchCount;    
        public Task CloseAsync();
        public Task SendAsync(BrokeredMessage message);
        public Task SendAsync(IList<BrokeredMessage> messages);
        public Task CompleteAsync(Guid lockToken);
        public Task AbandonAsync(Guid lockToken);
        public Task DeferAsync(Guid lockToken);
        public Task DeadLetterAsync(Guid lockToken);
        public Task<long> ScheduleMessageAsync(Message message, DateTimeOffset scheduledEnqueueTimeUtc);
        public Task CancelScheduledMessageAsync(long sequenceNumber);
        public void RegisterMessageHandler(OnMessageOptions options, Func<BrokeredMessage, Task>);
        public void RegisterSessionHandler(OnSessionOptions options, Func<Session, Task>);
    }
```
Other functionality that exisits in the .NET API today, that is not in the QueueClient above would then live in either `MessageSender` or `MessageReceiver`.

**Comment by SeanFeldman** [comment]
> Keep clients in the root namespace, and move sender/receivers to a separate namespace. We would like to keep the root namespace as simple as possible, allowing new customers to get started quickly without the need to learn too many concepts.

> Remove static create methods from the clients, and instantiate them through constructors.

> Some sort of connection pooling for clients, and allow customers to implement their own pooling algorithms for senders/receivers (this would come much later though).

👍 



@jtaubensee are you omitting the following on purpose from client?

- `Path`
- `AbandonAsync(Guid, IDictionary<String, Object>)`
- `DeadLetterAsync(Guid, string, string) / DeadLetterAsync(Guid, IDictionary<String, Object>)`
- `DeferAsync(Guid, IDictionary<String, Object>)`
- `FormatDeadLetterPath(String)`

And the following:
- Batching
- Sessions
- `PeekAsync(*)`
- `SendAsync(BrokeredMessage)`
- `SendBatchAsync(*)`

will be handled with `MessageSender/Receiver`?

> Limit clients to a message pump model (i.e. OnMessage), and reserve direct receive calls for the MessageReceiver.

Question I'd ask the team is you think for a persona that starts with ASB, is `OnMessage` pump a simpler concept than send/peek/receive individual message?

**Comment by jtaubensee** [comment]
Hey @SeanFeldman,

I think the goal is to start with the simplest API possible. And worst case scenario, we can always add something back in. I think the most important piece is that we establish, that the clients are the simple Service Bus programming model, and Sender/Receiver are for more advanced scenarios.

Regarding:
> @jtaubensee are you omitting the following on purpose from client?
Yes, we are. At least to start with. These would still be available in the Sender/Receiver.

and for:
> will be handled with MessageSender/Receiver?
* Batching - Sending batches will be supported with `SendAsync(IList<BrokeredMessage> messages);`, but receiving batches will not be supported as the only receive model is `OnMessage`.
* Sessions - The SessionHandler is in the clients
* Peek/Browse is reserved for the Sender/Receiver

Lastly, I think that for a simple console application, receive may be easier, but OnMessage is a much better way to go for any long running application. We often times see customers write their own receive pumps incorrectly.

**Comment by jtaubensee** [comment]
This was completed in #95 and the next steps of this are:
* #57 - Updating the `MessageSender` and `MessageReceiver`
* #98 - `Message` refactoring

**Comment by markbeij** [comment]
While upgrading my Azure Function from V1 to V2, I stumbled upon missing a method like to use:
`BrokeredMessage.DeadLetterAsync(string, string)`. The idea of spitting simple and advanced API set is great, but how should I deal with this situation?
I used this function to be able to add Dead letter reason and description when the last attempt failed. If I don't do this, I get MaxDeliveryCountExceeded, which is not telling me much.
Hope to learn the right approach for this situation.

**Comment by SeanFeldman** [comment]
API is not missing. It has changed.
The new client no longer allows operations on `Message`s directly. Instead, you need to go through specific clients that have received those messages. 

So to achieve that, you'd need something like this:
`await queueClient.DeadLetterAsync(message.SystemProperties.LockToken, reason, description);`

**Comment by markbeij** [comment]
Thanks, I will try that

**Comment by markbeij** [comment]
But how to get to the client from within an Azure Function?

I can't create another client object and pass the lock token in there like this:

```
[FunctionName("MyFunction")]
public static async Task Run([ServiceBusTrigger("mytopic", "mysubscription", Connection = "ConnectionString")]Message message, ILogger log)
{
    log.LogInformation($"C# ServiceBus topic trigger function processed message: {message}");

    var connection = new ServiceBusConnectionStringBuilder("sb://myendpoint", "mytopic/mysubscription", "MySharedAccessKey", "MySharedAccessKey");
    var client = new SubscriptionClient(connection, "MMS-Bevestigingsmail");
    await client.DeadLetterAsync(message.SystemProperties.LockToken, "deadLetterReason", "deadLetterErrorDescription");
}

```
I will get the following exception:

> Microsoft.WindowsAzure.Storage.StorageException: 'Not Found'

**Comment by SeanFeldman** [comment]
@markbeij you cannot instantiate a new client, you have to use the same client used to receive the message. My _assumption_ is that you have to declare it as an argument for your Function. But this is not ASB question thought, would you agree so? Rather, an Azure Functions question a different team would more than happy to answer 😉
