### ISSUE TITLE
Suggestion: a separate GH repo for ASB server side issues

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus-dotnet#90]
This repository is designated for the client.
There's no repository (for now) for the broker (server) side issues.
While there's a [UserVoice](https://feedback.azure.com/forums/216926-service-bus) forum, it is abandoned and doesn't serve its purpose as well as GH does.

I suggest to open a separate GH repo for the ASB server side for issues. It will allow tracking/reporting/linking/notification the way developers are accustomed to interact.

Additionally, it will help to connect client issues with server side issues (such as #89 and #46).

**Comment by jtaubensee** [comment]
Sure, check out [azure/azure-service-bus](https://github.com/azure/azure-service-bus)

**Comment by SeanFeldman** [comment]
To clarify, https://github.com/azure/azure-service-bus will be used for both, server and client side.

**Comment by jtaubensee** [comment]
Client side in what sense? The idea is that it would be used for:
* Service side issues and feature requests
* Samples
* Documentation issues

**Comment by SeanFeldman** [comment]
Got it. So the https://github.com/Azure/azure-service-bus-dotnet remains for the client. Right?

**Comment by jtaubensee** [comment]
Definitely. The only difference from how we've been working thus far, is that we now have a place for those things that seemed to be lacking a home previously.

**Comment by SeanFeldman** [comment]
👍
basically it's `azure-service-bus-!client` 😃
