### ISSUE TITLE
Update Projects to VS2017

### ISSUE THREAD

**Issue by ardalis** [Azure/azure-service-bus-dotnet#93]
## Actual Behavior
1. Projects use project.json

## Expected Behavior
1. Projects use .csproj

## Versions  
- OS platform and version:
- .NET Version:
- NuGet package version or commit ID:

**Comment by jtaubensee** [comment]
Hi @ardalis - We will probably do this shortly after VS 2017 is released on March 7th.

**Comment by ardalis** [comment]
Sounds good. I just opened the solution in the latest RC of VS2017 and everything converted over fine. However, I am getting a zillion (well, 434) roslyn analyzer errors. Currently trying to figure out how to turn those off...

**Comment by ardalis** [comment]
(apparently deleting the Stylecop package does the trick)

**Comment by jtaubensee** [comment]
Ha - We hopefully be able to revert what we did with #22, with the editor config settings.

https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options

Also, maybe this project will come back? [dotnet/codeformatter](https://github.com/dotnet/codeformatter)

**Comment by SeanFeldman** [comment]
🔥 StyleCop

**Comment by jtaubensee** [comment]
@SeanFeldman - Down with Style Cop? I can get on board with that. Thoughts on [dotnet/codeformatter](https://github.com/dotnet/codeformatter)?

**Comment by SeanFeldman** [comment]
T-7

**Comment by SeanFeldman** [comment]
Congrats on the alpha release again!
Looks like the time is right to switch over to VS2017.

With [`dotnet-migrate`](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-migrate) it looks straight forward.

Could we not introduce any code formatting tools and solely rely on [VS2017 coding styles](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options)? Or at least some code analyzers ([StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) looks like a solid [replacement suggested to the StyleCop team](https://github.com/StyleCop/StyleCop/issues/10))? If this is so important and there are guidelines for the MSFT org, ASB team shouldn't have reinvent the wheel and rely on what other teams are using (assuming there's such a thing 😉).

**Comment by jtaubensee** [comment]
Closing based on #127
