### ISSUE TITLE
Namespace name in the OnMessage exception handler

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#94]
Creating a new issue from part of #34.

Verbatim from @seanfeldman:
>When OnMessageOptions.ExceptionReceived event handler is invoked, it doesn't provide information on what namespace it's using. Having that information in the new client implementation would help for custom fail-over implementation.

**Comment by SeanFeldman** [comment]
Any opposition if I try to tackle this one?

**Comment by vinaysurya** [comment]
By all means :-)
