### ISSUE TITLE
Change Message.Body type to byte[]

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-service-bus-dotnet#98]
## Actual Behavior
* In the [.NET framework client](https://www.nuget.org/packages/WindowsAzure.ServiceBus/) a `BrokeredMessage` can be a serialize-able object, or a stream.

## Expected Behavior
* Change `Message` to only support `byte[]`
* We are proposing that the `Message` class be closely related to the Event Hubs [`EventData`](https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs/EventData.cs) class

## Why
* The use of streams makes extensibility much more difficult. The `Message` class is already a heavier object than it needs to be, and a majority of the logic in the class is around stream handling. For instance, if we want to make a handle to manipulate the `Message.Body` when sending or receiving a message, we need to be able to handle multiple streams, and "resetting" the body. This proposal would allow you to simply call something like: `message.Body = new byte[]();`
* Passing streams to Service Bus can result in a blocking send. For example, if you send a message with a stream and call send, the entire stream needs to be read (from where ever it is) into memory before the actual send occurs. This can cause users to think that there is an issue with Service Bus performance, when that is not actually the case.

### Edit:
Pointed out by @seanfeldman, this also means that we would remove the `DataContractSerializer` pieces as well.

**Comment by SimonCropp** [comment]
> the entire stream needs to be read (from where ever it is) into memory before the actual send occurs

why is this the case? cant the data be streamed all the way to the remote receiver? meaning the full byte array would never need to exist in memory

**Comment by jtaubensee** [comment]
@SimonCropp - Yes, that is correct. [Here](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs#L371) we actually call [StreamToBytes](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Amqp/AmqpMessageConverter.cs#L542) which will convert any stream to a `byte[]`.

**Comment by SimonCropp** [comment]
cant the data be streamed all the way to the remote receiver? meaning the full byte array would never need to exist in memory

**Comment by jtaubensee** [comment]
AMQP doesn't actually accept `Stream` as a data type, so our implementation of it in the past was just a "nice" feature for users. So either way we are holding the message in memory.

**Comment by SimonCropp** [comment]
so compat with AMQP is of a higher priority then performance?

**Comment by jtaubensee** [comment]
@SimonCropp - Two things:
1. We dont support that on the service side, so in order to realize that performance gain we would need to implement a new feature (which is not on our road map)
2. The `byte[]` model is loosely based on Event Hubs, which had 17.45 *trillion* requests last month, so the performance of it is pretty well proven, and not to mention that is always what Service Bus has done.

Really, the ability to pass a stream to a `BrokeredMessage` was simply a convenience for users, and we feel as though that convenience now comes with a cost that we are no longer willing to pay. As I mentioned above, it makes "plugins" much more difficult to manage, and it can be misleading when trying to bench mark Service Bus. We often have customers file support requests saying that their sends are taking a long time, when the latency is in fact caused by the reading of the stream, rather than Service Bus itself.

**Comment by SimonCropp** [comment]
fair enough. if it is not supported server side then u r correct that supporting a stream client side is unnecessary complexity and misleading to users.

Are streams still valid in any batch scenarios?

**Comment by jtaubensee** [comment]
Batch, as in `SendAsync(IList<Message>)`? We are proposing that in order to send a batch in this manner, all the `Message` bodies would need to be `byte[]`.

**Comment by SimonCropp** [comment]
Yep u r correct. Given the reasons u put forward byte array makes sense. 

Thanks for taking the time to get me up to speed

**Comment by jtaubensee** [comment]
Closing per #108

**Comment by duizendnegen** [comment]
This works less than optimal in combination with the Azure Scheduler. When scheduling to a service bus it mandates a body, when `azure-service-bus-dotnet` receives a message sent by the Azure Scheduler it throws an exception of not being able to convert `string` to `byte[]`.

Is there a way to work around this, to convince this library that the message really is a string after all? Or am I missing a way to address the Scheduler?

**Comment by jtaubensee** [comment]
@duizendnegen - You should be able to call `Encoding.UTF8.GetString(Message.Body)` in order to parse the body as a string.
